### ISSUE TITLE
Users from frontend to make/manage blog posts?

### ISSUE THREAD

**Issue by austinkregel** [rainlab/blog-plugin#100]
## Background

I run a web development company and I have a few clients who want to make blogs, but they don't like wordpress for their security issues and they think drupal is to complicated. So I said I would look into it. Now they are simple people, they don't like to see any kind of "fancy-fangled coding" or error pages. So that will be on me to make that happen but that also means I can't have them in the backend possibly messing with settings and breaking or destroying their website.
## Feature request?

I would love to be able to have the user management system (ums) plugin for OctoberCMS (OCMS) be able to interact with the blog management system (bms) plugin to allow the users a separate login and user experience from the backend users. In my case the backend would be for myself and my team to go in and make changes to the fundamentals of the website. Where as their blogs will be managed by their other system, the ums / bms. 
## Comments?

I'm not sure if someone else has a tutorial on how to do this or if I'd have to make my own plugin to get this kind of thing across, but I would love to be able to do this, and if anyone has already done this I would love to chat about it my email is [me@austinkregel.com](mailto:me@austinkregel.com)

Thank you.

**Comment by LukeTowers** [comment]
@austinkregel My advice to you would be to give them access to the backend through user accounts with limited permissions. Otherwise you'd have to build you own plugin to create and manage posts on the frontend, and then extend this one to support authors that are actually frontend users instead of backend users. Easiest solution by far is to simply use permissions.

**Comment by daftspunk** [comment]
Check out this plugin: https://octobercms.com/plugin/fireunion-blogfront
