### ISSUE TITLE
If a page has 2 components PostList

### ISSUE THREAD

**Issue by TheGreatMax** [rainlab/blog-plugin#102]
If a page has 2 components PostList, the entire pagination works on component 1.
I dont know how to fix that

for example
i have news in english and news in russian (its same path for translate blog)

<'div class="container">
<'div class=" row blog-list padding-top-20">
    <'div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
        <'h3 class="text-center">новости на русском</h3>
        {% component 'blogPosts' %}
    <'/div>
    <'div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
        <'h3 class="text-center">news in English</h3>
        {% component 'blogPosts2' %}
    <'/div>
<'/div>
<'/div>

**Comment by TheGreatMax** [comment]
for example
i have news in english and news in russian

<div class="container">
<div class=" row blog-list padding-top-20">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
        <h3 class="text-center">новости на русском</h3>
        {% component 'blogPosts' %}
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
        <h3 class="text-center">news in English</h3>
        {% component 'blogPosts2' %}
    </div>
</div>
</div>

**Comment by serversides** [comment]
Having the same issue myself.  Did you find a workaround?

**Comment by daftspunk** [comment]
We would need to see a sample theme to replicate and fix this.
