### ISSUE TITLE
Cant upload media

### ISSUE THREAD

**Issue by qazjayp** [rainlab/blog-plugin#105]
I have created a user with only Blog permissions.

All works apart from the featured image.

Im guessing thats a permission issue.

Any idea what permission needs to be activated for that to work?

**Comment by flip4bytes** [comment]
Oddly getting this error message as-well after update

![IMG](https://s3.amazonaws.com/f.cl.ly/items/3Q1q0R0Y3u0u080P2G1b/Image%202015-09-08%20at%2011.36.23%20PM.png)

I don't see why we can't just choose a featured image from the media selector though :/

**Comment by LukeTowers** [comment]
@abass That should be fixed by now, and @qazjayp your users would need permissions to upload files.

**Comment by daftspunk** [comment]
The `data` column missing error was a freak occurrence in one of the RC builds. Should be fixed by now.
