### ISSUE TITLE
Bug with Mime Types for uploading featured images

### ISSUE THREAD

**Issue by qazjayp** [rainlab/blog-plugin#107]
The blog validates the mime types as: 

$validationRules[] = 'mimes:jpg,jpeg,bmp,png,gif';

This works if the file extension is LowerCase.

If its uppercase, it fails.!!

Ive tested and this IS the case. 

Please could this be fixed.

**Comment by LukeTowers** [comment]
@qazjayp Feel free to add a PR for this

**Comment by daftspunk** [comment]
Actually, re-test it because I'm pretty sure we fixed this at the framework level. That's also where this should have been logged. Sorry for any confusion.
