### ISSUE TITLE
Posts published on future date showing in post listing

### ISSUE THREAD

**Issue by CrowderSoup** [rainlab/blog-plugin#11]
This may be more of a feature request, but I noticed this evening that if I check "published" and select a future date it still appears in the blog list immediately. Not only that, but I can also navigate directly to the blog post.

I would expect that selecting a future date would result in the post not showing in the post list until that date, and a 404 or "Cannot find post" message when it's navigated to directly. If this is not the desired behavior set me straight!

Thanks for the awesome plugins and CMS!

**Comment by jayalfredprufrock** [comment]
+1 This seems kind of important. I'm actually a little surprised to hear it doesn't work like that.
