### ISSUE TITLE
CLASS BACKEND\BEHAVIORS\IMPORTEXPORTCONTROLLER DOES NOT EXIST

### ISSUE THREAD

**Issue by Galixte** [rainlab/blog-plugin#111]
Hi,

after update october cms and plugins, i have this error: https://octobercms.com/forum/post/class-backendbehaviorsimportexportcontroller-does-not-exist

If i desactivate the BLOG plugin, the cms works without this error.

**Comment by Galixte** [comment]
In fact, that’s not resolve completly the problem.

**Comment by daftspunk** [comment]
Make sure your website is using the latest source code files for the October platform. It would appear it is reverting to an older build somehow.
