### ISSUE TITLE
How to show classic wysiwyg editor, not markdown?

### ISSUE THREAD

**Issue by vojtasvoboda** [rainlab/blog-plugin#112]
How to show classic wysiwyg editor instead of markdown editor? My clients don't know anything about `markdown` and trying to edit post in 'preview' area at the right side.

They want to edit content in same way as `staticPage` pages.

**Comment by gergo85** [comment]
You should try to the [Wysiwyg Editors](http://octobercms.com/plugin/anandpatel-wysiwygeditors) plugin.

**Comment by vojtasvoboda** [comment]
Yes, I tried it as first solution, but it doesn't work :-(

![snimek obrazovky 2015-08-19 v 11 03 40](https://cloud.githubusercontent.com/assets/374917/9352451/a2776e02-4661-11e5-97fb-a2d4104b3213.png)

![snimek obrazovky 2015-08-19 v 11 05 11](https://cloud.githubusercontent.com/assets/374917/9352469/c3a20fc4-4661-11e5-9df3-fdc195bf7648.png)

**Comment by robertsamurai** [comment]
Turning on "Use for RainLab Blog" doesn't work for me either, continues to use Markdown editor.  Markdown editor doesn't have options to insert Audio or Video using the Media Manager feature, so I prefer to use October's Rich Editor for posts.

**Comment by vojtasvoboda** [comment]
There is two way how to turn on Rich editor:

1) Edit `/plugins/rainlab/blog/models/post/fields.yaml` - rewrite `RainLab\Blog\FormWidgets\BlogMarkdown` to `richeditor`. BUT you lose it with first plugin update.

2) Better way, but little bit complicated - create own plugin (My.Site, or My.BlogBetter) and in Plugin.php add:

```
	public function boot()
	{
		// Extend all backend form usage
		Event::listen('backend.form.extendFields', function($widget) {

			// Extend only the Blog\Posts controller
			if (!$widget->getController() instanceof \RainLab\Blog\Controllers\Posts)
				return;

			// Extend only Blog\Post model
			if (!$widget->model instanceof \RainLab\Blog\Models\Post)
				return;

			// Update content field
			$widget->addSecondaryTabFields([
				'content' => [
		            'tab' => 'rainlab.blog::lang.post.tab_edit',
		            'type' => 'richeditor',
		            'size' => 'huge'
				]
			]);
		});
	}
```

Best solution would be to have possibility to overwrite YAML files in same way as config files or language files.

**Comment by vizo** [comment]
:+1:

**Comment by vojtasvoboda** [comment]
Fixed by https://github.com/anand-patel/oc-wysiwyg-editors/pull/51

**Comment by kubamarkiewicz** [comment]
The first solution (editing fields.yaml) work fine. 

However in the new version of blog plugin (1.2.6) that now supports translations you will also have to comment the following line 81 in Controllers/Post.php:
`$widget->secondaryTabs['fields']['content']['type'] = 'RainLab\Blog\FormWidgets\MLBlogMarkdown';`

**Comment by xseguib** [comment]
solution of @kubamarkiewicz worked for me, but if I comment that line translation is not showing I just changed that line
from
`$widget->secondaryTabs['fields']['content']['type'] = 'RainLab\Blog\FormWidgets\MLBlogMarkdown';`
 to 
`$widget->secondaryTabs['fields']['content']['type'] = 'richeditor';`

**Comment by daftspunk** [comment]
There are plugins available that can help with this. *ProBlog* is pretty popular.
