### ISSUE TITLE
Get category from post

### ISSUE THREAD

**Issue by felixinx** [rainlab/blog-plugin#115]
Hi,

I will like to have the category from the post page.

i try this : `$this->post->category->url` but is not working.

From the `blogPost` widget. Thanks.

Also, can we retrieve the author name using the `user_id`?

**Comment by rendler-denis** [comment]
Hello, @felixinx! 

For the author name checkout my answer on this ticket: https://github.com/rainlab/blog-plugin/issues/98

Hope it helps,
Denis

**Comment by felixinx** [comment]
Thanks. It will help!
