### ISSUE TITLE
CEO title not in rainlab_blog_posts table

### ISSUE THREAD

**Issue by ghost** [rainlab/blog-plugin#117]
Recently tryed October afres multiple projects done in Laravel. I got installed few plugins, including CEO and Blog. But when i try to save one post with dummy data, Lagagon gaves me this error:

```
"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'seo_title' in 'field list' (SQL: insert into `rainlab_blog_posts` (`user_id`, `title`, `slug`, `content`, `published`, `excerpt`, `seo_title`, `seo_description`, `seo_keywords`, `canonical_url`, `redirect_url`, `robot_index`, `robot_follow`, `published_at`, `content_html`, `updated_at`, `created_at`) values (1, Foo, foo, Lorem ipsum dolor sit amet, consetetur sadipscing elitr, 0, , , , , , , index, follow, , <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr</p>, 2015-08-16 18:37:48, 2015-08-16 18:37:48))" on line 624 of C:\laragon\www\october\vendor\laravel\framework\src\Illuminate\Database\Connection.php
```

Can it be caused by other modules uninstall ( not SEO || Blog || Blog Video ), or it is my fault?
Thanks for reply && sorry for my bad english!

**Comment by antidote314** [comment]
### Problem solved
After few tries, and uninstalling both plugins, first got installed blog, and before Seo, so Seo adds necesary cols to table. 
I hope this can be userfull to someone.

**Comment by wardemi** [comment]
Thanks :)

**Comment by gazatem** [comment]
can not remove seo related foreign key to blog post; therefore re-installation can not be done
