### ISSUE TITLE
Featured Image Filter

### ISSUE THREAD

**Issue by hollynnmccarthy** [rainlab/blog-plugin#120]
I want to call the featured image of each blog post so that I can use it on the blog post list page in addition to the title and summary. I know how to add the featured image (in the "manage" section of the blog post), but I simply want to call it so I can display them in the list on the blog page. Is there a {{ feature blog image }} filter?

**Comment by mlourens** [comment]
Late reaction, but still want to answer this one for further reference.
It is possible to call the featured images in your blog post list.

While looping trough the posts, every post has an array of featured images: `{{ post.featured_images }}`

To get the first one you can refer to `post.featured_images[0]` .
The featured_images is an object with different properties:

{
"id":3,
"disk_name":"56bbbd55641eb814687527.jpeg",
"file_name":"4abf-ab87-2c8e6dce5aba.jpeg",
"file_size":61164,
"content_type":"image\/jpeg",
"title":null,
"description":null,
"field":"featured_images",
"sort_order":3,
"created_at":"2016-02-10 22:44:37"
,"updated_at":"2016-02-10 22:44:40",
"path":"\/storage\/app\/uploads\/public\/56b\/bbd\/5b814687527.jpeg",
"extension":"jpeg"
}

For example: to get the location of the first featured image simply use `{{ post.featured_images[0].path }}`

**Comment by daftspunk** [comment]
Also try `{{ post.featured_images.first }}` for nicer syntax.
