### ISSUE TITLE
Thumbnail in blog list

### ISSUE THREAD

**Issue by goedda** [rainlab/blog-plugin#124]
Hi there

I would like to show a thumbnail instead of the full size image in the blog list. This does not seem to be possible, because the component does not inject the necessary data ("posts" variable). The images are part of the content and would have to be parsed, which I would like to avoid.
Is there a possibility to do that or do you have a suggestion how to do that?

regards goedda

**Comment by goedda** [comment]
Obviously, the featured images data is injected in the blog list as well. And well, the featured images have 200x200 px thumbnails, but this data is nowhere shown. It seems though to follow a pattern, so finally I did the following:

    {% if post.featured_images.count %}
    {# the first variable will select the first featured image of the respective post #}
    {% set first = post.featured_images|first %}
    {# the second variable will create the path to the thumbnail #}
    {% set src = first.path|trim(first.disk_name) ~ 'thumb_' ~ first.id ~ '_' ~ '200x200_0_0_crop' ~ '.' ~ first.extension %}
    <img
       data-src="{{ first.filename }}"
       src="{{ first }}"
       alt="{{ first.description }}"
    />
    {% endif %}

**Comment by johnnywo** [comment]
Thank you for your snippet! very useful for my project to!
