### ISSUE TITLE
Featured images are not erased with the respective post

### ISSUE THREAD

**Issue by jdmg94** [rainlab/blog-plugin#134]
the issue is the following, you write a post, you upload a couple of featured images, now, let's say you delete your post, and write a new one with no featured image, the post will load the featured images of the post we deleted, taking in consideration there are no further posts, most likely it is just taking the images acording to the posts place on the list not by the post itself

**Comment by LukeTowers** [comment]
The only thing that I can think of is that either the first post was never saved but the second had the same sessionKey which would have caused the deferred bindings attaching the featured images from the first post to be added to the new post, or that the first post was created, and then the table was truncated allowing the second post to take the id of the first post, which would then attach the previously detached featured images.

**Comment by daftspunk** [comment]
This should no longer occur, it was fixed at the framework level a long while back.
