### ISSUE TITLE
Featured image URL is incorrect when using sub directory installation

### ISSUE THREAD

**Issue by dontpanic** [rainlab/blog-plugin#135]
I've got October and the Blog set up on a `blog` sub directory. Other than that all I've done is install the blog plugin and SimplyBlog theme.

I have something like `<img src="{{ image.path|app }}"/>` in my page template, and it is resulting in a URL like `http://mywebsite.com/blog/blog/storage/app/uploads/public/560/ae5/0a5/560ae50a5427e993560884.png`. (Notice the duplicate /blog part)

Have I configured something wrong or did I stumble on a bug?

**Comment by daftspunk** [comment]
Tried?
```
<img src="{{ image.path }}"/>
```

**Comment by dontpanic** [comment]
@daftspunk Yep, and it works fine. I'd just like to use absolute URLs if possible. Thanks for the quick reply.
