### ISSUE TITLE
Spaces in image uploads and post content markdown.

### ISSUE THREAD

**Issue by dontpanic** [rainlab/blog-plugin#136]
Markdown's image tag doesn't support spaces in URLs (understandably). Unfortunately my less-than-savvy client immediately uploaded "Fun day at the beach.jpg" (worked fine) then tried to insert it into a Blog post (did not work, space in URL).

I think you could just escape the url before you place it into the editor and it'd work as intended. But I just started with October + Blog so I'm clueless =)

Thanks!

**Comment by nathanlesage** [comment]
As far as I can see, the function you would want to change resides in assets/js/post-form.js. If I'm correct, on line 54 someone who's better than me in JScript should include an escape function and it should work!

**Comment by daftspunk** [comment]
This will be fixed in Build 305+
