### ISSUE TITLE
AngularJS 

### ISSUE THREAD

**Issue by webgik** [rainlab/blog-plugin#146]
If I install this plugin 
https://github.com/responsiv/angular-plugin 
And try to use the blog plugin, it doesn't work anymore. The page with bloglists it's working, also the blog categories are loaded, but the component BlogPost it doesn't work. I can't see any details on blog post page.

**Comment by vojtasvoboda** [comment]
It looks like angular-plugin issue rather then blog-plugin

**Comment by LukeTowers** [comment]
@vojtasvoboda is correct, this would be an issue with the other plugin.
