### ISSUE TITLE
Functionality to quickly insert images without the media manager

### ISSUE THREAD

**Issue by nsrosenqvist** [rainlab/blog-plugin#147]
Now you have to upload and organize the images in the media manager, but when it comes to blogging that is just a big hindrance to me. I will never use the images anywhere else and if I want to insert a bunch of images into a gallery this takes a lot of work. I'd rather be able to have images "attached" to the blog post and have a button that instantly allows me to upload a new image without having to create a directory for the blog post on the file system.

**Comment by LukeTowers** [comment]
You can, through the use of featured images, which utilize the file attachments system of October, which aren't managed through the media manager.
