### ISSUE TITLE
behind the scenes: database or just files? 

### ISSUE THREAD

**Issue by adamjroe** [rainlab/blog-plugin#148]
Hi All,

we are setting up the blog plugin for a multi-person development environment. Does the blog need access to the database at any point, or is it purely file based? 

I am wondering here about setting up an environment where developers work locally, upload to a test server, then push the tested code to the live site. In addition, we have bloggers who would like to use the WYSIWYG in-browser editor. The question is what the least painful way to do it is. Our idea is to have the bloggers edit on the test server, then we push the code to our live server. But in our current formation, the DB is not transferred, only files. So this won't work if the blog needs the DB :). 

Thanks, 
Adam

**Comment by keiosweb** [comment]
To answer your question: this blog plugin stores categories and posts in database.

**Comment by LukeTowers** [comment]
@keiosweb is correct, the plugin stores content in the database.
