### ISSUE TITLE
Add Preview Image

### ISSUE THREAD

**Issue by kodermax** [rainlab/blog-plugin#149]
Could you please add new field preview image for blog post?

**Comment by kodermax** [comment]
Can i make this functionality and send request?

**Comment by kodermax** [comment]
Hello!

**Comment by keiosweb** [comment]
can you explain what do you mean by preview image? do you mean some sort of cover image for posts or what exactly? 

Although I don't think adding any new fields is good idea for pull request - usual "october way" is to create your own plugin that extends existing one with new fields that you require.

**Comment by LukeTowers** [comment]
@keiosweb is correct, extend this plugin through your own to add that type of functionality unless you can provide a convincing reason as to why it's required to be in this plugin.

**Comment by daftspunk** [comment]
I just use the first featured image as the preview image...

```
<img src="{{ post.featured_images.first.path }}" />
```

**Comment by LukeTowers** [comment]
And @daftspunk strikes again with a helpful solution after a shutdown by myself :)
