### ISSUE TITLE
Post Expiry Date

### ISSUE THREAD

**Issue by nathanjdunn** [rainlab/blog-plugin#152]
Hi,

Would it be possible to add a post expiry date/time to the post menu? I think a lot of users would find this useful as it means they do not have to remember to unpublish posts when they are no longer relevant.

Thanks,
Nathan

**Comment by WWRFresource** [comment]
Think this is similar to #312 ?

**Comment by LukeTowers** [comment]
Duplicate of #312, more conversation there so closing this.
