### ISSUE TITLE
Double slugs are allowed

### ISSUE THREAD

**Issue by twwd** [rainlab/blog-plugin#153]
I'm able to create two different posts with the same slug. When I open the corresponding url, the post which was created first, is displayed. Please add a slug validation and maybe auto renaming (i.e. /post and /post-1).

**Comment by dogiedog** [comment]
I added a pull request with a validation rule to prevent double slugs

https://github.com/rainlab/blog-plugin/pull/154

**Comment by daftspunk** [comment]
Fixed by #154
