### ISSUE TITLE
FR: KeyValue Pairs

### ISSUE THREAD

**Issue by ConnorVG** [rainlab/blog-plugin#16]
*NOTE: This is a feature request*

You should have the ability, in a specific tab, during blog post creation/editting to apply custom key-value pairs that can be accessed in the page.

Something like:
Key: [____________] Value: [_________________________________________] [ + ]

*pressing the [ + ] button would add another KeyValue pair*

Which when put in like:
Key: [something____] Value: [Something about something or something________]

and then do this in the page:
`{{ post.keyVal.something }}`

Outputs `Something about something or something` to the page.

This will help a lot with custom post types, such as:
In my usage I would have a youtube key and a disqus key which I would pass to partials to generate a specific youtube video and disqus thread.

**Comment by PhilMarc** [comment]
+1

**Comment by daftspunk** [comment]
It would be a nice feature, easy to add by extension.

**Comment by ConnorVG** [comment]
Maybe not so much in 2014 :stuck_out_tongue:

**Comment by daftspunk** [comment]
The feature reminds me a bit of WordPress, it wouldn't make much sense if you didn't need this feature, so we probably shouldn't include it by default. Besides there are many more (fun) ways to handle this type of functionality in 2016!
