### ISSUE TITLE
Post and Postlist displaying the same thing

### ISSUE THREAD

**Issue by allw1994** [rainlab/blog-plugin#160]
Hi,

I trying to get the blog plugin to work, i have managed to get postlist to work, but the post component on a completely separate page does not work.
it either:
1 - with no :slug in the URL, displays no posts,
2 - with :slug displays the same as the postlist page, including some text i added to test, it is literally identical, any suggestions are welcome at this point.

thanks!

**Comment by buckhornmktg** [comment]
Maybe my issue is related. When using the component on a page it works, but when I use the code from the plugin with custom markup, no posts are found and it really doesn't seem to matter what URL i use.

**Comment by daftspunk** [comment]
Check the [vanilla theme](https://github.com/rainlab/vanilla-theme) to get an idea how to use it

**Comment by buckhornmktg** [comment]
I see what my problem is now. I was using {% set posts = __SELF__.posts %} from the component not {% set posts = blogPosts.posts %} 

Thanks!
