### ISSUE TITLE
Filter by category name or slug

### ISSUE THREAD

**Issue by WebShapedBiz** [rainlab/blog-plugin#163]
Hi.

On static page, is it possible to specify the category filter like `categoryFilter = "MyCategoryName"`? Name or slug, it does not matter. I would like to skip URL for category name/slug definition.

Cheers.

**Comment by gmalagutti** [comment]
+1 need the same feature

**Comment by gmalagutti** [comment]
need the same feature

**Comment by r3k4** [comment]
+1 same here

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
