### ISSUE TITLE
How to use auto make slug feature for non-english character?

### ISSUE THREAD

**Issue by ghost** [rainlab/blog-plugin#17]
I'd like posts with non-english character title.

but, auto-slug feature not working.

How I can fix it? is there any code for non-english user's slug?

**Comment by dbYoung** [comment]
+1

**Comment by LukeTowers** [comment]
Relevant PR: https://github.com/octobercms/library/pull/178

**Comment by LukeTowers** [comment]
Should be fixed by https://github.com/octobercms/library/pull/178#issuecomment-302836370
