### ISSUE TITLE
category update broke blog backend

### ISSUE THREAD

**Issue by tobiasmathes** [rainlab/blog-plugin#171]
OctoberCMS 313
PostgreSQL 9.4.5-1.pgdg80+1 (postgres official debian binary)
PHP 7.0.2-1~dotdeb+8.1

Next Illuminate\Database\QueryException: SQLSTATE[42803]: Grouping error: 7 ERROR: column "rainlab_blog_categories.nest_left" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...s"."post_id" = "rainlab_blog_posts"."id" order by "nest_left...
^ (SQL:
```sql
select "rainlab_blog_posts".*, (select string_agg(name::VARCHAR, ', ')
from "rainlab_blog_categories"
inner join "rainlab_blog_posts_categories" on "rainlab_blog_categories"."id" = "rainlab_blog_posts_categories"."category_id"
where "rainlab_blog_posts_categories"."post_id" = "rainlab_blog_posts"."id"
order by "nest_left" asc) as "categories" from "rainlab_blog_posts" order by "published_at" desc limit 25 offset 0) 
```

**Comment by daftspunk** [comment]
Are you able to restructure this SQL to make it valid?

**Comment by tobiasmathes** [comment]
I did not attempt to restructure the SQL, but I can try.

**Comment by daftspunk** [comment]
I mean just paste it here, if we know what the valid SQL looks like, we can have a better shot at fixing it.

**Comment by tobiasmathes** [comment]
As far as I can tell, there is no problem with the query, the plugin update did not perform an update to the table :

```
october-# \dS rainlab_blog_posts_categories
Table "public.rainlab_blog_posts_categories"
   Column    |  Type   | Modifiers
-------------+---------+-----------
 post_id     | integer | not null
 category_id | integer | not null
Indexes:
    "rainlab_blog_posts_categories_pkey" PRIMARY KEY, btree (post_id, category_id)
```
and the file 'updates/categories_add_nested_fields.php' reads:

```php
Schema::table('rainlab_blog_categories', function($table)
        {
            $table->integer('parent_id')->unsigned()->index()->nullable();
            $table->integer('nest_left')->nullable();
            $table->integer('nest_right')->nullable();
            $table->integer('nest_depth')->nullable();
        });
```

**Comment by tobiasmathes** [comment]
Interestingly enough, this error ONLY occurs if I open */backend/rainlab/blog/posts*, the urls */backend/rainlab/blog/categories* and */backend/rainlab/blog/posts/create* work w/o problems.

**Comment by daftspunk** [comment]
Valid SQL would be
```
select
  "rainlab_blog_posts".*, 
  (select string_agg(name::VARCHAR, ', ')
    from "rainlab_blog_categories"
    inner join "rainlab_blog_posts_categories" 
       on "rainlab_blog_categories"."id" = "rainlab_blog_posts_categories"."category_id"
       where "rainlab_blog_posts_categories"."post_id" = "rainlab_blog_posts"."id"
  ) as "categories" 
from "rainlab_blog_posts" 
order by "published_at" desc 
limit 25 offset 0
```

**Comment by daftspunk** [comment]
Take a look at https://github.com/octobercms/october/commit/d8922c263f99a51d3b58947ac633622fd1aa1043

If you update this line, it should fix it

**Comment by tobiasmathes** [comment]
Yes, thank you! That fixed it. :) :+1:

**Comment by daftspunk** [comment]
Good stuff!
