### ISSUE TITLE
Component "Post List" is not recognizing CategoryFilter

### ISSUE THREAD

**Issue by tobiasmathes** [rainlab/blog-plugin#173]
October build 313
Blog plugin 1.2.2
PostgreSQL 9,5
PHP 7.0.2

I just found this out by accident, apparently the Post List is not recognizing the set CategoryFilter, which in my case is for the category "published", but I also tried to change the category and it didn't have any effect.

I looked in the code, but I am still to unfamiliar with laravel to make any impact. :(

**Comment by antonov-dev** [comment]
Maybe you add your CategoryFilter parameter just like property value? You should enter it like an external parameter name. You can switch the mode by clicking '>_' button near the field you need in component editor.

**Comment by tobiasmathes** [comment]
Already did that, it worked just fine before that 'nested category' update.

![github_october_catlist_failure](https://cloud.githubusercontent.com/assets/178869/12830278/b12a3792-cb8e-11e5-94b9-d43cd817d877.png)

**Comment by daftspunk** [comment]
Click the little `>_` icon and then enter "published". You have the category filter in external parameter mode so it is looking for a paramter called `{{ published }}`

**Comment by tobiasmathes** [comment]
That originally lead to an exception, something about nest_left and nest_right fubar. What helped was to remove the category, create a new one with the same name and sort all the articles back into it.

My assessment is still correct, the update with the nested categories broke the blog categories. Every before-update category is display the a "[+] name" in the backend. After re-creating the "Published" category it's just the "[ ] name" and now it works how it supposed to work.
