### ISSUE TITLE
Category title not work

### ISSUE THREAD

**Issue by vshepel** [rainlab/blog-plugin#178]
I have problem. This not work.
```
function onEnd()
{
    // Optional - set the page title to the category name
    if ($this->category)
        $this->page->title = $this->category->name;
}
```
Page have dafault title(
![image](https://cloud.githubusercontent.com/assets/14239290/12697823/4818a54c-c795-11e5-962b-e2931571b8fd.png)

**Comment by jimibi** [comment]
Because it can be multiple categories you should use
    
    $cat = '';
    $count = 0;
    foreach ($this["post"]->categories as $value) {
        $count++;
        $cat = $cat.$value-> name;
        if (count($this["post"]->categories) !== $count)
            $cat = $cat.', ';
    }
    $this->page->description = "Catégories: ".$cat;
