### ISSUE TITLE
Blog rss feed invalid with '&' symbol in blog post title

### ISSUE THREAD

**Issue by ixperiencenl** [rainlab/blog-plugin#181]
When I have a blog post with the '&' symbol in the title, this isn't being escaped properly and the RSS feed from the blog becomes invalid. The error that pops up then is: error on line 52 at column 42: xmlParseEntityRef: no name

When removing the symbol, the problem is gone.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
