### ISSUE TITLE
I can't make sort by category, whats wrong?(

### ISSUE THREAD

**Issue by m49n** [rainlab/blog-plugin#182]
[BlogPosts](http://joxi.ru/DrlvOddS4x7jb2)
[BlogCategory](http://joxi.ru/Rmz9g77SWwEllr)

Link with category (blog/category/hello), but displaying all categories
[Blog on page](http://joxi.ru/D2PKBwwId6nx0m)

**Comment by graker** [comment]
I may be mistaken but look at the "Category filter" property in Post List component. Specifically, note that the ">_" symbol's position. It's on the right. As I understand this symbol, if you want to type in url parameter, you have to have ">_" on the left as you do for "Page number" property. Just click on this symbol so it will appear on the left, then retype ":slug" as the value.  Should be working.

**Comment by m49n** [comment]
Thanks!!!! It Works :+1:

**Comment by warkarth** [comment]
i had a problem with categories because i tried to put a Post List in a partial inside a page, the problem result to be that, just you have to define te post list on the page, and copy the  {% component 'blogPosts' %} into the partial.

**Comment by armandoalmeida** [comment]
Thanks @graker! Now it works fine!
