### ISSUE TITLE
Blog Image broken on upload

### ISSUE THREAD

**Issue by marcoelho97** [rainlab/blog-plugin#183]
Everytime I upload an image, it breaks....
When I upload it, this is what shows up at the console:
http://prntscr.com/a41bhh
And this is how it looks in the upload:
https://gyazo.com/41516dbd7155e406305e614e3271e2ac

There are no error logs, and, as far as I'm concerned, There are no dependencies for blog.
As for space, I have 5gb of 35gb used, so, it can't be a space problem, and all folders have "755" permission.

Hope you can help me out here.

**Comment by LukeTowers** [comment]
@marcoelho97 Are you still having this issue after updating to the latest version?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
