### ISSUE TITLE
Publish workflow?

### ISSUE THREAD

**Issue by richlove1** [rainlab/blog-plugin#188]
Hope it's OK to post as an issue but there seems to be an obvious feature missing from the blog plugin that most CMSs implement, which is an publishing workflow.

I'd like to be able to give a backend user group (Blog Authors) the ability to author blog posts for our website but I would like to retain final publishing rights. 

It seems as soon as you give somebody 'Manage the blog posts' to enable them to author a post (desirable) they also get 'publish direct to live' rights also. I think it would be desirable to have 'Publish Blog Posts' as a separate permission

**Comment by LukeTowers** [comment]
If you're willing to implement it in a PR, I'm willing to review it to get it added :)

**Comment by daftspunk** [comment]
I agree this would be fantastic to have a workflow the allows a nice workflow

Draft -> Proof read required -> Published

This would make things like automatic posting to social media easier.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
