### ISSUE TITLE
Filter posts with ajax framework

### ISSUE THREAD

**Issue by Teranode** [rainlab/blog-plugin#194]
would there be any examples or way to filter posts with the ajax framework?
For instance lets say i want to change the sort by option or search without changing pages.

**Comment by kevinvermeulenn** [comment]
Hi @Teranode , 
Did you find a solution yet?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by 01Kuzma** [comment]
Long time passed since last reply.
Any news regarding this?

**Comment by LukeTowers** [comment]
@01Kuzma no, and you would be better served by asking for help on the forum or Discord instead of commenting on a four year old issue.
