### ISSUE TITLE
Add repair categories feature

### ISSUE THREAD

**Issue by qazjayp** [rainlab/blog-plugin#195]
My website is down out of the blue (blog version 1.2.2 )

Illegal operator and value combination.

Where('nest_left', '>=', null)

56  Illuminate\Database\Query\Builder->where(…)  
55  call_user_func_array(…)   ~/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php     526
54  Illuminate\Database\Eloquent\Builder->where(…)    ~/vendor/october/rain/src/Database/Traits/NestedTree.php    357
53  RainLab\Blog\Models\Category->scopeAllChildren(…)

**Comment by daftspunk** [comment]
What database engine are you using? Did you upgrade anything at all?

**Comment by qazjayp** [comment]
mysql.

No nothing updated at all.

**Comment by daftspunk** [comment]
Try this `php artisan tinker`

Paste in
```
foreach (RainLab\Blog\Models\Category::whereNull('nest_left')->get() as $category) {
    $category->setDefaultLeftAndRight();
    $category->save();
}
```

**Comment by qazjayp** [comment]
I get this from Tinker

php artisan tinker
PHP Fatal error:  Cannot use PhpParser\Node\Scalar\String as String 
because 'String' is a special class name in 
/home/forge/lifestyleproperty.co.uk/vendor/psy/psysh/src/Psy/CodeCleaner/MagicConstantsPass.php 
on line 19



   [Symfony\Component\Debug\Exception\FatalErrorException]
   Cannot use PhpParser\Node\Scalar\String as String because
    'String' is a special class name

**Comment by daftspunk** [comment]
Try putting it on a page with this PHP code
```
function onStart()
{
foreach (RainLab\Blog\Models\Category::whereNull('nest_left')->get() as $category) {
    $category->setDefaultLeftAndRight();
    $category->save();
}
}
```

Then open that page

**Comment by qazjayp** [comment]
This link: http://email.sidekick.org/c/eJwljjuOwzAQQ09jl8JIY_0KFZsAew99ZmLBXtiQlcK3XyEhWJEA-UpQ2YGda9AWDD6eRhjwYAGnBa5aaKt5E0d7zWvQmBOzWpyJhZkI9YKMiykcHWmy8x7W3s9rwp9J_Q7vlenq905nO05q_Rb5EO9tNH3kcwuNzv2e1AMA2bImrxMhDyCEbJ3TOsqcosukVIm-FGmk9YPNq8zwlZQoCyevvYrS-EzgUrbAfvB_5sWr9vWdxvXfP8swRw8

saved this:

function onStart() {

     echo 'called';

     $test = RainLab\Blog\Models\Category::whereNull('nest_left')->get();
     print_r($test->all());

     foreach 
(RainLab\Blog\Models\Category::whereNull('nest_left')->get() as $category) {
         $category->setDefaultLeftAndRight();
         $category->save();

     }
}

**Comment by daftspunk** [comment]
Looks like it's fixed now

We may need to include a "Repair categories" function because yours somehow became corrupted

**Comment by qazjayp** [comment]
How the hell is it working now?

Did the code you provide force a fix?

Somehow?

thanks

jon

**Comment by daftspunk** [comment]
Yes of course it did =)

**Comment by qazjayp** [comment]
thanks again for you help

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
