### ISSUE TITLE
Whereraw method ignores database prefix

### ISSUE THREAD

**Issue by firemankurt** [rainlab/blog-plugin#197]
Whereraw method ignores database prefix on line 82 of blog-plugin/components/Categories.php

https://github.com/rainlab/blog-plugin/blob/12d3d139e99330620f31bfdbc0f309ebf2db385d/components/Categories.php#L82

See original complaint : https://octobercms.com/forum/post/whereraw-method-ignores-database-prefix

**Comment by daftspunk** [comment]
Fixed by #198

**Comment by fahmyrm** [comment]
I've just installed OctoberCMS and encountered a (most likely) related error. When I open the /blog section I got an "Undefined variable: prefix" at \plugins\rainlab\blog\components\Categories.php line 83. I haven't even modify anything, so I thought it was my database setting or something, but the forum and account section (from Vanilla theme) worked just fine.

Any suggestion on how to fix this?

**Comment by daftspunk** [comment]
Thanks @fahmyrm, this should be fixed in 3f52d78a9e0704b78ac37712dc368b4af5146e03

@firemankurt please make sure you test your code before submitting pull requests! 😈
