### ISSUE TITLE
Dynamic Page Numbers in <head> title?

### ISSUE THREAD

**Issue by imkane** [rainlab/blog-plugin#201]
In my blog.htm Page, I'm trying to set a dynamic page # in the <head> title.  This is better practice for SEO than the default setup.

```
<?php
function onEnd() {
    $this->page->title = "Blog Page . $what_variable_goes_here" ;	
}
?>
```

I see it at the code at the top referenced as:
`pageNumber = "{{ :page }}"`
But I have no idea how to access that in PHP.

Any ideas?

**Comment by daftspunk** [comment]
```
$this->page->title = "Blog Page . $this->param('page')" ;   
```

**Comment by imkane** [comment]
Awesome, thanks!
