### ISSUE TITLE
Support for localized dates?

### ISSUE THREAD

**Issue by amdad** [rainlab/blog-plugin#202]
Hey @daftspunk  would be nice to see how new localized dates (from Build 329) should be used in frontend?

**Comment by daftspunk** [comment]
It's up to you how you want to `->format()` it

**Comment by amdad** [comment]
This function also support translation? 

I know how to format date to display in the way I want, but I don't know how to translate it. After last Build october backend now show properly translated month names to backend active language of page. I'm using Translate plugin and Blog still is always show up for example 13 December 2016 instead 13 Décembre 2016.

**Comment by daftspunk** [comment]
Learn from this script

https://github.com/octobercms/october/blob/develop/modules/backend/assets/js/october.datetime.js

We do it in the backend using JavaScript using Moment.js and Moment.timezone.js.

**Comment by amdad** [comment]
I just looking answer for this question: https://octobercms.com/forum/post/twig-date-format-cant-localized?page=1 Just thought, maybe after latest helpers you add there is new default way in october to do this. 

Load moment JS just for translate dates on frontend? Hm..

**Comment by daftspunk** [comment]
The multilingual support in PHP and Carbon is poor. We are yet to find a solution. The Twig extension looks interesting.

**Comment by daftspunk** [comment]
This is a larger question and should be moved to the main October issues list.

**Comment by amdad** [comment]
But are you agree it's a basic thing? Should this be in core. Now, in every language (other then en) we always see english months names. I thought if config/app.php  'locale' => 'fr', is set then all dates in font should be displayed in this translation. You just did in on backend. 

Twig string should be left untouched, just take some global setting to set lang for page from October or Translate plugin. 

Yes, I ask here not in october main repo because I thought this function was added in Build 329.

Should I start issue in October repo for this case?
