### ISSUE TITLE
Add ability to select Featured Image from Media Manager

### ISSUE THREAD

**Issue by ellier** [rainlab/blog-plugin#204]
Featured images can only be uploaded.
We should have the ability to set the featured image for a post from the Media Manager.

**Comment by SamReez** [comment]
Yes, I require this functionality to be added as well please.

**Comment by daftspunk** [comment]
This could be added easily by creating a plugin that extends the Blog plugin. See [OB-10 article](http://octobercms.com/support/article/ob-10) on how to do this.

**Comment by FasTraxPOS** [comment]
Still not an option?
