### ISSUE TITLE
Output Author Information and Display Post List By Author

### ISSUE THREAD

**Issue by Atorui** [rainlab/blog-plugin#206]
I do not see this in documentation. So I request this enhancement, how to output author information, and display post list by author.

**Comment by LittleTom** [comment]
use this tag {{ post.user.full_name }} at blog-posts or blog-post

**Comment by Atorui** [comment]
How about outputting the author avatar?

**Comment by AramLoosman** [comment]
You can use {{ post.user.avatar.path }} for displaying the avatar.
