### ISSUE TITLE
Not load post

### ISSUE THREAD

**Issue by uitlaber** [rainlab/blog-plugin#207]
`protected function loadPost()
    {
        $slug = $this->property('slug');
        $post = BlogPost::isPublished()->where('slug', $slug)->first();
...
`
mybee  ?
`protected function loadPost()
    {
        $slug = $this->param($this->property('slug'));
        $post = BlogPost::isPublished()->where('slug', $slug)->first();
`

**Comment by LukeTowers** [comment]
This makes no sense.

**Comment by daftspunk** [comment]
Code is this already

```
$slug = $this->property('slug');
```

So we are good then!

**Comment by daftspunk** [comment]
If you want to access it via the param, use this

```
slug = "{{ slug }}"
```

That will take the value from the URL param
