### ISSUE TITLE
Feature Request: Publish Time

### ISSUE THREAD

**Issue by dylanjacob** [rainlab/blog-plugin#208]
It would be nice to be able to set a time for which a post was/should be published. Ideally, this would allow including the timestamp on the frontend if desired, and allow to set the time at which a post will be published when setting the publish date in the future.

Currently, when a post's publish date is in the future, the post does not publish until that date, but the time is not adjustable. The post will always publish at midnight (relative to the timezone defined in php.ini, or the system's local timezone), but if the user would like to publish at noon, or another time, this is unachievable. Adding a separate field for time (separate both in the Create/Update UI as well as how it retrieved from the CMS when the post is displayed) will allow the publish time to be set without affecting how users currently display the publish date.

**Comment by graker** [comment]
Hi Dylan

Until maintainers decide whether or not to allow setting a publish time by default, this pull request: #180 will probably help you. You see, this feature is implemented already, it is just turned off by default. Personally I'd love to see it turned on in the original plugin. But you can always change one line of code to have it anyway.

**Comment by daftspunk** [comment]
Thanks @graker!

Fixed by #180

**Comment by haythameyd** [comment]
Is is possible to edit the published_at field after setting it for the first time? for me it doesn't work at all, once it's set, it stays there with this date, also is it possible to change the date format from month day year to day month year?

**Comment by LukeTowers** [comment]
@haythameyd Those would be separate issues, please report as such and make sure you include detailed information. Remember, the more information you can provide the more likely it is that we can help.
