### ISSUE TITLE
blog-plugin don't translate content. how to solve?

### ISSUE THREAD

**Issue by lieroes** [rainlab/blog-plugin#210]
Hi, Rainlab,
 I found the bug. 
 Can't translate "content" field in blog plugin. 
 In "Post" model translatable setted only "content" field but in component we display "content_html" which are not translated. 
 "title", "excerpt" - works fine!

 So, how to solve this? Thank you.

**Comment by amdad** [comment]
The same problem here. Any solution?

**Comment by amdad** [comment]
Second thing is.. Categories also should be translatable. Perfect would be if slugs be too.

**Comment by minux84** [comment]
+1

**Comment by minux84** [comment]
The same thing even if I use WYSIWYG editor. I think it's related to javascript that rewrite the DOM for those components...

**Comment by Eoler** [comment]
Workaround is to change default component partials to use
`content|md|raw`
instead of
`content_html|raw`
until this is fixed.

**Comment by amdad** [comment]
Thanks!
