### ISSUE TITLE
Add a CSS class to images

### ISSUE THREAD

**Issue by quochuy** [rainlab/blog-plugin#211]
Hi

How can you add a css class to images embedded in a blog?
Or can you edit an HTML template that renders the blog post content so I can alter the image tag?

Thanks
Huy

**Comment by CptMeatball** [comment]
As a workaround, can't you use css selectors?

For example:
```
.cover-image > img {
  /* custom styles */
}

.gallery-images img {
  /* custom styles */
}
```

**Comment by quochuy** [comment]
Hi

Thanks
I later on discovered you can add classes to the images by using markdown language

Regards
Huy

-- NGUYEN DINH Quoc-Huy
Web Developer : PHP, HTML, CSS, JavaScript, jQuery, PhoneGap, Appcelerator Titanium

M: + 61 416 510 892 (tel:+%2061%20416%20510%20892) | E: mailto:contact@quoc-huy.com | W: http://www.quoc-huy.com (http://www.quoc-huy.com/)

**Comment by daftspunk** [comment]
Huy is referring to this syntax:

```
![test](image.jpg]{.class}
```
