### ISSUE TITLE
How can I use ".html" suffix at the blog-post's slug

### ISSUE THREAD

**Issue by LittleTom** [rainlab/blog-plugin#215]
There are some things I don't understand. How can I use ".html" suffix at the blog-post's slug, let me use URL(like "www.mysite.com/blog/first-artical.html") to visit.  It's very important to SEO.

**Comment by daftspunk** [comment]
It is an interesting question, there is no way to do this via [the page URL syntax](http://octobercms.com/docs/cms/pages#url-syntax). This is possible, but not very nice:

```
url = "/blog/post/:slug/.htm"
```

Feel free to log an issue in the main [GitHub repo](https://github.com/octobercms/october/issues) to see if we can introduce a feature to allow parameter prefixes/suffixes. For now, I suggest something like this

```
function onStart()
{
    // Make sure the URL does not end in .htm / .html
    return $this->stripHtmlFromUrl();
}

function stripHtmlFromUrl()
{
    // Redirect .html|.htm away
    $slug = $this->param('slug');
    if (ends_with($slug, ['.html', '.htm'])) {
        $redirect = $this->currentPageUrl(['slug' => str_replace(['.html', '.htm'], '', $slug)]);
        return Redirect::to($redirect, 301);
    }
}
```

**Comment by LittleTom** [comment]
Thank you very much
