### ISSUE TITLE
rainlab_blog_posts.content_html does not update

### ISSUE THREAD

**Issue by LaravelNick** [rainlab/blog-plugin#218]
When using the latest build of October CMS (Stable release) and the latest version of the Blog plugin in conjunction with the Wysiwyg Editors plugin (Froala), when updating a Blog Post, the rainlab_blog_posts.content column updates, but the rainlab_blog_posts.content_html column does not.

**Comment by daftspunk** [comment]
Wasn't able to replicate this:

1. Created a new blog post
1. Saved the blog post
1. Checked the table and saw `content_html` is populated
