### ISSUE TITLE
Plugin can not be updated on 'old' OctoberCMS 

### ISSUE THREAD

**Issue by ametad** [rainlab/blog-plugin#221]
After the big release of OC that implemented Laravel 5.1 this plugin cannot be updated on not fully upgraded OC instances.

This is because the implementation of this: https://octobercms.com/support/article/rn-4 (Build 332 - Invalid timestamps with MySQL strict mode)

The needed migration uses a newly introduced method
```
 DbDongle::convertTimestamps();
```
(commit here: https://github.com/octobercms/library/commit/8d336ecf75c1635f572d9a91a112292068a59d60#diff-755ded99d51c2e48f909222774b7057f)

## Problem

The update of this Blog plugin can be obtained (downloaded bij an update on the backend) in a 'old' version of OC, but after that the update migration fails because of the missing function 'convertTimestamps()'. After that you have a not correct working site.

## Suggestion

Such a upgrade of the plugin should be marked as 'breaking changes' with '!!!' as described here"https://octobercms.com/docs/plugin/updates#important-updates

**Comment by ametad** [comment]
Thank you Samuel Georges for answering related question here: http://stackoverflow.com/questions/38348102/how-to-implement-dbdongleconverttimestamps-as-workaround-of-invalid-timestamps

**Comment by daftspunk** [comment]
No problem! I hope it helps.
