### ISSUE TITLE
Custom attributes in Post's Markdown

### ISSUE THREAD

**Issue by vdomah** [rainlab/blog-plugin#224]
I want to add rel="somevalue" to a link. 

Found this construction to do this:
[a special url](/my-special-place.html){: rel=special}

But that doesn't work. What's the solution?

**Comment by daftspunk** [comment]
For now the best solution is to just use HTML

```
<a href="#" rel="special">...</a>
```

There are many different flavors of Markdown, I'm not sure if the version we use supports the syntax:

```
[a special url](/my-special-place.html){: rel=special}
```
