### ISSUE TITLE
Related blog posts

### ISSUE THREAD

**Issue by wvelez6** [rainlab/blog-plugin#225]
![posts_related_posts](https://cloud.githubusercontent.com/assets/7291247/17281588/a1fa0b18-576a-11e6-9042-d80c3f92d05d.jpg)

Doing a site for a non-proft organization using OctoberCMS, most of the site is done and they requested if I could add  to the bottom of the post page three related posts. I attached a mockup of what they want and I have search online and asked on slack channel but apparently I need to be a developer.  I'm starting in development and can go thru using documentation but cant find nothing similar to this request. Can someone please help me.

**Comment by daftspunk** [comment]
I wonder: What logic would be used to determine what is a related post?

**Comment by ribsousa** [comment]
this is what you seek!

https://octobercms.com/plugin/bedard-blogtags

**Comment by wvelez6** [comment]
@daftspunk The logic would be by category, so if the main post is under the category "Test" then the previous three post under the test category will pop under the new post. @ribsousa I tried that plugin and works, but only gives me a list of related posts by tags. They want a Title and excerpt of the latest post by category. They claim that users would be more interested and staying longer in the page if at the bottom they see related posts.

**Comment by daftspunk** [comment]
Thanks @ribsousa, looks great!

@wvelez6 Perhaps you can contact this author with your idea?

**Comment by ribsousa** [comment]
Hello @daftspunk

And I developed a simple solution components override partial blogspot and BlogPost and passing variables to the partial, see here http://gleebe.com/pt-br/blog/

**Comment by daftspunk** [comment]
@ribsousa Do you mind sharing your solution? Or does it use the plugin you mentioned above, using tags?

**Comment by wvelez6** [comment]
@ribsousa that's exactly what my client wants, @daftpunk probably you can implement into blog plug-in as component.

**Comment by daftspunk** [comment]
Feel free to submit a pull request, if the feature is clean, we can accept it.

**Comment by ribsousa** [comment]
You do not need a plugin for that!
follow these steps:

**1** - create a partial named **relatedPosts/default.htm** and add the code
`{% set posts = __SELF__.posts %}`

`{# In the loop we excluded the post being displayed list of related posts by variable postFilter passed by the partial #}`
`{% for post in posts if post.slug != postFilter %}`

 `{# Here you show what you want #}`
`<a href="{{ post.url }}">{{ post.title }}</a>`
`<p>{{ post.summary }}</p>`    
   
`{% enfor %}`

   `{% else %}`
         `<h5 class="no-data">{{ noPostsMessage }}</h5>`


**2** - create a partial named **related.htm** add **blogPosts** component to it, change the alias name for **relatedPosts**, set Category filter with the parameter **categoryFilter** and set Post per Page with the number of posts you want, example **3**


**3** - create a partial named **blogPost/default.htm** and add the code below, this override the default partial component

`{% set post = __SELF__.post %}`
`<h4>{{ post.title }}</h4>`

`{% if post.featured_images.count %}`
    `<div class="featured-images text-center">`
        `{% for image in post.featured_images %}`
           ` <p>`
                `<img`
                   ` data-src="{{ image.filename }}"`
                 `   src="{{ image.path }}"`
                  `  alt="{{ image.description }}"`
                   ` style="max-width: 100%" />`
           ` </p>`
        `{% endfor %}`
    `</div>`
`{% endif %}`

`<div class="content">{{ post.content_html|raw }}</div>`

`<p class="info">`
  `  Posted`
   ` {% if post.categories.count %} in`
       ` {% for category in post.categories %}`
           ` <a href="{{ category.url }}">{{ category.name }}</a>{% if not loop.last %}, {% endif %}`
        `{% endfor %}`
  `  {% endif %}`
    `on {{ post.published_at|date('M d, Y') }}`
`</p>`


`{# this code pass variables categoryFilter and postFilter for partial related.htm filter a list de related posts for active category #}`

`{% if post.categories.count %}`
       ` {% for category in post.categories %}`

`{% partial 'related' categoryFilter = category.slug postFilter = post.slug %}`

`{% endfor %}`
`{% endif %}`


**4** - Create the page named **post** or a name of your choice to display the post info and add **blogPost** component, ready now you will get a list of related posts displayed

**Comment by wvelez6** [comment]
@ribsousa I followed your instructions to the dot but can't get it to work. Do I need the plugin you suggested before in order for this to work?

**Comment by daftspunk** [comment]
@ribsousa  Looks like there might be some typos in the suggested code.  @wvelez6 Paste any error messages you get, that would be helpful.

**Comment by wvelez6** [comment]
@daftspunk No errors were displayed.

**Comment by ribsousa** [comment]
It is not necessary any plugin , if done properly should work , I'll review the code to see if there is some mistake ...

**Comment by ribsousa** [comment]
I found an error in step **1**, here's the corrected code

**1** - create a partial named **relatedPosts/default.htm** and add the code
```
{% set posts = __SELF__.posts %}
      
         {# In the loop we excluded the post being displayed list of related posts by variable postFilter passed by the partial #}
         {% for post in posts if post.slug != postFilter %}

             {# Here you show what you want #}
            <a href="{{ post.url }}">{{ post.title }}</a>
            <p>{{ post.summary }}</p>  
   
          {% else %}
          <h5 class="no-data">{{ noPostsMessage }}</h5>
      
         {% endfor %}
```

**Comment by wvelez6** [comment]
Unfortunatly, it's not working for me, I followed all the steps again, deleted all the partials and the page and started fresh and doesn't work.

**Comment by ribsousa** [comment]
If you want I can do it for you, just give access to the back end of your application, I can help you!

**Comment by wvelez6** [comment]
What email should I sent it to?

**Comment by ribsousa** [comment]
ribbsousa@gmail.com

**Comment by wvelez6** [comment]
Thank you so much Ronaldo. I think this would be a great feature to add as a component for beginner users like me. It would be great to just drag and drop a component and choose the amount of related posts to display. God bless you both.

**Comment by brianwachira** [comment]
So there is a plugin created to display related articles of a post. 
It basically displays all the other posts of that category.
[https://octobercms.com/plugin/tallpro-related](url)
The documentation is clear and it works like a charm!!

**Comment by bennothommo** [comment]
@brianwachira There's no need for a plugin for that - you can simply pass the category to a Posts component on your blog page, and put the current blog post into the `exceptPost` property, and that would do the same thing.
