### ISSUE TITLE
Missing sortOrder property in RssFeed component

### ISSUE THREAD

**Issue by thewizardplusplus** [rainlab/blog-plugin#226]
sortOrder property is used in `RssFeed::listPosts()` method ([here](https://github.com/rainlab/blog-plugin/blob/master/components/RssFeed.php#L115)), but not defined in `RssFeed::defineProperties()` method. The public field `RssFeed::$sortOrder` is also missing.

Therefore impossibly select a sort order for RssFeed component in the page editor:

![screenshot](https://cloud.githubusercontent.com/assets/3732121/17359663/b5dcf144-5978-11e6-8d21-9754daf0202e.png)

It's very useful feature, please add sortOrder property.

**Comment by daftspunk** [comment]
Feel free to submit a Pull Request for this.

**Comment by thewizardplusplus** [comment]
This issue was fixed by @graker in the pull request #235.
