### ISSUE TITLE
Specifying a different "Slug param name" than ":slug"

### ISSUE THREAD

**Issue by jiiis** [rainlab/blog-plugin#230]
Very useful plugin. Good job!

Just wondering if it is a bug that in the recent versions we can't specify a different `slug param name` than `:slug`?

For example, if we have a `blog post page` with URL 

```
/post/:post
```

and in the "Post" component we have

```
slug = "{{ :post }}"
```

Then the blog post page would work well. That said, the `post page links` generated in other pages would be incorrect.

For example, say we have a `blog category page`, which uses the `Post List` component to display a list of posts and we specify the `blog post page` we just created to be the `Post page`, then the links generated for posts would be something like

```
domain.com/post/default
```

where the `default` should instead be the real slug of the post.

This problem can be avoided by using `:slug` as the `post slug param name` in the `Post` component.

I think this can be a bug in recent versions of the `Blog` plugin, because in the demo video of this plugin, there used to be 2 configurations for `Post page links`
- `Post page`
- `Post page param name`

But now there is only `Post page` and we are no longer able to tell the `blog category page` that the `slug param name` for a generated `post page link` should be `:post` rather than the default `:slug`.

The `category page link` has exactly the same problem.

So any reason that we removed the `Post page param name` and `Category page param name` settings from `Post List` component?

Thanks.

**Comment by daftspunk** [comment]
This likely occurs because of the `setUrl` method inside the Post model:
```
    public function setUrl($pageName, $controller)
    {
        $params = [
            'id' => $this->id,
            'slug' => $this->slug,
        ];
```

It means the `slug` is a "fixed" parameter name when generating the links using the standard workflow. This isn't really a big issue because if you want to call it `post` instead, you should just use your own markup entirely, and would generate your own links anyway:

```
{{ 'blog/post'|page({ post: post.slug }) }}
```

This is necessary when entering this realm of customizations, and it isn't accommodated by the plugin to keep it simple and easy to understand. In most cases the slug parameter can be fixed with no worries, yet there is still a possibility to call it anything, it requires to step out of the norm.

**Comment by jiiis** [comment]
Hi @daftspunk, Thanks for answering. Yes, the link is exactly what I needed.

And I agree most of the times using `:slug` would  be good enough. The reason I wanted to use a different slug name is that I had

* Component `Category List` in the `default` layout
* Component `Post List` in the `Category` page (listing posts from a given category) which uses the `default` layout
* Component `Post` in the `Post` page which also uses the `default` layout

I used `currentCategorySlug` in the layout to decide the active category.

This would work well for the `Category` page. However, in the `Post` page, `currentCategorySlug` would pick up the value of the `slug URL param`, which would be the `post slug`. It should be `null` or some other falsy value, right?

Now I'm not even sure if specifying different slugs for `Post List` and `Post` in the `Category` page and `Post` page would solve the problem because I just tested it and found that even though I set `slug = "{{ :post }}"` for the `Post` component, the `currentCategorySlug` would still be whatever the `:post` value was.

**Comment by jiiis** [comment]
Sorry, I was wrong, using different slug names can actually fix the issue. : )

Still it looks like a little hack to me. Maybe `currentCategorySlug` can be smarter to pick up only the `category slug` from the environment?

And also given that `:slug` should be the only proper `slug variable name`, maybe it should not be configurable? Oh, people may need to set static values.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
