### ISSUE TITLE
List of variables

### ISSUE THREAD

**Issue by eduardoanimastapia** [rainlab/blog-plugin#233]
I'm trying to display the name of the post and the author in a Bootstrap jumbotron. Is there a list of all the variables exposed by the blog component?

**Comment by daftspunk** [comment]
Try using the `dump()` twig function on the component to see the variables inside. Eg:

```
{{ dump(blogPost) }}
```

You can also just render the post to the page and it will render as JSON, eg:

{{ blogPost.post }}

**Comment by eduardoanimastapia** [comment]
Using
`{{ dump(blogPost) }}`
does not dump all the variables: 
![capture](https://cloud.githubusercontent.com/assets/9285731/17640867/378fcb2e-60d8-11e6-89c1-168113d702e3.PNG)
while rendering the JSON outputs the necessary variables.
_Excerpt from JSON rendering_
```json
{
"id":2,"user_id":1,
"title":"Writeup: APMN",
"slug":"writeup-apmn",
"excerpt":"A technical writeup on the development of a prototype site for APMN"
}
```

**Comment by daftspunk** [comment]
Apologies, it should be

```
{{ dump(blogPost.post) }}
```

Cheers
