### ISSUE TITLE
Block vs Translate plugin

### ISSUE THREAD

**Issue by andrejpavlik** [rainlab/blog-plugin#234]
Hi. If I install them together, there is no correct translation displayed for the Excerpt in the Posts list. The Names of the posts are OK and translated. You can see a screenshot, where the names are in English and the Excerpts are in spanish. Could you repair it, please? 
Thanks.
Andrej.

**Comment by daftspunk** [comment]
Except should be translatable as per the Post model spec?

    public $translatable = [
        'title',
        'content',
        'content_html',
        'excerpt'
    ];

**Comment by andrejpavlik** [comment]
Yes, the excerpt is not translated. It is only in the default language no matter of selected language.
Thanks.

**Comment by norbitoth** [comment]
Hi,
I have the same problem, but the Post model is set correctly.
Do you have any idea?

Thanks,
Norbert

**Comment by daftspunk** [comment]
This has been replicated

**Comment by daftspunk** [comment]
Fixed in v1.2.11
