### ISSUE TITLE
How to display blogPosts list on the homepage (root / of the site)?

### ISSUE THREAD

**Issue by jakub2** [rainlab/blog-plugin#242]
Hi, I'm trying to get my blogPosts list on the homepage of my OctoberCMS site (the root of the website, i.e. `/`). The URL of my blog page is : `/blog/:page?`. When I go to the root `/`. How can I get the blogPosts list on my homepage (i.e. root `/`) please?

**Comment by jan-vince** [comment]
You can add **Blog posts** component to your page (or layout, or partial) and inside this page, you can access blogPosts object.

***[How to add component is here](https://vimeo.com/97088926), 5:41***

In page, you can render posts like this:

`{% for post in blogPosts.posts %}    `

`    <h5>{{post.title}}</h5>    `

`    <p>{{post.content_html|raw}}</p>    `

`{% endfor %}    `
