### ISSUE TITLE
special blog post types

### ISSUE THREAD

**Issue by webeks** [rainlab/blog-plugin#243]
Hi

I would need to display some special types of blog posts. For example youtube video, image, quote etc. Check [this template](http://preview.themeforest.net/item/goodinc-flat-responsive-wordpress-blog-news-theme/full_screen_preview/5285055) to see what I mean. 

One possibility would be to make 3 **new plugins** which I believe is waste of time since Blog is covering most functionalities already.

I could introduce special **blog post types** as a dropdown under Post->Manage.
Or I could achieve this by **extending categories** to have special meanings. 

Is this something you would incorporate into BlogPlugin or should I just make an **extension**?

Best,
Miha

**Comment by jan-vince** [comment]
I have used [Blog tags](https://octobercms.com/plugin/bedard-blogtags) plugin for this - tags had "special meaning" inside template.

**Comment by webeks** [comment]
Thanks for the tip. Will look into it (y)

**Comment by webeks** [comment]
@jan-vince so you basically hard coded "filters / types" inside template?

**Comment by webeks** [comment]
OK figured it out :) I will just add additional fields to theme.yaml to add "special" tags/categories and then use this for display. Closing ticket. Thanks!
