### ISSUE TITLE
There is no way to make the slug of the post translatable.

### ISSUE THREAD

**Issue by EMFLUX** [rainlab/blog-plugin#244]
The plugin is very useful!

There is no way to make the slug of the post translatable.

For the moment when I add a new post, the post title and the body are translatable but the slug is unique.

**Comment by daftspunk** [comment]
I am fairly certain we added support for this recently. Is there a problem with it? If so, as per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by xseguib** [comment]
Works fine, but translate plugin for me and my workmate feels a bit buggy, see issue https://github.com/rainlab/translate-plugin/issues/167 , for instance, if i am in the spanish version of a post and switch to eng does not translate the slug of the url. I needed to do a try catch, but only enters to catch the first time I switch, other times the try code works.


try {
		$this['post']=Post::transWhere('slug',$this->param('slug'),\App::getLocale())->firstOrFail();
} catch (Exception $e) {
		// dd('catch');
		$slugtranslated=Db::table('rainlab_blog_posts')
->join('rainlab_translate_indexes','rainlab_blog_posts.id','=','rainlab_translate_indexes.model_id')
->where('rainlab_translate_indexes.locale',\App::getLocale())->first();
		// dd($slugtranslated);
		return redirect(\App::getLocale().'/blog/'.$slugtranslated->slug);
	}

**Comment by daftspunk** [comment]
Moving to rainlab/translate-plugin#167
