### ISSUE TITLE
Category list ordering does not work

### ISSUE THREAD

**Issue by vanmil** [rainlab/blog-plugin#260]
Hi all,

The ordering of the categories by name is not working as far as I know. 

[Blog-plugin/components/Categories.php](https://github.com/rainlab/blog-plugin/blob/master/components/Categories.php) line reads as follows:
`$categories = BlogCategory::orderBy('name');`

I think that line _should_ do the ordering, but it somehow gets overwritten by another sorting on id or something. Does someone maybe know how to fix this?

Thanks, Jelle

**Comment by daftspunk** [comment]
The category list uses Nested Sets, so the order is fixed based on the reorder page. To find this page, navigate to **Blog > Categories > Reorder Categories**.
