### ISSUE TITLE
After Upgrade to the latest OctoberCMS and Blog version, the Read More Tag plugin doesn't work anymore. 

### ISSUE THREAD

**Issue by rxd29** [rainlab/blog-plugin#262]
After Upgrade to the latest OctoberCMS and Blog version, the Read More Tag plugin doesn't work anymore for the excerpt.
It worked perfectly prior to the upgrade and I could overcome the limitation of the blog post's component standard excerpt styling and now again it looks aweful :-(
My October CMS Version build: 382
Blog Version: 1.2.14
I also posted this in the Read More Tag plugins Support Forum.
Any idea for a workaround how I can fix it on my own?

**Comment by daftspunk** [comment]
Added docs for using the `<!-- more -->` tag

## Excerpt Vs. Read more

Posts are managed by selecting *Blog > Posts* from the menu. Each post can contain an excerpt by entering some text in this field on the *Manage* tab. This content is displayed on the page using the `summary` attribute of the blog post.

    {{ post.summary }}

Alternatively this field can be left blank and the excerpt can be captured from the main content (*Edit* tab). Use the special tag `<!-- more -->` to specify a summary from the main content, all content above this tag will be treated as the summary. For example:

    This is a great introduction to a great blog post. This text is included as part of the excerpt / summary.

    

    Let's dive in to more detail about why this post is so great. This text will not be included in the summary.

Finally, if no excerpt is specified and the "more" tag is not used, the blog post will capture the first 600 characters of the content and use this for the summary.

> **Note**: The HTML contents will be stripped from the `summary` attribute.
