### ISSUE TITLE
RE #262 After Upgrade to the latest OctoberCMS and Blog version, the Read More Tag plugin doesn't work anymore.  

### ISSUE THREAD

**Issue by rxd29** [rainlab/blog-plugin#263]
I tried the fix, but it's now a funny letter puzzle with scrambled letters and symbols scattered all over the screen :-( :-(
Just to reproduce:
- My "read more tag" plugin is active
- In my "Posts" pages I have set `<p class="excerpt">{{ post.content_html|untilMore('post'|page({'slug': post.slug})) `}}</p>` as advised per plugin
- In my single blog Post item set the `<!--more READ `MORE`-->`
- I changed the 3 files i.e. Post.php, default.htm (and README.md)
Result: see 1st line
2nd test.
- Deactivate My "read more tag" plugin and remove the  `<p class="excerpt">{{ post.content_html|untilMore('post'|page({'slug': post.slug})) `}}</p>` 
in post page
changed the 3 files i.e. Post.php, default.htm (and README.md)
- In my single blog Post item set the `<!--more READ `MORE`-->`
Result: same as first test
Setting back the 3 files to the original "official" blogpost plugin Version files: non-readable 5 lines of text  in blog Posts list.
The Problem seems to be in Post.php
Is there anything I did wrong?

**Comment by daftspunk** [comment]
You'll need to contact the plugin author to get support with the Read More Tag plugin.
