### ISSUE TITLE
[Question] Applying CSS to individual elements

### ISSUE THREAD

**Issue by ElliotWilde** [rainlab/blog-plugin#264]
Hello, 

I'm new and still learning OctoberCMS but I'm struggling to understand how to apply CSS to specific elements of a 'post' in the 'post list' and 'post' pages. 

Using {% component 'blogPosts' %} it automatically pulls:
-  Title
-  Post date
-  Category
-  Post exerpt

However, I wish to be able to apply CSS individually to each of those elements.

Apologies if this is covered in documentation and I've simply misread.

**Comment by mjdwebdesign** [comment]
Hi Elliot,

I've just provided an answer here **https://github.com/rainlab/blog-plugin/issues/275** which is similar to the situation you explain.

The method I talk about uses partials to override plugin components, allowing you to implement your own elements within the component's code.

Here's the overriding partials documentation: http://octobercms.com/docs/cms/components#overriding-partials

**_- mjdwebdesign_**

**Comment by LukeTowers** [comment]
@mjdwebdesign is correct, either utilize your own custom overriding partials within your theme or target the default generated elements via your theme's CSS.
