### ISSUE TITLE
URL of the posts not set on the blogposts component

### ISSUE THREAD

**Issue by elroyK** [rainlab/blog-plugin#265]
Hi, I'm working on a non profit's website and we're using your blog plug-in to add publications to it. The problem is, when displayed on the `/publications` page, the posts title link to the same page instead of their specific post's page (`/publications/post/:slug`) despite having specified the page to the component inspector. Nonetheless, typing the correct link (e.g. `/publications/post/first-blog-post`) still redirects to the correct page, so I guess it's something to do with RainLab's interpretation ? I tried setting the link to a 404 or any other page, it stays as /publications.

I think it's kind of the same problem as #132 which had no answer yet.

Thanks for you answer :)

**Comment by tthoeye** [comment]
Same problem here. Any news?

**Comment by daftspunk** [comment]
Sounds like you may need to set the `postPage` property in the component? See the documentation for more details.

**Comment by elroyK** [comment]
It's been set since the beginning, even setting it to the 404 page doesn't work (as said in the original message)
Here is the page
```
<div id="news-content" class="section">
    <div class="container text-center">
        <h1>Publications</h1>
    </div>
    <div class="container">
        {% component 'publications' postPage='publication/:slug' %}
    </div>
</div>
```

I tried setting it as `{% component 'publications' %}` or `{% component 'publications' postPage='publication' %}`, nothing really works...

**Comment by LukeTowers** [comment]
@elroyK Please share the contents of your `publications` component

**Comment by LukeTowers** [comment]
@elroyK After looking at the code, the `post.url` property is set by passing the `postPage` property and various data about the post to the controller's `pageUrl($pageName, $params)` method. So, your `postPage` property must be the name of the page that you are displaying the `blogPost` component on, and it's url must be configured to accept at least a `:slug` route variable for the URL to the post to be generated correctly. 

Does that solve your problem? If not, please post the contents of your `publication` CMS page, where it is in the theme, and the configuration of your `publications` component.

**Comment by elroyK** [comment]
publication only has this line `{% component 'blogPost' %}`

The `publications` component is configured like so :

```
 ____________________________________________
| Alias            | publications            |
| Page number      | :page                   |
| Category filter  |                         |
| Posts per page   | 10                      |
| No posts message | No posts found          |
| Post order       | Published (descending)  |
|____________________________________________|
| Links                                      |
|____________________________________________|
| Category page    | blogcategory            |
| Post page        | publication/:slug       |
|____________________________________________|
```

I tried with `| Post page        | publication       |` but had no success

Was that what you wanted to see?

**Comment by elroyK** [comment]
Also here's the `blogPost` component's configuration on the `publication` page

```
 ______________________________
| Alias         | blogPost     |
| Post slug     | :slug        |
| Category page | blogcategory |
|______________________________|
```

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
