### ISSUE TITLE
Is it possible to target a single blog post list with the pagination?

### ISSUE THREAD

**Issue by mjdwebdesign** [rainlab/blog-plugin#267]
Hello again,
after fixing my original pagination issue I've now come across a secondary issue with my main blog feed.

The pagination is working as intended, no problems there. I'm simply wondering if a pagination can target a single blog post list when there are multiple blog post lists on the webpage.

The image below should be able to demonstrate my situation in more detail.

![news-layout](https://cloud.githubusercontent.com/assets/23475543/21115344/de60b3fc-c0a8-11e6-9ae7-c9ce9e96d675.jpg)

I have 3 different blog post lists situated on the page. The sidebar and footer feed are displayed on every page of the website, displaying the most recent posts. The sidebar displays a maximum of 3 posts and the footer feed displays 4. The pagination has been disabled on both of these feeds.

All 3 feeds have their own unique name and relate to their own seperate partials.

The pagination for the main feed is enabled however, when using the pagination it triggers all feeds to change.

Is it possible to ensure the pagination only changes the main blog posts feed?

**Comment by LukeTowers** [comment]
Just set the `pageNumber` property for the other components to 1 so that it stops using the default value of `:page` which will pull it from the URL.

**Comment by mjdwebdesign** [comment]
Thank you very much @LukeTowers for your response.
Of course, it makes complete sense to me now to do that. I'm surprised I didn't try that solution before.
Much appreciated!

**Comment by LukeTowers** [comment]
Not a problem, glad I could help!
