### ISSUE TITLE
Feature Request: "All Post From Category" static pages menu item

### ISSUE THREAD

**Issue by jajacobs** [rainlab/blog-plugin#270]
It would be nice to have a static pages menu item that displays links to all posts under a specified category.

**Comment by LukeTowers** [comment]
@jajacobs Why don't you just link to the category page?

**Comment by jajacobs** [comment]
I am trying to build a navigation menu with categories at level one and two. Deeper levels would be the posts.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
