### ISSUE TITLE
How to add target=_blank

### ISSUE THREAD

**Issue by quochuy** [rainlab/blog-plugin#274]
Hi

How can I make a link open a new tab?
Basically how do I add target="_blank"?
`[text](url){:target="_blank"}` does not work

thanks
Huy

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by groovejunkk** [comment]
Hi,

I searched the internet and your documentation, but I couldn't manage to open links in a blog post inside a new tab. Is adding html properties except ids and classes implemented?
I would give it a try myself if this is not yet supported.

All the best, 
Simon

**Comment by groovejunkk** [comment]
I just grepped a little bit back and forth through a fresh october instance and found, that emmet.js seems to be responsible for the feature I am looking for. I am just guessing, but might it be, that for the 
[This](http://google.de){#id.class} feature adding id or class to an html element, you rely on emmet.js?
For me adding aditional html properties would belong there. I will investigate further.

**Comment by bennothommo** [comment]
@quochuy @groovejunkk The Markdown parser in use does not support specifying attributes like `target`, only IDs and classes. If you want to insert links with a particular `target` attribute, you can either use a raw `<a>` HTML tag, or specify a class in Markdown and use JavaScript to modify the target attribute on-the-fly.
