### ISSUE TITLE
How can I add a second BlogList...

### ISSUE THREAD

**Issue by leannephillipz** [rainlab/blog-plugin#275]
I need two types of styling for blog list.

1. A main blog list page
2. A quick (title only) list to display on a homepage.

Does any one have any simple solutions to this?

I've tried adding a second "list" componant 

'RainLab\Blog\Components\List'      => 'bloglist',
and other files, but I just can't get it working.

I need to apply different styles and different content so I can't use the same "blogPosts" componant.

Has anyone got any suggestions for a way round this? I thought about using a partial, but I can't get that working either.

Any suggestions would really help.

Many thanks

**Comment by mjdwebdesign** [comment]
Hi Leanne,

I wouldn't recommend going into the source code and changing things there. Although this might potentially fix the issue, there's likely to be further issues when updating the plugin in the future. I had an issue with the plugin's pagination. Coming to this GitHub page for assistance I was instructed to override the blog posts using partials.

You can use the same "blogPosts" component across different pages, even within the same page. I'll do my best to explain how I went about doing this.

Overriding partials documentation: http://octobercms.com/docs/cms/components#overriding-partials

I have a similar setup to yourself, requiring multiple instances of the "blogPosts" across the website. Mine are located on the website's landing page, sidebar, footer and of course, "News" page.

# 1. Setup your blog component correctly

![image](https://cloud.githubusercontent.com/assets/23475543/22462315/b2e7f9c4-e7a4-11e6-8065-45446adc83ea.png)

^ this is the main blog post. I've renamed it's alias to "newsFeed". You'll also need to change this alias within the markup, like so:

![image](https://cloud.githubusercontent.com/assets/23475543/22462387/ff94f7ea-e7a4-11e6-8b10-d32b269cd156.png)

Do the same for any other blog posts you've added across your website. In the case of your situation, here's how I have the landing page blog post list setup:

![image](https://cloud.githubusercontent.com/assets/23475543/22462510/779209ae-e7a5-11e6-8732-875218f1943c.png)

I've renamed the alias of this blog post to "recentNews" and done the same for the alias within the markup.

![image](https://cloud.githubusercontent.com/assets/23475543/22462546/a2de40f0-e7a5-11e6-9fe2-096f177f9e87.png)

# 2. Preparing a partial directory

Now that you have renamed the components, you can create some new partial directories, of which the path will match that of the alias you named the components.

![image](https://cloud.githubusercontent.com/assets/23475543/22462705/5511939e-e7a6-11e6-881b-8350f03f4899.png)

As you can see, I've created new folders for each of my blog posts located at:
_/themes/**your-theme**/partials/_

_/themes/**your-theme**/partials/recentNews_ relates to the blog post located on the landing page of the website.

Inside each directory is "default.htm" which will contain the code to override the blog component.
**You'll have to create a new folder within Windows explorer / the FTP you use. You can't add a new directory through the partials interface.**

#  3. The code

Locate _/new/plugins/rainlab/blog/components/posts/default.htm_

Copy and paste this code into the default.htm located within the new directories you've made.
Or, just copy and paste the default.htm straight into the new directory.

If all goes well and my explanation isn't complete sh*t, the new "default.htm" you've created inside the new directories should override the relevant blog component.

Fingers crossed!

If you continue having issues let me know, I'll see how I can help further.

**_- mjdwebdesign._**

**Comment by leannephillipz** [comment]
Hey mjdwebdesign!

Thanks so much for your help, I really appreciate the time you've taken to point me in the right direction! It worked!

Warm Wishes,
Leanne

**Comment by mjdwebdesign** [comment]
Phew @leannephillipz, great news!

I'm relieved to know my explanation worked out alright.
It's only right I give back to October CMS and its community.

Warm wished to you also,

- **_mjdwebdesign_**
