### ISSUE TITLE
User permission to manage/edit blog posts/categories

### ISSUE THREAD

**Issue by mlukaszewski** [rainlab/blog-plugin#28]
I cannot set user/group permission to give this u/g access to blog plugin and blog plugin only.
Or I don't know smth? :)

**Comment by SaifurRahmanMohsin** [comment]
+1
Also, it would be nice to have a author field to tag the content creator from the list of available users

**Comment by LukeTowers** [comment]
This was added in https://github.com/rainlab/blog-plugin/pull/40
