### ISSUE TITLE
How to change the author? [question]

### ISSUE THREAD

**Issue by rodrigogoncalves** [rainlab/blog-plugin#281]
I've created users in Rainlab.User plugin and expected them to be available as possible post authors in the Manage tab on blog post edit page. How can I change authors of posts?

Thanks

**Comment by kealsera** [comment]
+1

**Comment by kealsera** [comment]
bump

**Comment by LukeTowers** [comment]
Post authors are Backend Users, not RainLab.User users. There is currently no interface implemented for changing the author of a post after it's been posted. It shouldn't be difficult to extend the plugin with your own plugin to add that feature though

**Comment by jan-vince** [comment]
I wanted to try this, so I have added option to change post author into my [Small Extensions plugin](https://octobercms.com/plugin/janvince-smallextensions).

You can look into my code and copy/fork it if you want. Not the best implementation for sure, but it works :)

*And if you need to make a connection to Rainlab.Users records, it would be very simillar approach.*

**Comment by jan-vince** [comment]
Strange as I need this on my current project :)

I will add this (tomorrow I hope) and let you know...

**Comment by jan-vince** [comment]
Hi @qroft 

I had no time to add this yet but keep it in my todo list and will look at it asap!

**Comment by qroft** [comment]
Friendly bump. Hugs and greetings from this corner of the planet!

**Comment by LukeTowers** [comment]
@qroft log an issue here instead: https://github.com/jan-vince/smallextensions/issues

**Comment by jan-vince** [comment]
Hi @qroft, I have just added this function - it is in 1.8.0 version :)
