### ISSUE TITLE
Steps needed to set permanent url for posts like /:category/:slug

### ISSUE THREAD

**Issue by rodrigogoncalves** [rainlab/blog-plugin#282]
When migrating a blog previously running WordPress to October + Rain Lab Blog, a URL structure (called "permalink" in WP's lingo) like `/[category]/[slug]` can be preserved by specifying `/:category/:slug` as the URL in the page template that has `{% component 'blogPost' %}`.

I don't know if there is a place for this kind of tip in the docs. Some people might find it useful. Perhaps this could go to a section describing general steps to migrate from other popular blog/cms engines.

**Comment by Rmfordev** [comment]
@rodrigogoncalves Hello! There are solutions?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
