### ISSUE TITLE
Multiple post lists on one page

### ISSUE THREAD

**Issue by petermezes** [rainlab/blog-plugin#287]
Hi. 
Im building a simple magazine and on the home page I made overview of posts/articles in my few categories. I have three categories. I wanted to have hero section with latest article. Then three sections, each includes 4 latest posts from specific directory. If I run them separately, all is good, but when I run them all together, looks like variable `posts` is holding all the data. Each `posts` has 4 posts as wanted, but same content. Its like overwritten by the last post list component call. 

This is the homepage code: 
```
title = "Úvod"
url = "/"
layout = "main"
is_hidden = 0

[blogPosts blogPostsHomeLatest]
pageNumber = "{{ :page }}"
postsPerPage = 1
noPostsMessage = "No posts found"
sortOrder = "published_at desc"
categoryPage = "kategoria"
postPage = "clanok"

[blogPosts blogPostsHomeRecenzie]
pageNumber = "{{ :page }}"
categoryFilter = "{{ recenzie }}"
postsPerPage = 4
noPostsMessage = "No posts found"
sortOrder = "published_at desc"
categoryPage = "kategoria"
postPage = "clanok"

[blogPosts blogPostsHomeRozhovory]
pageNumber = "{{ :page }}"
categoryFilter = "{{ rozhovory }}"
postsPerPage = 4
noPostsMessage = "No posts found"
sortOrder = "published_at desc"
categoryPage = "kategoria"
postPage = "clanok"

[blogPosts blogPostsHomeZaujimavosti]
pageNumber = "{{ :page }}"
categoryFilter = "{{ zaujimavosti }}"
postsPerPage = 4
noPostsMessage = "No posts found"
sortOrder = "published_at desc"
categoryPage = "kategoria"
postPage = "clanok"
==


<div id="homePage">
    {% component 'blogPostsHomeLatest' %}
    <hr>
    {% component 'blogPostsHomeRecenzie' %}
    <hr>
    {% component 'blogPostsHomeRozhovory' %}
    <hr>
    {% component 'blogPostsHomeZaujimavosti' %}
</div>
```

I was searching if there is anyway to rename `posts` for each call to hold its data and wont be overwritten, but I didnt find anything. Is there any way then, how to display multiple post lists on one page? 

Thank you!

**Comment by LukeTowers** [comment]
You would access the posts member variable of each component through the component alias.

I.e.
```twig
{% for post in blogPostsHomeZaujimavosti.posts %}
    {# blogPostsHomeZaujimavosti posts will be looped through here #}
{% endfor %}
```

**Comment by petermezes** [comment]
Ah, I believed it was something simple! 
Thank you for your help.

**Comment by LukeTowers** [comment]
No problem, you'll probably find faster help on the IRC channel, Slack, or the forums in the future though :)
