### ISSUE TITLE
Add category image!

### ISSUE THREAD

**Issue by ribsousa** [rainlab/blog-plugin#289]
Could add a field to upload an image to category? I think it could be great.

**Comment by LukeTowers** [comment]
@ribsousa You could do that through a plugin, just extend the Category model to add a relationship to a system file, and then extend the Categories controller to add the fields necessary to choose that image.

**Comment by ribsousa** [comment]
Ok! thanks

**Comment by junshenshi** [comment]
@ribsousa 
Hi
请问您那个图片插件怎么能使用多语言？
How can your image plug-in use multiple languages?

**Comment by ribsousa** [comment]
Hello, inside the lang folder you can add your language and october will translate altomatically.
You can add a pull request in [github](https://github.com/ribsousa/featured-images), which I do the plugin update to add your language.
