### ISSUE TITLE
File attachments change affects the featured_images object

### ISSUE THREAD

**Issue by stephenkeable** [rainlab/blog-plugin#291]
I've noticed this change over the develop branch of the october core:-

https://github.com/octobercms/october/commit/5aa351f67c0f9b4d7b1b5c5cb6c2199d19164c79

Causes problems with the featured_images object when using the path property with the media filter, causing an exception to be thrown about invalid path. As a full URL is returned by the code below instead of a path.

`post.featured_images.first.path`

So this throws an exception `post.featured_images.first.path|media`

**Comment by LukeTowers** [comment]
@daftspunk Is this something that breaks backwards compatibility in a significant way?

**Comment by stephenkeable** [comment]
Possibly, we use S3 to store all of our blog image so they don't exist on the local storage URL which is now generated by the path prop of images with the featured_images object.
The closest thing to a fix was to use this in a template file:- 
`post.featured_images.first.path|replace([domain] : [cdn_domain])`
Which just feels rather hacky compared to the media filter.

**Comment by LukeTowers** [comment]
@stephenkeable So this change is something that actively broke your projects?

**Comment by stephenkeable** [comment]
Yes the blog pages of our website started throwing exceptions.
We switched from the develop branch of october to the master to prevent this happening in production.

**Comment by LukeTowers** [comment]
Thanks for the report! Things like this is why we have the `develop` vs `master` branches :)

**Comment by daftspunk** [comment]
Hey @stephenkeable Thanks for testing the pre-release code and sorry for any frustration this may be causing. I think there might be some confusion here around the pathing. The `|media` filter is designed to convert a relative path, uploaded via the media manager, to a fully qualified path. It isn't intended to be used for file uploads.

Can you try something for me, crack open your **cms.php** config file (under /config) and update the following option:

```
    'storage' => [

        'uploads' => [
            // ...
            'path'   => 'http://cdn.hostname.tld/storage/app/uploads',
        ],
        // ...
    ],
```

The `storage.uploads.path` should contain the full URL path to your CDN location. Then update your markup to read simply:

```
{{  post.featured_images.first.path }}
```

Let me know how you go with this.

**Comment by stephenkeable** [comment]
@daftspunk that's fine, no worries either. Will try it out on Monday and let you know.

**Comment by stephenkeable** [comment]
Gave it a go and specifying a full URL instead of relative path in the cms.php config file worked (after removing the |media filter from template files too) switched to the dev branch and can confirm working there too.
Thanks for your help with this.

**Comment by LukeTowers** [comment]
Good to hear that your issue is solved now!

**Comment by LukeTowers** [comment]
A [release note](http://octobercms.com/support/article/rn-7) has been created to document this.
