### ISSUE TITLE
Use mediafinder for feature_images

### ISSUE THREAD

**Issue by justb81** [rainlab/blog-plugin#301]
My editors asked me the other day to change the Featured Image-Upload to use the mediafinder dialog. i tried to do it myself and it worked seamlessly.

My i start a PR for that change?

**Comment by LukeTowers** [comment]
It's something that I do personally (along with switch the markdown editor to a richeditor), but I don't think @daftspunk will accept it as it would be a breaking change. If you'd like, you could create a plugin to do it for people though. If not, I'll probably get around to doing that at some point myself.
