### ISSUE TITLE
Image stop working in home blog and category after last upgrade

### ISSUE THREAD

**Issue by willouch** [rainlab/blog-plugin#302]
Hi,

My mage stop working in home blog and category after last upgrade of BLOG plugin....

thks

**Comment by LukeTowers** [comment]
Is this the same issue as mentioned here: https://github.com/rainlab/blog-plugin/issues/291?

**Comment by willouch** [comment]
Sorry, this is not exactly like this, all HTML tag replace like this
`<p><img src="/storage/app/media/citron-mauvais-email-dents.png" alt="" /></p> <h3>Boire un jus de citron chaque matin est bon pour la santé.</h3> <p>L’inconvénient, c’est qu’il y a un risque très important pour les dents. </p> <p>Il est relativement facile d’évitez ce risque en adoptant quelques mesures de protection.</p>`

**Comment by LukeTowers** [comment]
Do you have a URL where I can see the issue happening?

**Comment by willouch** [comment]
https://www.jpsalama.fr/blog

1000000 thks

**Comment by LukeTowers** [comment]
Do you know what version of the blog you were using before you upgraded?

It looks like the problem could be resolved by adding the `| raw` filter to your Twig, but I don't know how your site is setup, I'd have to see your blog.htm page's code to understand more about how your site is setup.

**Comment by willouch** [comment]
Perfect solution! Thks @!!!

I'm neewbie with october... so maybe i have try without | raw and don't verify or take a phonecall at this moment...

I think that upgrade way is 1.2.13(not sure) to 1.2.14 to 1.2.15 to 1.2.16 this is a recent install.

Have a good day and good work!!!!!

P.S: thanks for your time.

**Comment by LukeTowers** [comment]
Happy to help :)
