### ISSUE TITLE
Get post featured image from media manager? (question)

### ISSUE THREAD

**Issue by mjdwebdesign** [rainlab/blog-plugin#304]
Hi,

As seen from the title, I'd like to request the ability to pull featured images from the media manager.

I'm aware this has been requested a few times but personally, I fail to understand why this feature hasn't been implemented yet? 

[https://github.com/rainlab/blog-plugin/issues/204](https://github.com/rainlab/blog-plugin/issues/204)

^ an issue opened last year.
There's evidently significant demand for this feature.

From my point of view, I can only see benefits coming from such a feature.
File and folder management would improve for a start.
I mean, just looking through the current "uploads" folder/file structure - it's a mess...

I'm also aware that I could extend the plugin but personally, I'm new to OctoberCMS, PHP and MySQL so I'm not comfortable with doing such a thing without a significantly detailed guide.

With the evident interest in this feature, I don't see why this shouldn't get developer attention. In the form of a plugin update or even a written guide / video covering how to extend this plugin specifically and implement the ability of fetching featured images from the media manager.

If there are specific reasons as to why this won't or can't be implemented, please enlighten me as I can't understand it myself.

Thanks,
Matt.

**Comment by jan-vince** [comment]
Hey, I had same need on one of my project, but I have solved this with a private plugin.

I have added this now to my [Small Extensions plugin](https://octobercms.com/plugin/janvince-smallextensions) in form of an extra image field.

When you allow this image field in Settings > Small Extensions, you will see new image field in blog post editing form (on tab More). It will link Media manager image to blog post.

Hope this will help you.

*Feel free to use my plugin or grab the plugin's code to create your own.*

**Comment by mjdwebdesign** [comment]
Hi Jan-vince,

Appreciate the reply.

It would be extremely beneficial to have this feature.
It's a shame the blog plugin doesn't have this feature by default.

I'll look at implementing this into my project to see if I can get the desired effect.

If I come across any issues or I fail to achieve the desired effect, I'll get in touch via the plugin's support.

Thanks again,
Matt.

**Comment by LukeTowers** [comment]
Closing this as it can be implemented by thirdparty plugins and isn't likely to be changed in the blog plugin itself.
