### ISSUE TITLE
403 Error "You dont have permission to access /backend/rainlab/blog/post/3

### ISSUE THREAD

**Issue by JREAM** [rainlab/blog-plugin#305]
I looked through the issues and had not seen any of these, my apologies if I missed it.
Appears that the Markdown preview is the issue possibly.

- Everything Saves Correctly, Everything works flawlessly, yet the Markdown Preview stops working after that popup in about 10 seconds.

- Using SSL/HTTP 2.0
- ACL also set to: `myself:www-data` with `ug+rw`

I am using my user with group permissions `user:www-data` 

```
sudo usermod -aG www-data myuser
chgrp -R www-data /var/www/october-path/
sudo chmod -R g+rws /var/www/october-path/
```

Anything you see wrong here? :+1: 

![err-oct](https://cloud.githubusercontent.com/assets/145959/25108611/0181b3cc-23a5-11e7-8dc0-634200a6a388.png)

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
