### ISSUE TITLE
Question - how to dynamically change post list category filter?

### ISSUE THREAD

**Issue by prema770** [rainlab/blog-plugin#308]
Can anyone please help with some tips on how to change a front page post list category on the fly - by clicking a selection button?
Thanks for any help

**Comment by kevinvermeulenn** [comment]
Hi @prema770 ,
Did you already have a solution for this? I've the same idea as you.  
Would be great if you have it already.

**Comment by LukeTowers** [comment]
@kevinvermeulenn based on your comment in #194 and here, I suggest you look into using the [AJAX framework](http://octobercms.com/docs/ajax/introduction).

**Comment by prema770** [comment]
Kevin! Nothing yet but will post back when we have the chance to take another look. Good luck meantime

**Comment by kevinvermeulenn** [comment]
@LukeTowers Could you help me with an example? 
I've never done this before..

**Comment by LukeTowers** [comment]
Try asking for help on the IRC channel or Slack @kevinvermeulenn

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
