### ISSUE TITLE
SQLSTATE Column not found

### ISSUE THREAD

**Issue by Michael-Reich** [rainlab/blog-plugin#311]
I installed it through the backend and reinstalled it several times with the CLI. Also performed php artisan october:up and plugin:refresh nothing worked for me.

Still get this error:
```
"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'seo_title' in 'field list' (SQL: update `rainlab_blog_posts` set `content` = This is your first ever **blog post**! It might be a good idea to update this post with some more relevant content.

You can edit this content by selecting **Blog** from the administration back-end menu.

*Enjoy the good times!*, `updated_at` = 2017-05-15 18:31:53, `seo_title` = , `seo_description` = , `seo_keywords` = , `canonical_url` = , `redirect_url` = , `robot_index` = index, `robot_follow` = follow where `id` = 1)" on line 666 of /xxx/vendor/laravel/framework/src/Illuminate/Database/Connection.php
```

**Comment by LukeTowers** [comment]
What other plugins do you have installed? `seo_title` isn't something that comes with the Blog plugin by default?

**Comment by Michael-Reich** [comment]
https://octobercms.com/plugin/anandpatel-seoextension
https://octobercms.com/plugin/martin-forms

This two

**Comment by LukeTowers** [comment]
Uninstall the SEO extension plugin, then install the blog plugin, and then re-install the seoexception plugin. That plugin doesn't properly handle the blog plugin being present but not yet initialized, so that's the problem.
