### ISSUE TITLE
Posts need an expiration date option

### ISSUE THREAD

**Issue by InquisitiveDevelopment** [rainlab/blog-plugin#312]
Posts have their required publish date. They **definitely** need an option to expire as well!

**Comment by pvullioud** [comment]
This could be also added by an external plugin.

**Comment by LukeTowers** [comment]
I would agree with @pvullioud, it wouldn't be that hard to put it in the main plugin or an external plugin, but I would lean towards an external plugin unless we get lots of feedback from users requesting this feature.

**Comment by gravataLonga** [comment]
:+1:

**Comment by WWRFresource** [comment]
I have been working on a "archive" system for my blog based on this very idea. The posts I make to my application are only relevant for 30-60 days. So, what I did was add an "unpublish" button the the Posts index. 

_list_toolbar.htm:
`    <button
        class="btn btn-default oc-icon-minus-square-o"
        disabled="disabled"
        onclick="$(this).data('request-data', {
            checked: $('.control-list').listWidget('getChecked')
        })"
        data-request="onUnpublish"
        data-request-confirm="<?= e(trans('rainlab.blog::lang.blog.delete_confirm')) ?>"
        data-trigger-action="enable"
        data-trigger=".control-list input[type=checkbox]"
        data-trigger-condition="checked"
        data-request-success="$(this).prop('disabled', true)"
        data-stripe-load-indicator>
        Unpublish selected
    </button>`

and Posts controller:
`    public function index_onUnpublish()
    {
        if (($checkedIds = post('checked')) && is_array($checkedIds) && count($checkedIds)) {

            foreach ($checkedIds as $postId) {
                if ((!$post = Post::find($postId)) || !$post->canEdit($this->user)) {
                    continue;
                }

                $post->update(['published' => 0]);
            }

            Flash::success('Successfully unpublihsed selected posts.');
        }

        return $this->listRefresh();
    }`

Now, I have to manually select posts to unpublish, obviously. I then modified the blog archive by @graker to look for unpublished posts.

I know this is probably not the cleanest way to do something like this, but I needed something fast and it's what I was able to come up with. 

I would certainly like to see something baked into the blog or extended-I'm just not sure how to extend forms like that. Or possibly even have a global setting that expires/archives posts after X amount of time.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
