### ISSUE TITLE
Missing Accent - WYSIWYG  

### ISSUE THREAD

**Issue by gravataLonga** [rainlab/blog-plugin#313]
##### Expected behavior
When i write "´" + "e" = "é"  

##### Actual behavior
The result is "´é"  

##### Reproduce steps
Backend > Post > New Post > Write a body  

##### October build
419 Build  

Here go a video:

[Video](https://youtu.be/xnlH7Mi1n_o)

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
