### ISSUE TITLE
Blog pagination throws error on very big numbers

### ISSUE THREAD

**Issue by graker** [rainlab/blog-plugin#315]
Hi

It seems that `paginate()` call [here](https://github.com/rainlab/blog-plugin/blob/master/models/Post.php#L287) is throwing errors when big (> MAX_INT) number is passed as a page number. And it appears that if we pass page parameter to Posts component, the only option we have to validate it is to use regex in page url to ensure it only consists of digits. And nowhere on the way this parameter is limited to max integer. So when it comes to pagination in database query, it throws this:

```
exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-532867040407453696' at line 1' in /vendor/laravel/framework/src/Illuminate/Database/Connection.php:319
```

Maybe it is a more general bug in October or Laravel, or it is the intention of pagination code authors to make users validate page number more thoroughly. Anyway I think something needs to be done with it.

**Comment by daftspunk** [comment]
This exists at the framework level, probably shouldn't be logged in the blog plugin. Check to see it hasn't yet been addressed at laravel/framework already.

**Comment by graker** [comment]
I found an issue https://github.com/laravel/framework/issues/17471 it seems that it hasn't been addressed yet.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
