### ISSUE TITLE
Unpublished Posts are present in the sitemap

### ISSUE THREAD

**Issue by pvullioud** [rainlab/blog-plugin#317]
Combined with https://github.com/rainlab/sitemap-plugin
the site map return all the posts include the unpublished one.

# To reproduce the issue
- create a post in the blog without published it
- load the sitemap : https://inetis.ch/sitemap.xml
- unpublished article is present

**Comment by pvullioud** [comment]
sorry duplicate with #272

**Comment by LukeTowers** [comment]
Duplicate of https://github.com/rainlab/sitemap-plugin/issues/45
