### ISSUE TITLE
Image is too big into the post content

### ISSUE THREAD

**Issue by LucasAbella29** [rainlab/blog-plugin#319]
I been doing some testing into the **blog-plugin** and when i make a post with an image into it, the image just appears in full size and it goes out of bounds. Is there a solution to that? (discarding the fact that i can resize the image, which is not what a i want).

**Comment by LukeTowers** [comment]
Are you talking about the image being too large in the backend or the frontend?

**Comment by LucasAbella29** [comment]
I'm sorry! I was talking about the frontend, because in the backend the visuals are good. In the frontend the image width goes out of bounds. If i set the heigth and width attributes to "100%" on navigator's console, it looks good.

**Comment by LukeTowers** [comment]
That's a problem for your theme to handle, not much this plugin can do about that. I'm available for freelance work though if you want me to take a look at it for you.
