### ISSUE TITLE
Table Not Found Error on Installation

### ISSUE THREAD

**Issue by epaprat** [rainlab/blog-plugin#320]
I am getting this error on installation. 

![screen shot 2017-06-09 at 11 37 24](https://user-images.githubusercontent.com/193685/26967743-1135e93c-4d08-11e7-975f-2c81848dc221.png)

![screen shot 2017-06-09 at 11 38 22](https://user-images.githubusercontent.com/193685/26967781-32783528-4d08-11e7-86c0-f0165a4c0fab.png)

**Comment by dustinblad** [comment]
I am getting a similar error. Are you using PostgreSQL?
#332

**Comment by LukeTowers** [comment]
What other plugins do you have installed @epaprat?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
