### ISSUE TITLE
How can I get featured image link for each post?

### ISSUE THREAD

**Issue by ahmcho** [rainlab/blog-plugin#323]
I know that I can iterate between all featured images by using `{{ post.featured_images }}` . I want to add them to my newsletter script, under title of the each post, when I'm sending them via mail() function in `Code` section. Is there a way to get the link for first image without Twig?

**Comment by jan-vince** [comment]
Have you tried ````$post->featured_images->first()````?

In a way like this:

````php
$posts = Post::all();

    foreach( $posts as $post) {

        dump( $post->featured_images->first() );

   }
````

**Comment by ahmcho** [comment]
Thanks! It partially solved the case, i just edited it a little bit, to get filepaths of each first image 
: `$post->featured_images[0]->first()->getpath();`

**Comment by jan-vince** [comment]
Why do you use ````featured_images[0]````?

Accessing objects this way means you have to check that the key exists otherwise you get exception - am I right?

This should do the same ````$post->featured_images->first()->getpath()```` and you receive NULL if no images are attached.

Or am I missing something?

**Comment by ahmcho** [comment]
My bad, after couple of hours, came to conclusion that it was unnecessary. `first()->getpath()` works just fine.
