### ISSUE TITLE
lack of permission for managing media not handled properly 

### ISSUE THREAD

**Issue by mjauvin** [rainlab/blog-plugin#325]
When clicking on the "insert media link/image" when editing/creating a Blog Post, I get the following error when the admin user does not have the "upload and manage media contents" permission:

"A widget with class name 'ocmediamanager' has not been bound to the controller" on line 523 of /home/jauvicba/wp.jauvin.com/modules/backend/classes/Controller.php

When dismissing the Error popup, the application is stuck there until I force a page reload.

**Comment by vanmil** [comment]
Think this is a general octobercms bug (probably edge update / version 420+) as I also experienced the same bug with the static pages plugin in combination with a mediafinder field.

**Comment by LukeTowers** [comment]
This should be integrated with https://github.com/octobercms/october/pull/2937 by adding a permission check to the EditorSetting model to modify the default buttons that are added to remove the mediamanager button if the user doesn't have permission.

**Comment by Harti** [comment]
[This is the file](https://github.com/octobercms/october/blob/4074ad8cc9c20a3196f058e908d98c5efca9ad1b/modules/backend/formwidgets/richeditor/partials/_richeditor.htm) where the fix should be implemented, in my opinion. It probably also affects the `$toolbarButtons`, not just the `$globalToolbarButtons`.

I cannot find the internal permission name for uploading/managing media contents [in the API docs](https://octobercms.com/docs/api). ☹️

**Comment by LukeTowers** [comment]
I suggested the global default instead of filtering it right on the RichEditor form widget because if someone has gone to the trouble of manually specifying the media button on their toolbar, I don't think it's our place to remove it automatically from that manual specification without the user knowing what happened.

The permission you are looking for is all-encompassing, it's called `media.manage_media` @Harti

**Comment by Harti** [comment]
https://gist.github.com/Harti/d8a426ef395f2e25b9e7b12cc4c1ef62

This is what I would be suggesting. **I was unable to test it** because my local installation of OctoberCMS build 419 _does not have the global toolbar setting yet, was unable to find updates and force installing updates does not upgrade the build_. Updating via Composer hangs on resolving dependencies through SAT. It is driving me insane.

**Comment by LukeTowers** [comment]
@Harti enable edgeUpdates in your config/cms.php. Also there's a different caching provider that you can get composer to use that improves the speed.

**Comment by Harti** [comment]
Thanks @LukeTowers, I was able to test my changes locally and opted for `str_replace`.

**Comment by php-bob** [comment]
I get a similar message when using the static pages plugin and the back end user does not have a role with Upload and manage media contents.  Found this post by googling the error message (simlar as mjauvin but on line 550), so I can understand if this is not the correct location for this comment.

![image](https://user-images.githubusercontent.com/17052981/50790856-b2ba1280-1285-11e9-8b5c-005a33968163.png)

1. Make sure you have the Static Pages plugin installed and a user with a role with the pages permissions
![image](https://user-images.githubusercontent.com/17052981/50791097-68856100-1286-11e9-9cc0-234889623b1a.png)
2. Login as the user.
3. Create a new static page or edit an existing static page.
4. Click the  Insert image button and then the browser button.
![image](https://user-images.githubusercontent.com/17052981/50791237-dd589b00-1286-11e9-9a55-4de8e99e5228.png)
5. Receive the error message and click OK.
6. Infinite loading gif until you refresh.
![image](https://user-images.githubusercontent.com/17052981/50791293-0b3ddf80-1287-11e9-848e-ae8a00520fdb.png)
![image](https://user-images.githubusercontent.com/17052981/50791420-68399580-1287-11e9-8425-3ed6d7d43148.png)

I can provide the stack trace from the event log if needed.
Thanks,

**Comment by LukeTowers** [comment]
@vanmil @Harti @php-bob Please test octobercms/october#4305 and then we can merge it in

**Comment by mjauvin** [comment]
Resolved by https://github.com/octobercms/october/pull/4305
