### ISSUE TITLE
Backward compatibility, new branch/tag.

### ISSUE THREAD

**Issue by tskorupka** [rainlab/blog-plugin#331]
With this [commit](https://github.com/rainlab/blog-plugin/commit/b48153200fb7d0deaad25dcc7a432d9b50ef84d4) we should create new branch/tag, because some users who use php with 5.6.* should have backward compatibility.

It would be good to support php 5.6.* and also 7.*, it's hard to stick to exact commit.

**Comment by daftspunk** [comment]
Good call, created `build419` branch for this.
