### ISSUE TITLE
Undefined Table

### ISSUE THREAD

**Issue by dustinblad** [rainlab/blog-plugin#332]
I'm receiving this error while trying to install the blog. v1.2.16. I am using PostgreSQL as my database backend. Any ideas are appreciated.
![error](https://user-images.githubusercontent.com/6413392/28630185-d0c5f096-71e6-11e7-9ec9-c3eec13f12d5.PNG)

**Comment by LukeTowers** [comment]
This is a result of a third party plugin that's trying to modify the blog plugin's database tables before they actually exist. See the `seo_title` column that the migration is trying to add; my guess is you have a SEO plugin that's causing this issue. Disable it and then finish installing the blog plugin.
