### ISSUE TITLE
Post preview link in _post_toolbar.htm?

### ISSUE THREAD

**Issue by WWRFresource** [rainlab/blog-plugin#333]
I found this code in the posts controller files but it does not seem to be showing when I'm updating posts. I would really like my backend user to be able to preview the post on the frontend. Tried searching for similar issues but did not find anything.

`    
    <a
        href="<?= URL::to($pageUrl) ?>"
        target="_blank"
        class="btn btn-primary oc-icon-crosshairs <?php if (!false): ?>hide<?php endif ?>"
        data-control="preview-button">
            <?= e(trans('backend::lang.form.preview_title')) ?>
    </a>
`

**Comment by LukeTowers** [comment]
You can't preview a post if it doesn't exist yet

**Comment by WWRFresource** [comment]
I get that-even if I have saved the post the preview link is not visible.

**Comment by LukeTowers** [comment]
Do you have a page setup to display posts with the Post component added?

**Comment by WWRFresource** [comment]
Yes on the front end I have everything setup and working fine.

**Comment by LukeTowers** [comment]
If you open your developer console on your browser do you see any errors?

**Comment by WWRFresource** [comment]
I'm not showing anything in the developer console for front end post page or backend post update.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
