### ISSUE TITLE
Post cannot be rendered outside {% component %} block

### ISSUE THREAD

**Issue by jan-vince** [rainlab/blog-plugin#335]
After #324 I cannot render blogPost outside of ````{% component 'blogPost' %}```` block because only using ````{% component %}```` calls ````onRender()```` method.

But this means that component's markup cannot be customized as [mentioned in docs](https://octobercms.com/docs/cms/components#customizing-default-markup) so we cannot render blog post manually in page or partial.

**Is this a BC?** Many of us are probably using partials/pages for manual rendering.

Can please anyone confirm this ( @LukeTowers , @daftspunk ) ?

----
I believe the original intention @Harti wanted to solve was to get a post when a slug is empty.

But this can be easily done by iterating over blogPosts items and getting the post needed (or by doing this in PHP section).

*Fix #324 also introduced a problem with changing page title as in #326.*

**Comment by LukeTowers** [comment]
This will need to be changed, but I'm not sure the best way to go about it yet. I think it should be switched back to `onRun` but then we need to add support for it getting the `post` variable at the correct time.

**Comment by jan-vince** [comment]
@LukeTowers  I would vote for getting this back to ````onRun()```` as right now we have to issues against this.

*What benefit is in changing post slug in a middle of a page render?*

*If you have ````/blog/:slug?```` URL, no slug is provided and you still render one of your posts on this page, this leads to very poor SEO as the same content will be on e.g.. ````/blog/my-last-post```` page.*

**Comment by Harti** [comment]
@jan-vince I’m sorry my “fix” caused you issues. It’s due to a lack of experience with all the nodes and their connections in this framework. 
I’m not certain what _your_ use case is so I don’t fully understand the problem caused yet.

I’m not sure how bad the SEO penalty truly is, and I disagree with the adverb “easily” for being able to iterate posts manually. It’s going to be a lot more expensive calling the page due to the not-so-short algorithm required to achieve the result. Using the described iteration method I would also have to make sure the selection arguments (such as categories) match, making it a lot more prone to bugs than using the same variable.

My use case is I’ve got an overview of all blog posts in a sidebar and when I click an item, I get to see both the sidebar and the item’s content in the content section.
Displaying the latest post on said URL is for user convenience as I don’t think it’s great to display a “hey user, please select a news item on the left” message and I’ve no idea what one could display if not the latest post.

Feel free to suggest a solution that works for both worlds. I would if I could and I’m sorry if I’m coming across arrogant which I don’t mean to be.

**Comment by jan-vince** [comment]
Hi @Harti you are definitely not arogant in any way! 

We are just looking for a good solution here.

#### Blog post without URL

What I wanted to say about SEO is that if your user haven't selected a post yet and you still want to show a content of some of your posts, I believe you should pick one post and **redirect** to a page with correct slug.

If you don't you will end up with 2 very same pages with different URLs - and that is truly bad for SEO.

#### Your use case

If I understand right you have a sidebar with posts and you probably use ````blogPosts```` component.

So you can easily get the latest post with just ````{{ posts.first }}````.

You will have to manually render selected post - but it's not a problem as you can expand component markup from original ````blog```` post as [in documentation](https://octobercms.com/docs/cms/components#customizing-default-markup).

But with this fix it is not possible anymore.

So once you will need a different markup for your post (eg. title after excerpt) how do you handle it?

*I know about [component's partials overriding](https://octobercms.com/docs/cms/components#overriding-partials) but it seems to me as a heavy-handed approach.*

**Comment by Harti** [comment]
> So once you will need a different markup for your post (eg. title after excerpt) how do you handle it?

I used custom markup by adding `{theme-folder}/partials/blogPost.htm`:
```
<p class="info clearfix">
    <span class="date float-left"><i class="fa fa-calendar-o"></i> {{ post.published_at|date('d. F Y') }}</span>
    <span class="time float-right"><i class="fa fa-clock-o"></i> {{ post.published_at|date('H:i') }} Uhr</span>
</p>
<h1>{{ post.title|raw }}</h1>
<div class="content">{{ post.content_html|raw }}</div>
```

and using this from a page:

```
// ...

[blogPost]
slug = "{{ :slug }}"

[blogPost firstPost]
==
	{% component 'blogPost' %}
```

I don't know about any other ways to properly override the markup. 

Again, I'll have to pass in theorycrafting a proper solution as I'm an OctoberCMS rookie. In the end I don't care if I have to replace some of the code I used, I just need it to work the way it does. Redirecting sounds like a good idea in general but the overhead of fetching the correct post for the redirect is really large.

**Comment by jan-vince** [comment]
Hi @Harti thanks for your answer. I have some ideas here (and questions :) 

*This is longer but not more than 2 minutes of reading...*

## Partials overriding

As I wrote I know about [component's partial overriding](https://octobercms.com/docs/cms/components#overriding-partials) but the main problem here is that it is dependent on a component's alias.

If you use your component more than once - or you need another alias/name for it - you have to create this overriding partial for all of them in a subdirectories with alias's name - am I right?

*How do you render your ````[blogPost firstPost]```` when you have defined overriding partial only for ````[blogPost]```` ?*


## Overhead

Please, what do you mean by this? :
> ... but the overhead of fetching the correct post for the redirect is really large.

In your #324 code example you manually pass slug from the very first post from your ````blogPosts```` component like this:

````
{% component 'firstPost' slug=blogPosts.posts[0].slug %}
````

But when you think about it I believe you have unnecessary queries here:

* You list all posts in your sidebar from blogPosts component (first query)
* You get first post to pass a slug to ````firstPost```` component (second query if not cached)
* ````firstPost```` component has to search for this post as you deliver only a slug (third query)

But I believe this all can be done with just one SQL query:

*This is just an idea how to solve your use case:*

````
title = "Blog"
url = "/blog/:post?"
layout = "default"
is_hidden = 0

[blogPosts]
pageNumber = "{{ :page }}"
postsPerPage = 10
noPostsMessage = "No posts found"
sortOrder = "published_at desc"
categoryPage = "page"
postPage = "post"

[blogPost]
slug = "{{ :slug }}"
categoryPage = "blog"
==
{% set firstPost = null %}

<div class="sidebar">
    {% for post in blogPosts.posts %}
    
        {% if firstPost is empty %}
            {% set firstPost = post %}
        {% endif %}
        
        <h1 class="title">{{ post.title }} </h1>
        <div class="excerpt">{{ post.summary }}</div>
        
    {% endfor %}
</div>

<div class="post">
    <h1>{{ firstPost.title }}</h1>
    <div class="excerpt">{{ firstPost.summary }}
</div>
````

## Redirect

I don't want to force you to redirect when no slug is given - I know this is just a good practice but you are master of your code! :)

But I wanted to try how difficult is to write such code and this is what I ended with in PHP section of page:

````
...
title = "Blog"
url = "/blog/:slug?"
layout = "default"
is_hidden = 0
...
==
<?php
use \RainLab\Blog\Models\Post;

function onStart() {

    if( empty($this->param('slug') ) ) {
        $firstPost = Post::isPublished()->first();
        if( !empty($firstPost->slug) ) {
            return redirect( url('blog', [ 'slug' => $firstPost->slug ]) , 302 ); // moved temporarily as first post can change
        }
    }

}
==
...
````

Maybe this is a way how to solve your problem and satisfy SEO ?


## BC break

And now what to do with BC breaks your commit introduced? Maybe you have some ideas and we can find way how to solve them.

#### Changing title of a page

We need to allow page title change as it is [documented in official README.md](https://github.com/rainlab/blog-plugin#implementing-front-end-pages) file and many people is probably using this.

#### Allow component's partial overriding

This is also [documented function in official docs](https://octobercms.com/docs/cms/components#moving-default-markup) and we need to keep this functionality as many can used it before.


## Changing ````onRender()```` method?

How about another way of forcing slug to ````blogPost```` component like this:

```` php

/**
*  /plugins/rainlab/blog/components/Post.php
*/
...
    public function onRun()
    {
        $this->categoryPage = $this->page['categoryPage'] = $this->property('categoryPage');
        $this->post = $this->page['post'] = $this->loadPost();
    }

    public function onRender()
    {
        if( empty( $this->post and $this->propery('slug') ) ) {
            $this->post = $this->page['post'] = $this->loadPost();
        }
    }
````

Maybe @LukeTowers can add his opinion here. 

And @petehalverson, @jimcottrell and @vojtasvoboda as they wrote about this in #326.

**Comment by Harti** [comment]
> How do you render your [blogPost firstPost] when you have defined overriding partial only for [blogPost]?

Indeed I had to copy the respective partial's directory. It's not ideal.
My gut feeling tells me that your solutions are in general more viable than mine and (despite it not being my call anyway) would endorse to revert the change that broke things. 
Take note, though, that your `onStart()` solution does **not** consider the categories of the blog posts. I'm not sure how the whereIn clause for categories would have to look like.

As a substitute, maybe there could be an internal function that takes care of the redirect automatically given a slug being empty (that only kicks in when you put something like `redirectOnEmptyParameter = :slug`?).

**Comment by jan-vince** [comment]
No problem to redirect in ````onEnd()```` method where ````blogPosts```` object is already present like this:

````
title = "Blog"
url = "/blog/:slug?"
layout = "default"
is_hidden = 0

[blogPosts]
pageNumber = "{{ :page }}"
postsPerPage = 10
noPostsMessage = "No posts found"
sortOrder = "published_at desc"
categoryPage = "page"
postPage = "post"
==
<?php
use \RainLab\Blog\Models\Post;

function onEnd() {

    if( empty($this->param('slug') ) and !empty( $firstPost = $this->posts->first() ) ) {
        if( !empty($firstPost->slug) ) {
            return redirect( url('blog', [ 'slug' => $firstPost->slug ]) , 302 ); // moved temporarily as first post can change
        }
    }

}
==
...
````


## New commit ?

So if you agree I will create a new commit to return post load back into ````onRun()```` method and I will add an above mentioned logic to ````onRender()```` method, so anyone will be still able to force post load by passing slug to component like ````{% component 'blogPost' slug = 'my-slug' %}````.

````php
/**
*  /plugins/rainlab/blog/components/Post.php
*/
...
    public function onRun()
    {
        $this->categoryPage = $this->page['categoryPage'] = $this->property('categoryPage');
        $this->post = $this->page['post'] = $this->loadPost();
    }

    public function onRender()
    {
        if( empty( $this->post and $this->propery('slug') ) ) {
            $this->post = $this->page['post'] = $this->loadPost();
        }
    }
````

Ok ?

**Comment by Harti** [comment]
You’re awesome, that’s a really good idea and if it works as advertised it would indeed solve my problem completely. 

*(I’m sorry that most of the work on this has been stuck on you; however I feel like I’ve learned a good deal about how these plugins work thanks to your help, and might be able to help you better in the future)*
