### ISSUE TITLE
After updating to build #421 categories sorting is broken

### ISSUE THREAD

**Issue by graker** [rainlab/blog-plugin#338]
Hi

I have a block on my site using Categories component and listing all categories sorted as I set on Reorder page. After I updated my site to the latest October build, it seems that the component stopped using Reorder values to sort categories as they are now sorted by category name.

Is it an intended behavior after the update?

**Comment by LukeTowers** [comment]
Not as far as I'm aware. See if you can dig into what's causing the change in behaviour and let us know.

**Comment by graker** [comment]
I've created a test page displaying the default blogCategories component and it is reproduced: categories on the test page are sorted by name while on the reorder page categories are properly sorted.

For now I just changed `orderBy()` in `Categories::loadCategories()` from `'name'` to `'nest_right'` so my production site would work as before the update. But I'll try to look into it soon.

**Comment by LukeTowers** [comment]
Might have something to do with https://github.com/rainlab/blog-plugin/blob/master/components/Categories.php#L90 not working the same anymore. I don't know if that's actually the case, but take a look.

**Comment by graker** [comment]
I thought so too but just can't see where's the problem at the moment.

`getNested()` is a call to [`scopeGetNested()`](https://github.com/octobercms/library/blob/7402b61b7dd7f1cc06faaff3699255e9a34e4e0c/src/Database/Traits/NestedTree.php#L427) which has just one line:

```return $query->get()->toNested();```

And `toNested()` is a method of [`TreeCollection`](https://github.com/octobercms/library/blob/762bb0a048d103db4d659d3749a02ea4877ba48f/src/Database/TreeCollection.php#L20) and the last change for that file was in January of 2016.

So now I'm not sure where to look.

**Comment by LukeTowers** [comment]
Take a look deeper if you can, just because the immediate files haven't changed doesn't necessarily mean that some Laravel internal hasn't changed that changes the query that gets generated. Best of luck!

**Comment by datune** [comment]
This doesn't affect just the Blog plugin, this affects everything using the NestedTree Trait. The Reorder Controller displays the NestedTree correctly, where as the ListController does not. As far as I can tell, it is not related to the Blog plugin itself.

@LukeTowers It seems to me that the problem is in [https://github.com/octobercms/october/blob/master/modules/backend/widgets/Lists.php#L489](url)

It applies a sortColumn without taking into account the setting of showTree. After I changed this line from: 
```php
if ($sortColumn = $this->getSortColumn()) {
```
to this:
```php
if ($sortColumn = $this->getSortColumn() && !$this->showTree) {
```
everything appears to be working. I've created a PR for others to [review and ponder...](https://github.com/octobercms/october/pull/3143)

**Comment by datune** [comment]
@graker Can you please [review this PR](https://github.com/octobercms/october/pull/3143) and, if true, confirm that this fixes the issue?

**Comment by graker** [comment]
@datune I did and it fixes the issue with lists but not the Categories List component.

**Comment by datune** [comment]
@LukeTowers @graker I digged a bit and think that this PR fixes it. @graker Please test and review so we can move forward.

I'm pretty convinced that nested tree sorting has never worked in the categories component, it was always sorted by name. I think the reason is historical (like there is ever any other reason :-P). Nesting has been introduced after the fact, which is why this has slipped through.

**Comment by graker** [comment]
@datune from what I see, I'm sure that it fixes the problem because that looks similar to what I did for a temporary fix: I changed order-by from `name` to `nest_right`. And you just removed the line to allow `getNested()` to do its job which is more elegant. I'm not sure though that it is the root of the problem (see below).

> I'm pretty convinced that nested tree sorting has never worked in the categories component, it was always sorted by name.

Well I've migrated my blog to October a year ago and I had a block with categories sorted manually (i.e. not by category name) so I believe the sorting did work as intended. And it was the case up until L5.5 upgrade. That's why there's some discussion above pointing out that the change that lead to this issue is somewhere else, somewhere deeper, probably in Laravel framework.

**Comment by LukeTowers** [comment]
@graker is there still an issue?

**Comment by graker** [comment]
Yes, in the latest plugin update the issue is still there and still fixed by changing the sorting order from `name` to `nest_right`.

**Comment by LukeTowers** [comment]
@graker could you please make a PR to fix it including a summary of the issue and the fix? Thanks!

**Comment by LukeTowers** [comment]
@graker actually just remembered #342, could you test that and let me know if it works for you?

**Comment by graker** [comment]
@LukeTowers Sure, I've just tested it and it does fix the issue for Categories component. 

Although as I mentioned before it is still not clear what was the reason of the change in original behavior, the fix works.

**Comment by LukeTowers** [comment]
Huh. Well, I'll merge #342 then.
