### ISSUE TITLE
Change MarkdownEditor image uploads to go to the media library

### ISSUE THREAD

**Issue by jawainc** [rainlab/blog-plugin#340]
when image markup is remove from editor, it remove the image from html viewer but it dosen't actually delete the image

**Comment by jan-vince** [comment]
Should it?

What about a situation when you include that file in two blog posts?

**Comment by jawainc** [comment]
what about if user want remove that image? if there's no way to delete it would be piles of unused images.

**Comment by LukeTowers** [comment]
@jawainc there is, it's just in the media library, you could delete it at any time.

**Comment by jawainc** [comment]
there are 2 option (2 buttons for embedding images) for embed image
1: through media library
2: by uploading <---- these image didn't appear in media library

**Comment by LukeTowers** [comment]
Where does the second option get stored?

**Comment by jawainc** [comment]
![image-path](https://user-images.githubusercontent.com/8276213/30842116-7dab0980-a299-11e7-8551-fc5658b91c0d.PNG)
see in image, its always some random directory with random name

**Comment by LukeTowers** [comment]
I think perhaps the solution to that would be to force files uploaded through the second option to be stored in the media library as there is no database record that they are attached to in order to be removed when no longer in use.

**Comment by jawainc** [comment]
we cannot dictate clients, if option is there it will be used.
I use other editor to solve this issue.

Thanks

**Comment by LukeTowers** [comment]
I meant do that in code, have the files uploaded through the second option go straight into the media library instead.

**Comment by jawainc** [comment]
How to do it ?

**Comment by LukeTowers** [comment]
We'd have to change the implementation of the image upload button in the markdown editor. It would probably be a code change to this plugin. I'll edit the title accordingly. Feel free to dig into it yourself and make a PR containing the changes :)

**Comment by jawainc** [comment]
Thanks a lot for your help

**Comment by LukeTowers** [comment]
I'll leave this open for now in case somebody wants to work on implementing support for it.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
