### ISSUE TITLE
Call to undefined function error on uploading blog featured image

### ISSUE THREAD

**Issue by jonathan-hc** [rainlab/blog-plugin#344]
Hello Rainlab,

Firstly, I want to thank you for this wonderful plugin. Great work!

I have been facing this issue on one of my live servers, where uploading a featured image gives the following error:

`Call to undefined function October\Rain\Database\Attach\imagecreatefromjpeg()`

`/htdocs/vendor/october/rain/src/Database/Attach/Resizer.php line 466`

Here's a screenshot of the error:
![blog-plugin-error](https://user-images.githubusercontent.com/32612308/32142515-6f07af34-bcbe-11e7-8afe-7a44e59b8b5e.png)

The server is running PHP 7.1.8 FPM/FastCGI with GD plugin enabled

Curiously, I am not facing this issue on my local development machine, which is running PHP v 7.0.10

Any ideas what might be wrong? 

Thank you!

Jonathan

**Comment by LukeTowers** [comment]
Double check that the GD library is working correctly. See https://stackoverflow.com/a/13338387/6652884
