### ISSUE TITLE
Incorrectly lists the URLs for unpublished blog posts in the sitemap

### ISSUE THREAD

**Issue by jm-mwi** [rainlab/blog-plugin#346]
The plugin currently adds URLs for blog posts even if they aren't published.

The plugin should either only list the blog posts that are published or it should also add the blog post to the robots file as a URL that shouldn't be visited.

EDIT: This is being reported as I'm seeing URL errors show up in my webmaster console.

**Comment by LukeTowers** [comment]
@jm-mwi What version of the blog plugin, sitemap plugin, and OctoberCMS are you running?

**Comment by InquisitiveDevelopment** [comment]
1.2.19 - Blog Plugin
1.0.8 - Sitemap

The site is running build 431.

**Comment by LukeTowers** [comment]
This line (https://github.com/rainlab/blog-plugin/blob/master/models/Post.php#L533) should be what restricts it to only published posts. Are you able to do some debugging to find more information about the issue? @InquisitiveDevelopment

**Comment by InquisitiveDevelopment** [comment]
@LukeTowers it appears to be fixed now.  Webmaster tools are no longer bitching!

**Comment by InquisitiveDevelopment** [comment]
BTW, I'm @jm-mwi. That was my old work account.

**Comment by LukeTowers** [comment]
Good to hear, I'll close this issue for now then.
