### ISSUE TITLE
Single Post not getting hit in Production

### ISSUE THREAD

**Issue by jrodd32** [rainlab/blog-plugin#348]
The individual post page is not getting hit in my production environment. The URL get's updated to the post slug but the blogRoll component is getting displayed instead of the blogPost.

I quickly manually edited the Post.php file in the plugin to dd() the $post var but it never got hit / triggered. 

Has anyone ever encountered this before? 

What is confusing me is it is working in my local and staging environments but not production. 

The servers are created with Chef and the code is deployed with Capistrano so I know there should not be in differences between the environments. 

If anyone has encountered this before and has some ideas to send my way for debugging that would be most appreciated.

Live site (broken): https://advancereadymix.com/news/
Staging site (functional): http://advance-ready-mix.doe1915.com/news

There will be a .htaccess blocker on the staging site.
UN: testing
PW: peek!

**Comment by LukeTowers** [comment]
What plugins do you have? Sounds like you have a URL cache enabled that has incorrect cache material.

**Comment by jrodd32** [comment]
Hey @LukeTowers thanks for the reply.

I have the following plugins installed in all 3 environments:

**Comment by LukeTowers** [comment]
@jrodd32 so the issue is still present? Have you tried `php artisan cache:clear`?

**Comment by jrodd32** [comment]
Hey Luke yeah I’m still having the issue. I’ve ran that command as well as manually deleting all cache folders as well.

I even went as far as writing my own extension the overwrites the Post component and it is still happening.

I can post my code for all files if that would be helpful.


Poor grammar and misspellings sponsored by iPhone.

On Nov 21, 2017, at 15:05, Luke Towers <notifications@github.com<mailto:notifications@github.com>> wrote:


@jrodd32<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjrodd32&data=02%7C01%7Cjlong%40doeanderson.com%7Cc359f6ec20f248fcf08b08d5311b25c3%7C03203a4594eb49efbc8868ebe2ecea1b%7C0%7C0%7C636468915028042443&sdata=LnJTWApRxaL2O8eaKNdkx8Zrj7G2H64M6SH%2FCJDejRw%3D&reserved=0> so the issue is still present? Have you tried php artisan cache:clear?

**Comment by LukeTowers** [comment]
Have you tried redeploying to your production environment manually? Maybe it's missing some files

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
