### ISSUE TITLE
Blog post title not working

### ISSUE THREAD

**Issue by DraganGagi** [rainlab/blog-plugin#350]

**Comment by DraganGagi** [comment]
`title = "post -"
url = "/post/:slug"
layout = "default"
is_hidden = 0

[blogPost]
slug = "{{ :slug }}"
categoryPage = "category-"
==
<?php
function onEnd()
{

    // Optional - set the page title to the post title
    if (isset($this->post))
        $this->page->title = $this->post->title;
}
?>
==
{% component 'blogPost' %}`

**Comment by LukeTowers** [comment]
_No reason provided for closing._
