### ISSUE TITLE
SVG files prevented from being uploaded

### ISSUE THREAD

**Issue by AndrewHaze** [rainlab/blog-plugin#351]
After the update to version 1.2.19, the .svg files can't be uploaded anymore. It was possible before, and such files that have already been uploaded are fine.

**Comment by LukeTowers** [comment]
SVG files have been disabled by default as they are a potential security concern. See https://github.com/octobercms/library/commit/3bbbbf3da469f457881b5af902eb0b89b95189a2#diff-b10ad96937e698dbb2d75768efa33870. You can re-enable them for your project specifically, but as a whole the default has been changed to prevent uploading them.

**Comment by AndrewHaze** [comment]
Thanks!
