### ISSUE TITLE
How can i filter out the post

### ISSUE THREAD

**Issue by stefanreimert** [rainlab/blog-plugin#353]
I now have:
/blog/post/:slug/:page?

And it renders to:
http://localhost:8000/blog/post/first-blog-post

And this is what i want:
http://localhost:8000/blog/first-blog-post

I dont know if it is me and i am overthinking it?

**Comment by LukeTowers** [comment]
Use `/blog/:slug/:page?`

**Comment by stefanreimert** [comment]
@LukeTowers but how does the templating goes from here?
Now when i hit the url i dont get redirected to the blog post...
I put it down just like the tutorial movie for setting up the blog.

**This is my blog page:**
`title = "Blog"
url = "/blog/:page?"
layout = "default"
is_hidden = 0

[blogCategories]
slug = "{{ :slug }}"
displayEmpty = 0
categoryPage = "blog/category"
==`

**And here my post page:**
`title = "Blog post"
url = "/blog/:slug/:page?"
layout = "default"
is_hidden = 0

[blogPost]
slug = "{{ :slug }}"
categoryPage = "blog"
==
{% component 'blogPost' %}`
