### ISSUE TITLE
Wrong code in the documentation

### ISSUE THREAD

**Issue by zooks** [rainlab/blog-plugin#354]
if (isset($this->post))
        $this->page->title = $this->post->title;

`isset($this->post)` returns `false`, so the code doesn't work.

https://github.com/rainlab/blog-plugin/commit/daff5e6bc2fe33f1f7e01d99e250952ca69b0eb5

**Comment by LukeTowers** [comment]
Does `if ($this->post))` work?

**Comment by zooks** [comment]
Yes, it works.

**Comment by LukeTowers** [comment]
Could you make a PR to change that line in the docs then?
