### ISSUE TITLE
Single Posts not displaying + categories not filtering

### ISSUE THREAD

**Issue by BKoehler** [rainlab/blog-plugin#357]
I am having 2 issues with blog posts. Issue #1: Single blog posts are not displaying when a post is clicked,  and Issue #2: Blog categories are not filtering. I click on a category and all posts still listed.

**Comment by LukeTowers** [comment]
Sounds like you have an issue with how you setup the components and the URLs.

**Comment by ronogrimen** [comment]
@LukeTowers I'm having the same issue, categoryFilter not workings on me. Its always show all the posts

**Comment by LukeTowers** [comment]
What build of October are you running? What version of the blog plugin? How is your page with the blog posts listing component setup and how is the page with the single blog post component setup? @BKoehler @ronogrimen

**Comment by LukeTowers** [comment]
The amount of time spent asking for help is directly related to the amount of time spent putting in effort to answer it. If you want help and / or guidance, then invest as much time as possible in making questions that are detailed and easy to understand. Otherwise, nobody is going to invest their time helping with a question that wasn't even worth the askers time to ask correctly.

**Comment by ronogrimen** [comment]
@LukeTowers 431 current build of october and 1.2.19 is the version of blog plugin but I already found a solution. Thank you for replying!

**Comment by LukeTowers** [comment]
@ronogrimen what was the issue for you? Posting here can help out other people with the same issue.

**Comment by BKoehler** [comment]
@ronogrimen I believe I am running the same version as you. What was your solution? If I may ask

**Comment by BKoehler** [comment]
@LukeTowers I followed the video tutorial by Samuel Georges "Building a Blog & Forum Website" which I found via the October documentation.

**Comment by LukeTowers** [comment]
@BKoehler I'll still need to see your code before I can help

**Comment by ronogrimen** [comment]
@BKoehler i used a plugin that shows related tags. (Blog Tags Extension)

**Comment by amjadniazi48** [comment]
i also followed the video of Samuel Georges "Building a Blog & Forum Website" from youtube but it is not filtering the posts category wise

**Comment by LukeTowers** [comment]
Funny how I still can't read minds or your code without seeing it yet 😉

**Comment by amjadniazi48** [comment]
following is the code for my blog page
-------------------------------
title = "blog"
url = "/blog"
layout = "default"
description = "The page showing all the posts"
is_hidden = 0

[blogPosts]
pageNumber = "{{ :page }}"
categoryFilter = ":slug"
postsPerPage = 10
noPostsMessage = "No posts found"
sortOrder = "published_at desc"
categoryPage = "blog/category"
postPage = "blog/posts"

[blogCategories]
slug = "{{ :slug }}"
displayEmpty = 0
categoryPage = "blog/category"
=======
`{% set posts = blogPosts.posts %}

<ul class="post-list">
    {% for post in posts %}
        <li>
            <h3><a href="{{ post.url }}">{{ post.title }}</a></h3>

            <p class="info">
                Posted
                {% if post.categories.count %} in {% endif %}
                {% for category in post.categories %}
                    <a href="{{ category.url }}">{{ category.name }}</a>{% if not loop.last %}, {% endif %}
                {% endfor %}
                on {{ post.published_at|date('M d, Y') }}
            </p>

            <p class="excerpt">{{ post.summary|raw }}</p>
        </li>
    {% else %}
        <li class="no-data">{{ noPostsMessage }}</li>
    {% endfor %}
</ul>

{% if posts.lastPage > 1 %}
    <ul class="pagination">
        {% if posts.currentPage > 1 %}
            <li><a href="{{ this.page.baseFileName|page({ (pageParam): (posts.currentPage-1) }) }}">&larr; Prev</a></li>
        {% endif %}

        {% for page in 1..posts.lastPage %}
            <li class="{{ posts.currentPage == page ? 'active' : null }}">
                <a href="{{ this.page.baseFileName|page({ (pageParam): page }) }}">{{ page }}</a>
            </li>
        {% endfor %}

        {% if posts.lastPage > posts.currentPage %}
            <li><a href="{{ this.page.baseFileName|page({ (pageParam): (posts.currentPage+1) }) }}">Next &rarr;</a></li>
        {% endif %}
    </ul>
{% endif %}
{% component 'blogCategories' %}`
Following is the code for my blog single post page
-----------------------------------------------
title = "Blog Posts"
url = "/blog/posts/:slug"
layout = "default"
is_hidden = 0

[blogPost]
slug = "{{ :slug }}"
categoryPage = "blog/category"
=======
`{% set post = blogPost.post %}

<div class="content">{{ post.content_html|raw }}</div>

{% if post.featured_images.count %}
    <div class="featured-images text-center">
        {% for image in post.featured_images %}
            <p>
                <img
                    data-src="{{ image.filename }}"
                    src="{{ image.path }}"
                    alt="{{ image.description }}"
                    style="max-width: 100%" />
            </p>
        {% endfor %}
    </div>
{% endif %}

<p class="info">
    Posted
    {% if post.categories.count %} in
        {% for category in post.categories %}
            <a href="{{ category.url }}">{{ category.name }}</a>{% if not loop.last %}, {% endif %}
        {% endfor %}
    {% endif %}
    on {{ post.published_at|date('M d, Y') }}
</p>
`
---------------------
and for category page it is just like the above code used in blog page just url is different and i.e
`title = "Blog Category"
url = "/blog/category/:slug"
layout = "default"
is_hidden = 0

[blogCategories]
slug = "{{ :slug }}"
displayEmpty = 0
categoryPage = "blog/category"

[blogPosts]
pageNumber = "{{ :page }}"
categoryFilter = ":slug"
postsPerPage = 10
noPostsMessage = "No posts found"
sortOrder = "published_at desc"
categoryPage = "blog/category"
postPage = "blog/posts"`
==

**Comment by jan-vince** [comment]
I think there should be ````categoryFilter = "{{ :slug }}"```` in ````[blogPosts]```` component definition.

**Comment by amjadniazi48** [comment]
i did the same now its filtering category wise but it showing the post with categories but on categories area it shows the categories with 0 posts as shown in the following diagrams
![4](https://user-images.githubusercontent.com/2420029/35939537-422a1916-0c6e-11e8-8c58-c66243e530dd.png)
![5](https://user-images.githubusercontent.com/2420029/35939538-4260ccea-0c6e-11e8-9d76-733ca6dfb25c.png)

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
