### ISSUE TITLE
Add code syntax in posts

### ISSUE THREAD

**Issue by grafxflow** [rainlab/blog-plugin#362]
I am currently trying to add php code syntax in my blog posts for tutorials.

It works for php syntax of code apart from '<?php' itself. Anytime I try to add something like '&lt;?php' it changes it back to '<?php' and therefore doesn't appear. Is there anyway around this issue?

**Comment by graker** [comment]
Have you tried to use markdown 
\`\`\`
some code
\`\`\` syntax? 

[Take a look](https://graker.ru/news/2017/07/04/octobercms-ajax-popup-widget) I posted code with php and it works.

Also, you should probably ask it on forum since it's not really a bug.

**Comment by graker** [comment]
If there's a bug then maybe you could provide an extended example? Like, OC and blog plugin version, editor in use, post sample you have an issue with

**Comment by grafxflow** [comment]
An example would be.

I have replaced ``` replaced with ''' for example.

'''php 
<?php 
echo 'hello world'; 
?>
'''

Which works fine but when going back to edit the post it gets replaced with...

<pre><code class="language-php">
<?php
echo 'hello world';
?>
</code></pre>

**Comment by LukeTowers** [comment]
@grafxflow this sounds like an issue with the ProBlog plugin

**Comment by grafxflow** [comment]
Yes been looking through it now it return the 'content' rather than the 'markdown_content'. I will contact them now :) Thanks for all your help.

**Comment by GinoPane** [comment]
@LukeTowers this one should be closed

**Comment by w20k** [comment]
@GinoPane be more specific why? Please 😄

**Comment by GinoPane** [comment]
@w20k ah, I was just scanning opened issues, read comments and found out that this issue belongs to the ProBlog plugin, and the TS confirmed that above:

> sounds like an issue with the ProBlog plugin

> I will contact them now

**Comment by w20k** [comment]
> @grafxflow this sounds like an issue with the ProBlog plugin
> Yes I have been looking through it now it return the 'content' rather than the 'markdown_content'. I will contact them now :) Thanks for all your help.

Closing, based on the @grafxflow comment.
Not related to the Blog Plugin.
