### ISSUE TITLE
pagination using parameter

### ISSUE THREAD

**Issue by hakimihamdan88** [rainlab/blog-plugin#368]
possible to use "?page=1" as pagination?

**Comment by LukeTowers** [comment]
Why not routing parameters? `/posts/:page?`

**Comment by hakimihamdan88** [comment]
need to combine /blog , /blog/post-slug and /blog/page

**Comment by LukeTowers** [comment]
Make the routes more specific:
http://octobercms.com/docs/cms/pages#url-syntax

Blog: `/blog`
Blog Page: `/blog/:page?|^[0-9]+$`
Blog Post: `/blog/:post?`

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
