### ISSUE TITLE
post.url not getting correct url for post

### ISSUE THREAD

**Issue by SethArchambault** [rainlab/blog-plugin#371]
It returns a page instead.. So I've manually replaced all instances of post.url with '/myurl/' . post.slug

Not ideal!

**Comment by LukeTowers** [comment]
No code provided nor replication instructions.

Not ideal!

**Comment by MeteALANLI** [comment]
![no_url](https://user-images.githubusercontent.com/9418142/37906872-1bfba8b4-310c-11e8-95d4-f7a7d8173fe4.JPG)

Like he said post.url or category.url returns a page instead of slugged url. I've manually replace post.url and category.url to  '/myurl/' . post.slug

**Comment by LukeTowers** [comment]
@MeteALANLI @SethArchambault sounds like you both haven't correctly setup the components to generate those URLs for you. See the `postPage` and `categoryPage` properties here: https://github.com/rainlab/blog-plugin#post-list-page
