### ISSUE TITLE
[Feature Request] Allow external featured images

### ISSUE THREAD

**Issue by readtedium** [rainlab/blog-plugin#373]
Hi there,

I have a website that I'm moving over with about 500 posts, each with an existing featured image. I'm already using imgix to manage my photos and would like to continue doing so. However, the plugin as designed requires featured images to be uploaded into the October CMS system.

I'm assuming that I could potentially use a custom field to put in existing URLs but it would be helpful to have the option of using an external image source for featured images.

**Comment by LukeTowers** [comment]
How do you envision such a system working @shortformblog?

**Comment by shortformblog** [comment]
I don't think to has to be anything complicated. In Ghost, there is a small icon in the corner of their image upload box that allows you to switch the option to a URL instead:

![Before](https://cdn.tedium.co/Screenshot%202018-03-12%2000.43.12.png)

![After](https://cdn.tedium.co/Screenshot%202018-03-12%2000.43.24.png)

By making it easy to let the user select this it could ease some complications elsewhere for folks moving their sites over.

**Comment by LukeTowers** [comment]
How would you suggest implementing that @shortformblog? Currently the featured image is a file attachment to the post object directly, so if you wanted to have just a URL there you would have to have support for doing so in your theme that's rendering the post. Such a think could conceivably be achieved by a plugin extending this one.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
