### ISSUE TITLE
Edit post - cancel text

### ISSUE THREAD

**Issue by avitkinov** [rainlab/blog-plugin#374]
![screenshot from 2018-03-12 13 03 43](https://user-images.githubusercontent.com/3220115/37280338-233a4e62-25f6-11e8-8eb5-22e7cc768e68.png)

**Comment by LukeTowers** [comment]
That's not from this plugin:
![screen shot 2018-03-12 at 4 16 44 pm](https://user-images.githubusercontent.com/7253840/37312491-de15163a-2610-11e8-8b09-411bb0a4e27e.png)
