### ISSUE TITLE
All posts show on Chrome but some posts do not show on other browsers like Microsoft Edge & Mozilla

### ISSUE THREAD

**Issue by wertykid** [rainlab/blog-plugin#377]
Hello,

Everything works for the plugin but I am getting this weird issue whereby all the posts show on Chrome but some posts do not show on other browsers like Microsoft Edge & Mozilla. While testing other plugins like SiteSearch, they were not able to search for the posts that do not show in Microsoft Edge & Mozilla as well.  Can I know why is that so?

**Comment by LukeTowers** [comment]
@wertykid my guess is that you are running into the feature of showing unpublished posts to logged in users. See https://github.com/rainlab/blog-plugin/issues/349#issuecomment-346851649 and the related issues. 

Try viewing the site in incognito in chrome to see if the articles still show up.

**Comment by wertykid** [comment]
Hello Luke, 
Thank you for the quick reply. I tried it out in incognito mode and the posts show. Thanks a lot for the help!

**Comment by LukeTowers** [comment]
@wertykid so did you figure out your issue then?

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
