### ISSUE TITLE
Adding code, not code syntax, to a blog post

### ISSUE THREAD

**Issue by metalac** [rainlab/blog-plugin#380]
I'm trying to figure out what is the right way to add code to a blog post, or if it's even possible?  I want to make a blog post that has a little form on the bottom where user can enter a few numbers at the bottom and on submit a calculation is performed and result displayed.  I can do this no problem using the theme pages, but would ideally like to do this within the blog, since I'd like to keep all my content with the blog.  I'd be OK with making the component and then inserting the component on the blog page, but it appears that can't be done.

Thanks.

**Comment by metalac** [comment]
Ideally it would behave similarly to the way "pages" behave in the CMS section. You'd have a layout section and a code section.  Not sure how this would work from the security stand point.  Worst case I'd like it to be a component I could add to the blog post.

**Comment by LukeTowers** [comment]
You could in theory add this functionality with a plugin extending the blog plugin; which is probably the best way to go with this idea, it seems a bit beyond the scope of what most users would need this plugin to do; at least to my initial assessment of the proposed idea.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
