### ISSUE TITLE
Are there any sorts of tests for this plugin? 

### ISSUE THREAD

**Issue by Ognj3n** [rainlab/blog-plugin#383]
Hi there! 

I'm interested in testing this plugin using phpunit and behat but would like to know if there are already some tests written? I checked build branch and couldn't find them.

**Comment by LukeTowers** [comment]
@Ognj3n there are no tests for this at present time, perhaps @scottbedard could add some.

**Comment by scottbedard** [comment]
It sounds like @Ognj3n is interested in writing some tests, I'd be happy to be a reviewer on the PR

**Comment by Ognj3n** [comment]
@scottbedard Not really an expert in those, so not sure if it's a good idea :)

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
