### ISSUE TITLE
Can I Stop markdown styling in blog editor in this plugin?

### ISSUE THREAD

**Issue by zakir1929** [rainlab/blog-plugin#384]
My client want it to be simple and he does not not like markdown styling syntax in editor.

**Comment by LukeTowers** [comment]
See http://octobercms.com/plugin/janvince-smallextensions

**Comment by zakir1929** [comment]
Thankyou @LukeTowers  for your response. although i did that by extending that plugin and changed field type to richeditor.
        \Event::listen('backend.form.extendFieldsBefore', function($widget)
        {

            if (!$widget->model instanceof \RainLab\Blog\Models\Post){
                return;
            }

            $fields = [
	                'content' => [
	                    'tab' => 'rainlab.blog::lang.post.tab_edit',
	                    'type' => 'richeditor',
			            'stretch' => 'true',
	                ]
            ];

            if($fields){
            	foreach($fields as $key => $value){
			        $widget->secondaryTabs['fields'][$key] = $value;
            	}
            }

        });

**Comment by zakir1929** [comment]
Thankyou @LukeTowers  for your response. although i did that by extending that plugin and changed field type to richeditor.


        \Event::listen('backend.form.extendFieldsBefore', function($widget)
        {

            if (!$widget->model instanceof \RainLab\Blog\Models\Post){
                return;
            }

            $fields = [
	                'content' => [
	                    'tab' => 'rainlab.blog::lang.post.tab_edit',
	                    'type' => 'richeditor',
			     'stretch' => 'true',
	                ]
            ];

            if($fields){
            	foreach($fields as $key => $value){
			        $widget->secondaryTabs['fields'][$key] = $value;
            	}
            }

        });

**Comment by LukeTowers** [comment]
@zakir1929 test that thoroughly, the markdown field stores it's content in the `content` column which is then transformed into the `content_html` column. I would recommend that you remove the `content` field and replace it with the `content_html` field being a richeditor.
