### ISSUE TITLE
Extend post with future event date

### ISSUE THREAD

**Issue by Antar74** [rainlab/blog-plugin#386]
Hello. I'm enjoying your plugin very much, it's super useful. Congrats!

But I need some extra features on the blog post, I need to include an event date for posts in an event or activity category. Out of the box I have the post title, the post publishing date, the post category, and the post content. How can I have an extra field to add data related to a future date (not the post date)? I'm trying to build a site where the posts are events or activities with specific dates set in the near future. 
Could you please advise how can I extend the blog post options to do this? Ca I achive this with your plugin? Or should I use other plugin(s) to handle the job?

Thanx in advance :)

**Comment by LukeTowers** [comment]
@Antar74 if you're not able to do that yourself with the [OctoberCMS docs](https://octobercms.com/docs) then I would recommend looking at another plugin built specifically for managing events.
