### ISSUE TITLE
Pagination not working - component configured with :page? parameter

### ISSUE THREAD

**Issue by johnyserpa** [rainlab/blog-plugin#387]
I have this code in order to have pagination in a postList.
```
{% if posts.lastPage > 1 %}
<div>
    <ul class="col-xs-12 Blog-pages-button clear-fix">
        {% if posts.currentPage > 1 %}
        <li><a href="{{ this.page.baseFileName|page({ (pageParam): (posts.currentPage-1) }) }}">Prev</a></li>
        {% endif %}

        {% for page in 1..posts.lastPage %}
        <li class="{{ posts.currentPage == page ? 'active' : null }}">
            <a href="{{ this.page.baseFileName|page({ (pageParam): page }) }}">{{ page }}</a>
        </li>
        {% endfor %}

        {% if posts.lastPage > posts.currentPage %}
        <li><a href="{{ this.page.baseFileName|page({ (pageParam): (posts.currentPage+1) }) }}">Next</a></li>
        {% endif %}
    </ul>
</div>
{% endif %}
```

Also the page is using this component with:
![component configuration](https://image.ibb.co/m98WeS/Screenshot_from_2018_05_08_19_57_49.png)

Shouldn't it be working?
You can see the live webpage [here](https://www.colegiopaulovi.com/noticias/)

Help is much appreciated.

**Comment by johnyserpa** [comment]
Sorry, I had to fix it with a workaround. I'm hardcoding the path /noticias and using the var {{ page }} to add the pagination number.

**Comment by johnyserpa** [comment]
@LukeTowers this is the structure:
![url structure](https://preview.ibb.co/bW9qQd/Screenshot_from_2018_05_09_22_01_38.png)

**Comment by johnyserpa** [comment]
@LukeTowers this is the structure:
![url structure](https://preview.ibb.co/eyXukd/Screenshot_from_2018_05_09_22_03_41.png)

**Comment by LukeTowers** [comment]
What's the issue that you're running into?

**Comment by johnyserpa** [comment]
`{{ this.page.baseFileName|page({ (pageParam): (posts.currentPage-1) }) }}`
`{{ this.page.baseFileName|page({ (pageParam): page }) }}`
`{{ this.page.baseFileName|page({ (pageParam): (posts.currentPage-1) }) }}`

These codes are not generating the an URL. Links become the same as the page we are in.

**Example**: 
If we are in the `/noticias/2` page, all links will be `/noticias/2`, if we are in `/noticias` page, all links will be `/noticias`

Was I clear enough?

**Comment by LukeTowers** [comment]
@johnyserpa thanks. Where is the partial that you have the links being generated in? Have you tried debugging the `posts.currentPage` and `page` variables to see what they contain in the context of your custom partial?

**Comment by sozonovalexey** [comment]
I confirm the bug when perPage more than 10. The problem in `vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php` on line 1464. `$method` variable accept this param with empty `$parameters`. So the `$column` in `value($column)` has no value. I don't know how it works but if I set 

```
        if (empty($parameters))
            $parameters = [0 => $method];
```

everything works fine.

**Comment by sozonovalexey** [comment]
![2018-05-17_20-57-01](https://user-images.githubusercontent.com/1676060/40195060-0fd0df3c-5a15-11e8-9d8c-c78f2119cdfb.png)

**Comment by sozonovalexey** [comment]
The problem was in two similar components (with similar params) on one page.

**Comment by LukeTowers** [comment]
@johnyserpa is @sozonovalexey's answer correct?
