### ISSUE TITLE
Improve setUrl to handle arbitrary param names

### ISSUE THREAD

**Issue by GinoPane** [rainlab/blog-plugin#392]
Hey guys! 

The lines I'm referring to are: 
https://github.com/rainlab/blog-plugin/blob/599102985de963773a3361006efcb902f2911985/models/Post.php#L145

It is `Post::setUrl` method. And actually I detected the same issue for plenty of other plugins. The summary is simple: page parameter are hardcoded, but the URL itself can be changed when we create a page which uses our component, like this:

![image](https://user-images.githubusercontent.com/3897579/41961551-ad22fbae-79ea-11e8-9a51-17dcd24e1721.png)

The model itself still expects the page param to be "slug". And it will break all links generated by `setUrl`, like this: `/blog/post/default (instead of slug value).`

Is it considered an issue? I think that those params shouldn't be hardcoded as long as the page URL could be easily changed from UI.

**Comment by LukeTowers** [comment]
Feel free to make a PR to add an additional param `$paramMapping = ['slug' => 'real_slug_param_name', ...]` to the `setUrl` method

**Comment by GinoPane** [comment]
Hi @LukeTowers! Ok, will do. Already did something similar for my work-in-progress plugin.

**Comment by GinoPane** [comment]
Will push new commits to this soon
