### ISSUE TITLE
Featured Images Path (First image only)

### ISSUE THREAD

**Issue by JSalvonaBlueprint** [rainlab/blog-plugin#402]
Hello,

I've been loving the plugin and it's definitely going to be used again by me. However I have one small problem.

I want to use a featured image for my blog posts page however I have multiple featured images and I only want to use the first featured image for each post on this page. I couldn't figure out how to do this, I tried various PHP methods using functions however none worked. 

This is the code I used
```twig                
{% if post.featured_images.count %}<!-- Blog Post featured images -->
                  {% for image in post.featured_images %}
                            <div class="featured-main">
                              <p>
                                  <img
                                      data-src="{{ image.filename }}"
                                      src="{{ image.path }}"
                                      alt="{{ image.description }}"
                                      class="img-fluid mx-auto d-block fr-fic fr-dii" />
                              </p>
                            </div>
                  {% endfor %}
                {% endif %}<!-- ./Blog Post featured images -->
```
Would appreciate if anyone could help me out!

I could use jQuery to remove all images except the first however I don't want to do this, this would be a last resort.

Keep up the good work 👍

Kind regards,
Jack S

**Comment by LukeTowers** [comment]
```twig
{% if post.featured.images.count %}
    {% set image = post.featured_images.0 %}
    <div class="featured-main">
        <p>
            <img
                data-src="{{ image.filename }}"
                src="{{ image.path }}"
                alt="{{ image.description }}"
                class="img-fluid mx-auto d-block fr-fic fr-dii" />
        </p>
    </div>
{% endif %}
```

**Comment by JSalvonaBlueprint** [comment]
Ah brilliant, thank you for the swift response Luke! I was thinking about it completely wrong.

**Comment by vrkansagara** [comment]
@LukeTowers  use ``` {% set image = post.featured_images.first %}``` instead of ```0``` for fetching first post.

**Comment by mittultechnobrave** [comment]
How can I alllow users to add only single featured image instead of multiple ? any hook ?
