### ISSUE TITLE
How to export posts with featured image

### ISSUE THREAD

**Issue by Driglu4it** [rainlab/blog-plugin#403]
Hello, i have a problem. 
When i trying do export blog posts i have no choose featured image in export column.
Any have idea (sorry, for my bad english)?

**Comment by LukeTowers** [comment]
@Driglu4it Featured images are stored in the filesystem, how exactly do you expect to be able to export them and have it be a usable format utilizing elsewhere?

**Comment by Driglu4it** [comment]
I meant the URL of attachment image

**Comment by LukeTowers** [comment]
@Driglu4it a pull request. Basically, you write the code that you need and then you submit it to this repository by making a pull request on Github and then I review it and merge it into this repository.

**Comment by bennothommo** [comment]
Implemented support for exporting featured images as of 2a3d4ae4c9b2575328c24671f948e718b3e370b4.
