### ISSUE TITLE
Categories component without 'displayEmpty' ignores nested categories

### ISSUE THREAD

**Issue by Rike-cz** [rainlab/blog-plugin#404]
**Situation:** _Category 1_ and nested _Category 1-1_. _Category 1-1_ has a post.

**Expected behavior:** When I am in _Category 1_, I can see all posts of nested categories too. When I use Categories component with `displayEmpty = false`, I can see in returned tree _Category 1_ and nested _Category 1-1_, because nested _Category 1-1_ has a post.

**Actual behavior**: First one works fine. But component Categories do not return _Category 1_ (yes, because it's empty) even though nested _Category 1-1_ is not empty and post from _Category 1-1_ is listed on _Category 1_ detail page.
I think problem is in this SQL query: https://github.com/rainlab/blog-plugin/blob/master/components/Categories.php#L83-L92

Is it bug or feature?

**Comment by LukeTowers** [comment]
@Rike-cz probably a bug, feel free to submit a PR to improve that query.

**Comment by Rike-cz** [comment]
I am not sure that my solution is good. Please take a look: https://github.com/Rike-cz/blog-plugin/commit/6989124245a7e2e8248ed7893de74447026ebf78

**Comment by bennothommo** [comment]
@Rike-cz If you are still interested in seeing this actioned, could you submit your changes above as a PR so that we can determine if it conflicts with any recent changes?

**Comment by Rike-cz** [comment]
@bennothommo You can try it.

**Comment by bennothommo** [comment]
Thanks @Rike-cz :)

**Comment by bennothommo** [comment]
Fixed by #434.
