### ISSUE TITLE
Current page number appended to category url links

### ISSUE THREAD

**Issue by mennax** [rainlab/blog-plugin#405]
If I visit second page: http://mydomain.test/blog/2

    title = "Blog"
    url = "/blog/:page?"
    layout = "default"
    is_hidden = 0
    
    [blogPosts]
    pageNumber = "{{ :page }}"
    postsPerPage = 5
    noPostsMessage = "No posts found"
    sortOrder = "published_at desc"
    categoryPage = "blog-category"
    postPage = "blog-post"
    ==
    {% set posts = blogPosts.posts %}
    {% for post in posts %}
        {% for category in post.categories %}
            <a href="{{ category.url }}">{{ category.name }}</a>
        {% endfor %}
    {% endfor %}

{{ category.url }}
return: /blog/category/myslug/2

Blog v. 1.2.19
System build 437

Thank you!

**Comment by mennax** [comment]
Fixed.

    <a href="{{ category.url }}">{{ category.name }}</a>

becomes

    <a href="{{ 'blog-category'|page({slug:category.slug, page:false}) }}">{{ category.name }}</a>

**Comment by petehalverson** [comment]
I can confirm this issue.

I believe the underlying issue is here: https://github.com/rainlab/blog-plugin/blob/master/models/Category.php#L77

@LukeTowers I can't think of a reason you'd call `$category->setUrl()` wanting route parameters to persist seeing that it's not used for the paginator.

**Comment by LukeTowers** [comment]
Thanks @petehalverson!
