### ISSUE TITLE
Filter blog post list by month

### ISSUE THREAD

**Issue by Antar74** [rainlab/blog-plugin#407]
Hello

I need to filter a post list form a specific category by month (set with the publishing date). I already know how to filter by category, but not by publishing date. How can I do that? Thanks in advance!

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
