### ISSUE TITLE
bug with :page

### ISSUE THREAD

**Issue by dmi3yy** [rainlab/blog-plugin#41]
http://monosnap.com/image/p8fmzL4lrQjNVfT8MTUfmxNjurdpWU
http://monosnap.com/image/NmmYyICM9l6lBZgrc9SKQUUvDJpagB

I use 2 components 

forums and Blog 

in Blog for parPage use str
for Forum page  but when  go tu page 2 in Forum  Blog do the same

**Comment by masterweb121** [comment]
Did you add this to code section?

**Comment by LukeTowers** [comment]
Odd. If anybody can reproduce this, we'll reopen and take a look.

**Comment by daftspunk** [comment]
Also provide us with a sample theme that demonstrates the issue clearly.
