### ISSUE TITLE
Firing events

### ISSUE THREAD

**Issue by briddle** [rainlab/blog-plugin#410]
Is it possible to add firing events onPost etc.?

**Comment by LukeTowers** [comment]
Propose the events that you wanted added, what parameters would be expected, and where exactly you want it and we'll consider it.

**Comment by briddle** [comment]
Hi Luke,

Just to be sure first: Is it correct that the Blog plugin does not fire events or am I missing something in the docs?

**Comment by LukeTowers** [comment]
The blog plugin itself right now does not fire any of its own events, there are still the core events available though.

**Comment by briddle** [comment]
Hi Luke,

Ah, I forgot about the core events, those will work for me :)
Thank you!

Closing.
