### ISSUE TITLE
Importing posts does not assign the selected categories

### ISSUE THREAD

**Issue by mennax** [rainlab/blog-plugin#411]
blog/models/postimport/PostImport.php

        elseif ($this->categories) {
            $ids = (array) $this->categories;
        }

it should be:

        elseif ($this->post_categories) {
            $ids = (array) $this->post_categories;
        }

**Comment by LukeTowers** [comment]
Why should it be that way?

**Comment by mennax** [comment]
Hi Luke,
I'm sorry but I do not speak English very well nor am I an experienced
developer:

If I import posts and the option "Create categories specified in the import
file" is checked: everything good
but
if I import posts with the option unchecked and I select some categories
that imported posts will belong to
the table rainlab_blog_posts_categoriesis is not populated

blog/models/postimport/fields.yaml
the field name is post_categories

I tested, it works

October System build 437
Blog plugin 1.2.19

**Comment by LukeTowers** [comment]
@mennax can you submit a PR to change `post_categories` to `categories` in the fields.yaml file?

**Comment by mennax** [comment]
@LukeTowers Sorry, I am not able to submit a PR

with this change I get the error:

"The model class RainLab\Blog\Models\PostImport must define a method getCategoriesOptions() returning options for the 'categories' form field."

I have to change

in blog/models/PostImport.php

    public function getPostCategoriesOptions()
    {
        return Category::lists('name', 'id');
    }

in

    public function getCategoriesOptions()
    {
        return Category::lists('name', 'id');
    }

**Comment by LukeTowers** [comment]
Probably, I don't have time to look into it a whole bunch. Give it a try and test it out a couple of different ways and see what works :)

**Comment by mennax** [comment]
Already tested,
with and without "Create categories specified in the import file"  checked,
works like a charm! 
Thanks

**Comment by mennax** [comment]
OK I try

**Comment by mennax** [comment]
Done. Can you tell me please if I've created the PR well?

**Comment by LukeTowers** [comment]
Looks good to me @mennax!
