### ISSUE TITLE
Insert Components using MarkDown

### ISSUE THREAD

**Issue by SalocinDotTEN** [rainlab/blog-plugin#413]
Hi,

I would like to include another OctoberCMS component (e.g. Polls) into the blog post content itself by using the Markdown syntax.

Is this possible?

Thank you.

**Comment by LukeTowers** [comment]
@SalocinDotTEN what sort of syntax are you thinking of for this? Please provide an example of the markdown code you would expect to use to include a component and how you would handle populating that component's properties.

**Comment by SalocinDotTEN** [comment]
Hi @LukeTowers,

I am intending to have a shortcode-like syntax e.g.
`[poll id="1"]`
that is simple for the blog editors to enter and the display result is the appropriate poll from the poll component with the correct ID.
If there is no ID it should not display anything or should show an error message.

**Comment by LukeTowers** [comment]
While I like this idea, I don't really have time to implement it myself (unless you want to sponsor the work). Would you be willing to implement it yourself and make a PR or sponsor it being added?

**Comment by SalocinDotTEN** [comment]
Alright thanks. I shall see what I can do and whether it can be made into a pull request.

**Comment by SalocinDotTEN** [comment]
Sorry for the long delay. I have found another way by using the blog tags plugin and having an if statement to detect the tag and show the according survey.
