### ISSUE TITLE
The preview of video doesn't appear

### ISSUE THREAD

**Issue by gergo85** [rainlab/blog-plugin#419]
On the Github:
![novideo](https://user-images.githubusercontent.com/2959112/49637375-7cc70b80-fa05-11e8-821e-c4e8621038f9.JPG)

and October too:
![novideo_cms](https://user-images.githubusercontent.com/2959112/49637394-8badbe00-fa05-11e8-9a69-2803563044f2.JPG)

**Comment by bennothommo** [comment]
The video has been changed to a link as of 639a9b3b277161781940302d1165daa76eb8acf7.
