### ISSUE TITLE
[Change] Featured Image should use Media Manager by default

### ISSUE THREAD

**Issue by drmzio** [rainlab/blog-plugin#424]
Blog posts commonly use the same featured image across multiple posts and it makes sense that the featured image should open up the media manager. WordPress does this by default. Also, people using S3 to store media can attach their external image to the blog post using the media manager, rather than having to upload it manually.

The blog plugin was released in 2014 but the media manager was released a year later, so I think that's why it hasn't been implemented into the blog plugin.

Several issues have already brought this up: #204 #304 #301 #147 and a pull request to implement this change: #261 

Any thoughts on this change?

**Comment by LukeTowers** [comment]
It's not something that can be easily changed given that it would break existing installs, but it's behaviour that's easily modified by using a plugin to extend this one.

**Comment by alainstudio** [comment]
Media Manger would be a nice addition, also you could just keep this as it is, so it will not break any existing install, and call in BLOG-PLUGIN 2 - with media... I am new to October CMS, moving a couple WP website to October CMS, thanks for your hard work!

**Comment by drmzio** [comment]
@LukeTowers Agree with @alainstudio. Perhaps have this feature implemented on the next major release.

**Comment by drmzio** [comment]
Ok so I've managed to create a small plugin that adds the media manager widget to a new `banner_image` field. Since it's very small, I don't think it needed to be published on the marketplace. This method uses the Posts `metadata` column to store the saved image.

Here's the plugin code, along with an example on how to access the banner image URI inside Twig template: https://gist.github.com/drmzio/984c05930fa7060eac8acf8607b636d3

![](https://cl.ly/917c3f8875b2/Screen%252520Shot%2525202019-02-19%252520at%2525207.56.42%252520PM.png)

**Comment by LukeTowers** [comment]
I'm going to say that the official way of accomplishing this request will be extending the blog plugin yourself to do so. October is built to make those sorts of extensions easy to accomplish so I would prefer we kept away from a breaking change for something that is easily implemented by whoever wants it when they want it.

**Comment by stefanreimert** [comment]
Unsubscribe

Verstuurd vanaf mijn iPhone

**Comment by u07** [comment]
@drmzio, 
> Since it's very small, I don't think it needed to be published on the marketplace

Cool things are sometimes small, but still cool. Like that cool tomato-slice-holding-gizmo I bought today) Your plugin makes things simpler, so it is sure worth publishing. And thanks for the code!
