### ISSUE TITLE
Adding blog author and avatar to post list and post views

### ISSUE THREAD

**Issue by StrangerPings** [rainlab/blog-plugin#427]
I've seen many solutions but none seem to work.  I have tried 

```
{{ post.user.first_name }} 
{{ post.user.last_name}} 
{{ post.user_id }}
```

in the components template files.  Even tried adding

`public $belongsTo = [ 'user' => ['Backend\Models\User','key'=>'user_id'] ];`

to the model file in rainlab/blog

Yet nothing outputs.  I have also tried

https://octobercms.com/forum/post/adding-author-to-blog-post
https://github.com/rainlab/blog-plugin/issues/206
https://github.com/rainlab/blog-plugin/issues/98

I see that there is a relation in rainlab/models/post with the user, but I can't even get it to display

https://github.com/rainlab/blog-plugin/blob/master/models/Post.php#L78-L80

Any ideas?

**Comment by w20k** [comment]
Have you try `{{ dump(post) }}` or `{{ dump(post.user) }}` to understand what you have in there.

**Comment by StrangerPings** [comment]
@w20k Yes I have tried, dumping post outputs a lot of info and post.user returns null.

![image](https://user-images.githubusercontent.com/22084825/53272881-61a59700-36ea-11e9-852b-4da3695b5d43.png)

**Comment by StrangerPings** [comment]
There is even a theme that displays the post author https://octobercms.com/theme/krisawzm-simply-blog

However on a quick installation it doesn't work either.  I haven't used October in about a yearso something has changed since as that used {{ post.user.full_name }} https://github.com/kalfheim/simply-blog-theme/blob/master/partials/blogPostsListRaw.htm#L23

**Comment by w20k** [comment]
@StrangerPings do you have User in user table?
One more thing, users won't be applied, and I don't think there is an option right now to update postest with "admin" users

**Comment by StrangerPings** [comment]
@w20k I left in the default post which of course doesn't have a user!  I am such an idiot 🤕 Many thanks for solving this one for me!  I would have been going around in circles for days 😛
