### ISSUE TITLE
Help with Blog layout

### ISSUE THREAD

**Issue by cloudwales** [rainlab/blog-plugin#429]
Hi. I was wondering how i would get the page posts to show in a row of 2 posts. Hope that makes sense.

So there will be 2 articles on a row.

Any help would be greatful
Many thanks

**Comment by bennothommo** [comment]
@cloudwales You can modify the blog posts component markup to any format you would like. For example, you can copy the component partial (https://raw.githubusercontent.com/rainlab/blog-plugin/master/components/posts/default.htm), place it into your layout or page that the component is tied to, and then replace every reference of `__SELF__` with the component's alias (by default, this is `blogPosts`). This would allow you to set up a different layout for the blog posts.

You can find more info on this in the Components docs:
https://octobercms.com/docs/plugin/components
