### ISSUE TITLE
need date with time

### ISSUE THREAD

**Issue by dmi3yy** [rainlab/blog-plugin#43]
now only date  incorrect Sort order in list of posts  if 2 or more in one day

**Comment by gentoid** [comment]
vote for this

**Comment by graker** [comment]
Hi guys

It's possible to have a quick workaround using Laravel events API. Just add new plugin (e.g. with scaffolding), and then at the beginning of Plugin.php add
`use RainLab\Blog\Models\Post;`
Then add boot() implementation to the Plugin class:
`public function boot() {
    Post::saving(function ($post) {
      $time = new Carbon($post->published_at);
      $time->setTime(date('H'), date('i'), date('s'));
      $post->published_at = $time->toDateTimeString();
    });
  }`

This code would add current hour, minutes and seconds to 'published_at' field anytime you create or update blog posts. Off course, it's a quick one and has some problems. For example, it doesn't respect timezones and it can mess with order when editing the next day after creating several posts. But it's not hard to alter the code for your needs really.

Anyway I think that the plugin should really include a time input for the published_at field at some point. Don't see why not to.

**Comment by LukeTowers** [comment]
Fixed in https://github.com/rainlab/blog-plugin/pull/180
