### ISSUE TITLE
No center image option in editor

### ISSUE THREAD

**Issue by hola56** [rainlab/blog-plugin#432]
Hi,

There doesn't appear to be an option to center an image if you upload it to the post and then click on it- any ideas on how to get that enabled please?

Also, there doesn't seem to be a preview post option available on either draft or published posts - is there a way to add that?

Many thanks.

**Comment by bennothommo** [comment]
@hola56 Would you mind providing us more information on this? Are you referring to an image uploaded directly into the editor, or an image uploaded as a "featured" image?

**Comment by hola56** [comment]
Hi, please see screenshot of issue. Thanks.
![center](https://user-images.githubusercontent.com/33097033/56591599-ec1e5000-65e0-11e9-9e02-299febc4e65e.PNG)

**Comment by bennothommo** [comment]
@hola56 Apologies, but I still do not understand what you're referring to. There is a "center image" action in your screenshot above. Would you mind giving us more information on exactly where you are not seeing this "center image" action?

**Comment by hola56** [comment]
Hello,
The only options available when you click on an image within a post are Align Left, Align Justify and Align Right - I cannot see the Align Center?

**Comment by bennothommo** [comment]
@hola56 I believe you can use the normal align tool (next to the Italics button) in the main richeditor toolbar to center the image. The one in the image toolbar is used mainly for setting a float direction when you use the "Inline" image style, to allow the text to wrap around the image.
