### ISSUE TITLE
Add featured image from media manager

### ISSUE THREAD

**Issue by sabuz** [rainlab/blog-plugin#433]
Featured image should be inserted from media manager. As a user you may want to reuse featured images, so you should use media manager.

**Comment by bennothommo** [comment]
Hi @sabuz, do you have any thoughts on how this would be implemented, keeping in mind that there's thousands of blog plugin installations already using the file upload widget?

**Comment by sabuz** [comment]
@bennothommo pls check/follow WordPress. Million peoples are using it because of its ease of access!

**Comment by bennothommo** [comment]
@sabuz If you want to see it implemented, please feel free to submit a PR, or alternatively, sponsor the work to be done by the core team.

**Comment by LukeTowers** [comment]
Functionality already exists by using https://octobercms.com/plugin/ictsoft-blogfeaturedfiles

**Comment by drmzio** [comment]
I figured out a trick to do this by writing a custom plugin that adds another field that lets you choose an image from the media manager: https://octobertricks.com/tricks/use-media-manager-for-blog-post-featured-image
