### ISSUE TITLE
Category pages with pagination - unexpected behaviour

### ISSUE THREAD

**Issue by JayFrogster** [rainlab/blog-plugin#435]
When setting up a category page with pagination ("/category/:slug/:page?") the website URL's "break" and there is no more a validation if a category exists.
When removing the ":page?", the validation works and non-existent categories entered manually into the URL will lead to a 404.
With ":slug/:page?" I can manually enter any category name (that doesn't exist), there will be no 404 redirect.

Is this known, or do I have an error in my set up somewhere?

(Sorry, I'm very new to OctoberCMS in general. But I have tried everything I could find about this topic, and it still gives me this behaviour.)

**Comment by bennothommo** [comment]
@JayFrogster It's likely this a scenario that is not handled with the category component currently - there's been a couple of issues reported where there's no handling of missing posts as well (https://github.com/rainlab/blog-plugin/issues/309#issuecomment-489349163 comes to mind). We will review this and get back to you.

**Comment by JayFrogster** [comment]
Related to the problem above, I suspect:

1. Set your home.html up for a post loop.
2. Enable pagination via url =  "/:page?".
3. Type *any* text into the browser URL bar and hit return - there will be no 404 error/redirect.

If you do this on a category page, you can force a 404 redirect. But if you try to implement a forced 404 redirect on the homepage, even the top level page of home ("/") becomes a 404.

**Comment by bennothommo** [comment]
@JayFrogster I dare say at a quick glance, it has something to do with how the system handles optional URL properties - in both instances you specified above, the page property was optional. If you feel up to it, would you be able to see if you can determine the cause and submit a PR?

**Comment by JayFrogster** [comment]
@bennothommo Unfortunately, I'm way to new to October. "Migrated" only 4 days ago from Wordpress to October, I'm still learning just the basics :)
I can try to dig into it, but I doubt I'm much of a help.

You mean this is more of a core code issue, than of the actual Blog plugin?

**Comment by bennothommo** [comment]
@JayFrogster That's fine if you're new - it may be a good learning experience to dive into the core a bit and see how it all works. :) Any contributions or suggestions you can make are very appreciated.

Whilst it might be something to do with the core, it's likely this can just as easily be handled in the component as well.  if you do investigate and it turns out to be a core issue, feel free to submit a PR to the [core October CMS repository](https://github.com/octobercms/october).

**Comment by JayFrogster** [comment]
@bennothommo The recent update did fix the issue on category pages - many thanks!

Unfortunately, the problem persists if the post list is set up on the home page ("/:page?"). Pagination itself works (for example http://mysite/2, http://mysite/3, etc.) but as soon as we have the ":page?" modifier, you can enter any invalid string into the URL - it won't throw a 404.

**Comment by bennothommo** [comment]
@JayFrogster We haven't yet made any changes to the optional parameter, as doing so might break sites which are already using them. I would recommend, as a workaround, using a required parameter for page and setting it up inside a `blog/` URL or something similar, as that's the "official" way of implementing the plugin.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
