### ISSUE TITLE
Problem with /default/ instead of category in all posts

### ISSUE THREAD

**Issue by RCheesley** [rainlab/blog-plugin#437]
This was discovered originally when using a sitemap plugin ( see https://github.com/utopigstudio/octobercms-plugin-seo/issues/2) but apparently it also relates to the all blog posts view, in that the URL is not using the category as would be expected, but instead inserting /default/ in the URL path.

This means that it causes problems with using the all blog posts view but also impacts on the URL's that are generated by sitemap plugins, as they are all using the same way as the all blog posts view to generate the URL structure.

**Comment by bennothommo** [comment]
@RCheesley Thanks for the report. I read through your linked issue as well - just to check, was the "default" slug used at all in any of the categories that you had linked the posts to?

**Comment by RCheesley** [comment]
No, as far as I'm aware we are not using it anywhere in the site setup.
I'll double check as someone else but the site but I've done quite a bit of
work on it and haven't come across it anywhere!

**Comment by bennothommo** [comment]
@RCheesley Thanks for letting us know. We will take a look at it shortly.

**Comment by bennothommo** [comment]
@RCheesley I have looked into this further for you. As you need to select a page with the "blogPost" component to display "all blog posts" in a menu or sitemap, the URLs used in the menu or sitemap will reflect the URL of the selected page, with *only* the blog slug property populated. It will not populate the category slug property as blog posts can belong to more than one category.

This is why the generally recommended URL for the blog posts is "/blog/post/:slug", as this would allow the blog post to be read from multiple categories, and the URL will appear correctly in any menus or sitemaps.

**Comment by mjauvin** [comment]
The way to properly use the blog post page url is to NOT use a category slug but have the category saved in the session when opening a blog post from a blog category page. Here is a sample of my blog category page (blog/category.htm):
```
title = "Blog Category Posts"
url = "/blog/:slug?"
layout = "default"
is_hidden = 0

[blogCategories]
displayEmpty = 0
categoryPage = "blog/category"

[blogPosts]
categoryFilter = "{{ :slug }}"
noPostsMessage = "No posts found"
sortOrder = "published_at desc"
categoryPage = "blog/category"
postPage = "blog/post"
==
function onInit()
{
    Session::put('category', $this->param('slug'));
}
==
```
And here's the Blog Post page (blog/post.htm):
```
title = "Blog Post"
url = "/post/:slug/"
layout = "default"
is_hidden = 0

[blogPost]
slug = "{{ :slug }}"
categoryPage = "blog/category"
==
function onInit()
{
    $this['categorySlug'] = $category = Session::get('category');
}
==
{% set category = categorySlug ? post.categories.where('slug', categorySlug).first %}
{% set prev = blogPost.previousPost %}
{% set next = blogPost.nextPost %}
{% set banner = post.featured_images|first %}
{% set summary = html_clean(post.summary) %}
{% set content = html_clean(post.content) %}
...
```

Hope this helps.

**Comment by bennothommo** [comment]
@mjauvin Not a bad solution, but it is a bit of a hack - `category` in the session is very broad and could conflict with other plugins that might be using the same key.

I believe it's been mentioned by someone else previously, but having a "primary" category that is tied to a blog post might solve this issue better - the blog post can still belong to multiple categories, but the primary one is always included and used in navigation items and sitemaps. The suggestion was that when you create or edit the blog post, the category checkbox list will serve as selecting all categories, but the first one selected is highlighted to indicate the primary category. Clicking another category's name (not the checkbox) would make that the primary category.

**Comment by mjauvin** [comment]
@bennothommo you can use whatever key you want, doesn't have to be "category".

**Comment by bennothommo** [comment]
@mjauvin I get that, I'm just merely commenting on the process of passing session variables directly in the PHP section of pages. Don't get me wrong, it works and it's a good workaround for the moment, but I'd like to investigate a more thorough solution.

**Comment by mjauvin** [comment]
@bennothommo for the sake of discussion, how would you let a blog post page "know" which category was selected when opening a post that has multiple categories (when the category list on the sidebar of the post page must be made active) ?

The only reliable way I found was to use the session to pass that information.

**Comment by bennothommo** [comment]
@mjauvin I'd simply include the category in the URL parameters - ie. `blog/:category/:slug` - and ensure that any links to that blog article, such as those through a BlogList component, reflect the current category. If the category is not available, then I would assume it's the primary category using the idea I mentioned above.
