### ISSUE TITLE
Move to the root category of a post when it is closed

### ISSUE THREAD

**Issue by exaline-ru** [rainlab/blog-plugin#441]
When you turn off the blog post and click on the his link, error 404 will appear. How do I get to the root category of a closed blog in this case?

**Comment by bennothommo** [comment]
Hi @exaline-ru, you have a couple of options:

- Simplest solution is to use a redirection plugin like [this one](https://octobercms.com/plugin/vdlp-redirect) to point the old blog URL to the category root.
- Or, you could make a plugin that will intercept requests to the Blog plugin that are going to unpublished blog posts and handle the redirection from there.
- Or, you could provide a PR for this plugin to allow developers to specify, in the Blog component properties, a URL to redirect to should a blog post not exist or is unpublished.
