### ISSUE TITLE
Category post count is not working correctly sometimes.

### ISSUE THREAD

**Issue by Developer-Nijat** [rainlab/blog-plugin#442]
Category post count is not working correctly sometimes. What is problem? post has been added successfully to category. In category page filter is working fine. everything is working but category post count is not working sometimes both backend and frontend

**Comment by LukeTowers** [comment]
More details please. Replication instructions required too.

**Comment by Developer-Nijat** [comment]
It is bad that such errors are in world-famous CMS.  It's just a simple blog.  Why are there childish mistakes?  Why hasn't  your team fixed by now?

**Comment by Developer-Nijat** [comment]
For example another problem. You can't insert post body start with <body> tag content.

**Comment by bennothommo** [comment]
@Developer-Nijat A better attitude might get the results your asking for.

**Comment by Developer-Nijat** [comment]
I'm afraid to add a new category now that a new error will appear.  Every time I add a new 'plugin', an error appears.  We are obliged to stay in such a situation for a simple blog.  Please check everything well.

**Comment by bennothommo** [comment]
@Developer-Nijat If you want us to investigate, instead of claiming we are making "childish mistakes" and demanding immediate fixes, you could instead help us out by giving us more information on the issue as @LukeTowers asked for initially, including the error messages you are receiving and any steps involved that would allow us to replicate the issue.

**Comment by Developer-Nijat** [comment]
![Screenshot_2019-05-27-06-50-13-211_com android chrome](https://user-images.githubusercontent.com/51002164/58392619-e71f4700-804b-11e9-9cec-daae338eb5ae.png)

**Comment by Developer-Nijat** [comment]
![IMG_20190527_065447](https://user-images.githubusercontent.com/51002164/58392706-5bf28100-804c-11e9-873e-0e16b6c92076.jpg)

**Comment by bennothommo** [comment]
@Developer-Nijat Why are you trying to add a `<body>` tag into a blog post? The body tag is meant to be used the surround the entire HTML contents of a page. Given that blogs are generally inserted into a CMS page, the page should already have a `<body>` tag.

**Comment by Developer-Nijat** [comment]
Dear friend, I have the right to do what I want as a writing. it is just insert bug. What do you think about serialize?

**Comment by Developer-Nijat** [comment]
I have left 'Voyager laravel admin' for such errors.  I decided to use Octobercms.  But I'm looking over here and there are bugs and it makes me sad.

**Comment by bennothommo** [comment]
@Developer-Nijat We do not consider that to be a bug. As per the [Mozilla Developer Docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/body), the only permitted parent tag of a `<body>` tag is `<html>`. The Markdown editor is not the right place to add a `<body>` tag as its meant to be used just for the formatting of content in a blog.

**Comment by LukeTowers** [comment]
@Developer-Nijat try wrapping your HTML code in backticks so that Parsedown doesn't think that it is actual HTML to be parsed.
