### ISSUE TITLE
published_at not converted to correct timezone

### ISSUE THREAD

**Issue by MaTToX3** [rainlab/blog-plugin#445]
Our client just published one of the articles and it was not showing up. Took me a while to realize they selected the time which is two hours after the current UTC time. 

Is it possible that selected time in published_at field is converted to the correct timezone of the app (in my case UTC)?

**Comment by bennothommo** [comment]
@MaTToX3 Do you have any thoughts on how this would work on sites where people are operating on multiple timezones?

**Comment by LukeTowers** [comment]
@MaTToX3 the current behaviour already converts timezones. It converts it from the backend user to the application timezone by default unless `ignoreTimezone: true` is set on the field and column configs for that field. So, the user probably has a preference set for a timezone that is two hours off of UTC and selected the time they thought was correct in UTC but they were actually selecting their local time. 

If you want everyone to be using the field as if it was just straight UTC, then you need to set `ignoreTimezone: true` on it.

**Comment by MaTToX3** [comment]
@LukeTowers Thank you for your response! Indeed, everything works that way, just as you said it. The thing is, when you create a new user for backend, he/she gets assigned a UTC timezone, which means no conversion is made (since system of course assumes that this is already UTC time). So, when I switched my account to +2 time (for my location), the published_at field has indeed convert to UTC.

**Comment by bennothommo** [comment]
@MaTToX3 Probably would be easier to just set the `App.timezone` variable to the +2 timezone if everyone is going to be using that. :)

**Comment by LukeTowers** [comment]
@bennothommo noooooo please don't do that. `app.timezone` should always always be UTC. What you can change however is `cms.backendTimezone`, which is the default timezone that everyone in the backend will use unless they otherwise specify: https://github.com/octobercms/october/blob/master/config/cms.php#L83.

**Comment by bennothommo** [comment]
@LukeTowers indeed you are correct. I forgot about that config variable.

@MaTToX3 please disregard me and use @LukeTowers' suggestion. He is a man of much wisdom.
