### ISSUE TITLE
Error when use of "random" in order list of list component

### ISSUE THREAD

**Issue by cedricdujardin** [rainlab/blog-plugin#448]
I got an error when I use the random option in list component : 

> BadMethodCallException: Call to undefined method October\Rain\Database\QueryBuilder::inRandomOrder() in /home/pirouetta/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2123

**Comment by bennothommo** [comment]
@cedricdujardin We'll need a little more information here. Which component and property are you referring to?

**Comment by cedricdujardin** [comment]
It occurs when I use the [blogPosts] component and set the 'sortOrder' variable to 'random' since the last update.

Here the configuration I use: 
`[blogPost]
slug = "{{ :slug }}"
categoryPage = "category"

[blogPosts]
pageNumber = "{{ :page }}"
categoryFilter = ":category"
postsPerPage = 2
noPostsMessage = "No posts found"
sortOrder = "random"
categoryPage = "article"
postPage = "article"`

I hope it's more helpful !

**Comment by bennothommo** [comment]
Thanks @cedricdujardin. Would you also be able to let us know which build of October you are using?
