### ISSUE TITLE
HTML in Footnotes

### ISSUE THREAD

**Issue by Cameron-Cn** [rainlab/blog-plugin#450]
(Edit: A mighty thanks for the effort here!)
Sorry if this is a duplicate or the wrong github!

It would appear that the footnotes issue remains--displaying HTML code in the footnote itself.
```
Lorem Ipsum dolor.[^1]
----
 [^1]<p>The footnote.&#160;<a href="#fnref1:1" rev="footnote" 
class="footnote-backref">&#8617;</a></p>
 ```

I think this is the bug in question:
   https://github.com/erusev/parsedown-extra/issues/118
Am I right in understanding this is an upstream issue, and we have to wait for a fix?

Or is there anything a PHP newbie like myself could be helpful with in regards to the footnote issue?

**Comment by bennothommo** [comment]
@Cameron-Cn You are correct - it's currently an upstream issue with the ParsedownExtra library. They have released a beta version with this issue fixed, but we can't use that yet. We'd either need to wait for the fix to be made stable, or apply the fix ourselves on a fork.

**Comment by Cameron-Cn** [comment]
Ah, I'll go see if the discussion over there has any hints about it.
There's a messy patch, but I'm not confident enough to implement a beta myself!

Thank you!

**Comment by aurelien-roy** [comment]
0.8.1 is now stable and includes a fix for https://github.com/erusev/parsedown-extra/issues/118

**Comment by LukeTowers** [comment]
@bennothommo are we pulling in that version on composer update or do we need to update our dependencies?

**Comment by bennothommo** [comment]
@LukeTowers yep, I believe the library will bring in the new version through its Composer requirements.

**Comment by bennothommo** [comment]
This should be fixed by running a `composer update` in your site to retrieve the latest version of the Parsedown Extra library. The next build of October will include that as well.
