### ISSUE TITLE
{{ post.content_html | raw }} not working

### ISSUE THREAD

**Issue by J2kwes** [rainlab/blog-plugin#452]
hello,

the content of my post is not showing on the single post page only the info of the post is showing (see the first picture), i dont know the reason of this. i checked in an earlier project of mine and it is working there correctly. can anyone help me?
![afbeelding](https://user-images.githubusercontent.com/31591236/59769762-115cd100-92a7-11e9-8539-47fc7ebb05f6.png)

![afbeelding](https://user-images.githubusercontent.com/31591236/59768646-03a64c00-92a5-11e9-88fe-40241953be34.png)
![afbeelding](https://user-images.githubusercontent.com/31591236/59768715-20db1a80-92a5-11e9-9005-1099637558d0.png)

**Comment by bennothommo** [comment]
@J2kwes the slug property in your `blogPost` component looks wrong - instead of getting the `:slug` from your URL, it just looks like the string `slug`. If you change the `slug` line under `[blogPost]` in your page to be the following, it should hopefully work:
```
slug = "{{ :slug }}"
```
