### ISSUE TITLE
Static menu and "Replace this item with its generated children" does not work properly for blog categories

### ISSUE THREAD

**Issue by zaxbux** [rainlab/blog-plugin#455]
- OctoberCMS Build: 455
- PHP Version: 7.1
- Database Engine: MariaDB
- Plugins Installed: Rainlab.Blog, RainLab.Pages

### Description:
When adding a blog category to a static pages menu and selecting "Allow nested items" and "Replace this item with its generated children" the plugin does not resolve the correct menu items. Siblings of the referenced category are generated, rather than the children replacing a single blog category.

I've narrowed the issue down to this line: https://github.com/rainlab/blog-plugin/blob/816ddb2dd7f4613808e93daf998eaacc9075723f/models/Category.php#L232

The `getNested()` function returns the referenced blog category (and in error, the siblings of that blog category as well).

I've tested this functionality with the static pages plugin and it's pages as a nested menu, and that works correctly.

### Steps To Reproduce:
1. Create two top-level blog categories, each with sub categories (and third-level sub categories if you want).
2. Create a menu in the static pages plugin, adding one of the top-level categories as the reference and checking "Allow nested items" and "Replace this item with its generated children".
3. Add the static pages menu component and view the menu. You'll see the referenced category as well as the sibling category. What should only be seen is the sub-categories that were added to the referenced category.

**Comment by bennothommo** [comment]
@zaxbux Would you be interested in providing a pull request with the fix?

**Comment by zaxbux** [comment]
I'm still having trouble figuring out where/what class/library the `getNested()` function comes from so I can learn more about it (and why it returns unexpected results, or if the issue lies in that function at all). So far, the only information in the October CMS docs is this:

https://github.com/octobercms/library/blob/9d066e184b41ffa3429346f0b50790d4e2eaaaa4/src/Database/Traits/NestedTree.php#L55

"returns a collection of results" isn't much to go off of.

**Comment by bennothommo** [comment]
@zaxbux You probably won't need to do anything to the `getNested` call - that is doing what it is supposed to. You would instead need to look into this code block just above it:
https://github.com/rainlab/blog-plugin/blob/816ddb2dd7f4613808e93daf998eaacc9075723f/models/Category.php#L227-L229
That is what assigns the parent category into the items list. I would imagine a fix would check to see if the `$item` menu item variable has the `replace` property set to true, if so, it should not include that parent category in the results.

**Comment by zaxbux** [comment]
My question still remains, what exactly is `getNested()` supposed to do? I don't feel comfortable implementing a fix without more information.

**Comment by bennothommo** [comment]
@zaxbux `getNested` is part of the `NestedTree` trait, which is basically an implementation of the [nested set model](https://en.wikipedia.org/wiki/Nested_set_model) of storing hierarchical data. That particular method gets an array of all categories that are a descendant of the selected category, nested by level. The `children` property starts a new loop as categories could be many levels deep.

**Comment by zaxbux** [comment]
This is where I'm thinking that the issue is with `getNested()`, as you've said it it supposed to return descendants, but it is not doing that. When that method is called, it is returning the selected category and it's sibling categories.

For example, what you're describing is that when the green category is selected as the reference, only the categories in blue will be returned. However, this is not the case, as the categories in red are not descendants but are also returned by `getNested()` and included in the menu:
 
![october_categories](https://user-images.githubusercontent.com/5186921/60475286-7c08f780-9c2b-11e9-95e8-f0d9ac7fabb6.png) 

Here are my menu settings in case they make a difference:
![october_menu_settings](https://user-images.githubusercontent.com/5186921/60475287-7c08f780-9c2b-11e9-8680-77c230bf2e68.png)

**Comment by bennothommo** [comment]
@zaxbux Can you show us a screenshot of the nav on the front-end where this is occurring?

**Comment by zaxbux** [comment]
Screenshot:
![october_nav_example](https://user-images.githubusercontent.com/5186921/60476267-ca1ffa00-9c2f-11e9-93a5-d9cec22fe417.png)

Here's the HTML generated by the default `staticMenu` component:
```html
<ul>
    <li role="presentation" class="  ">
        <a href="/blog/second-2">Second</a>
    </li>
    <li role="presentation" class="  ">
        <a href="/blog/first">First</a>
        <ul>
            <li role="presentation" class="  ">
                <a href="/blog/sub">Sub</a>
                <ul>
                    <li role="presentation" class="  ">
                        <a href="/blog/sub-2">Sub 2</a>
                    </li>
                </ul>
            </li>
        </ul>
    </li>
    <li role="presentation" class="  ">
        <a href="/blog/uncategorized">Uncategorized</a>
    </li>
</ul>
```

**Comment by bennothommo** [comment]
@zaxbux Thanks for that. I've not yet been able to confirm this myself, but if your screenshot above is definitely from the menu settings you posted earlier, then yes there is an issue here. If you have found a fix for it, please feel free to submit it.

**Comment by zaxbux** [comment]
I have still been unable to find the source file where `getNested()` is defined, so I am unable to provide a fix.

**Comment by LukeTowers** [comment]
https://github.com/octobercms/library/blob/master/src/Database/Traits/SimpleTree.php#L136
https://github.com/octobercms/library/blob/master/src/Database/Traits/NestedTree.php#L494
