### ISSUE TITLE
Custom Components and Sitemap plugin

### ISSUE THREAD

**Issue by phpMagpie** [rainlab/blog-plugin#456]
We've taken on an existing website which is using rainlab's blog and sitemap plugins.  

It looks like some custom development has been done registering a custom `BlogPostComponent::class => 'blogPostDetail'` and `BlogListingComponent::class => 'blogPostListing'`.

This is stopping the `Post::getMenuTypeInfo($type)` and `Post::resolveMenuItem($item, $url, $theme)` from working as they are expecting different component names, which is in turn stopping 'All blog posts' from working in the sitemap.

Any idea how I get these custom components working nicely with the sitemap plugin?

**Comment by LukeTowers** [comment]
@phpMagpie you could try setting those component's aliases to `blogPost` and `blogPosts` (not sure that'd work though), or you can extend the Post model with your own model, override those methods to look for your custom components, and then add your own event listeners  (https://github.com/rainlab/blog-plugin/blob/master/Plugin.php#L154-L170) to resolve using your custom Post model by subscribing to the events with a higher priority (https://octobercms.com/docs/services/events#subscribing-priority)

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
