### ISSUE TITLE
Parsedown Extra functionality

### ISSUE THREAD

**Issue by willstocks** [rainlab/blog-plugin#457]
Hi guys,

It is my understanding that OctoberCMS includes Parsedown Extra as standard, however when I try to add a code block such as: 

```markdown
  ```{.language-php .line-numbers}
    function thisisatest($var) {
      return $var;
    }
  ``` .
```

Which would in theory therefore add the `language-php` and `line-numbers` classes to my output `pre`/`code` block. However this doesn't appear to be the case, the output HTML is instead as follows:

```html
<pre class="language-php">
  <code class="language-{. language-php">
    function thisisatest($var) {
      return $var;
    }
  </code>
</pre>
```

As you can see, the main bit (on the `<code class=`) is incorrect and not pulling through the second class (`.line-numbers`) and I therefore have to write out the HTML manually instead.

Any ideas?

**Comment by LukeTowers** [comment]
@willstocks-tech didn't even realize this was a feature, could you link to the docs for it?

**Comment by willstocks-tech** [comment]
@LukeTowers I’ll grab the links from my laptop as soon as I can, probs tomorrow now. But one I do have to hand: https://octobercms.com/docs/api/october/rain/parse/parsedown/parsedown

And

https://michelf.ca/projects/php-markdown/extra/

**Comment by willstocks-tech** [comment]
The latter is included in https://github.com/erusev/parsedown-extra which is included in October by default apparently - there’s a demo on there so you can play with outputs

**Comment by LukeTowers** [comment]
@willstocks-tech hmm, might be an issue with the library we use, just tried your example on https://parsedown.org/extra/ and it didn't work.

**Comment by willstocks-tech** [comment]
😧 ok, let me dig out those links and I’ll send them over tomorrow! I had a
working example earlier too

The only reason I found out it was possible was due to a couple of
blogs/forum posts I had found detailing it (it was annoying me having to
manually build out the pre/code structure rather than just using the
backticks... then apparently the lib is baked in to October 🤯)

**Comment by willstocks-tech** [comment]
@LukeTowers - so I've been looking at this (first chance I've had!) and I've found:
- https://github.com/erusev/parsedown-extra/issues/56
- https://github.com/erusev/parsedown-extra/issues/112

So it looks like, for some reason, in Parsedown Extra there is a bug that prevents classes being correctly added to code blocks, which is annoying! Apparently, this feature works in Markdown Extra (which Parsedown Extra is supposed to bring to Parsedown) :(

**Comment by bennothommo** [comment]
@willstocks-tech We'll need to wait for Parsedown Extra to fix it up on their end - it looks like they are doing so shortly.

**Comment by daftspunk** [comment]
Looks like this feature is unavailable until the referenced issues in the vendor lib are sorted
