### ISSUE TITLE
Post URLs Defaulting to /default After 1.3.2 Update

### ISSUE THREAD

**Issue by srsgores** [rainlab/blog-plugin#458]
There's a breaking change in [the 1.3.2 update](https://github.com/rainlab/blog-plugin/compare/v1.3.2...master), which causes existing usages of `{{post.url}}` to all resolve to `/post/default` as opposed to `/post/:slug`.  This only happens after upgrading from 1.3.1 to 1.3.2.

Reporting this, as it is a breaking change.  Unsure of the solution at this point and will update once the responsible code is found.

**Comment by daftspunk** [comment]
This should have been rolled back in 950fbd7b1e6a0ad8d1c0277027fe3ed7c8e12091. @srsgores if it is still an issue, please ping me and we can revisit
