### ISSUE TITLE
Calling particular single post title and description in pages.

### ISSUE THREAD

**Issue by balochlens** [rainlab/blog-plugin#459]
I have 100 of posts in my blog, while I am trying to create accordion of posts using UIKit-3. 
After tiring by googling, I am posting here. 
How to get the title and description of specific post in pages.
```
<h3> title of specific post </h3>
<p> description of particular post </p>
```

**Comment by w20k** [comment]
You could download theme and look how it's done: https://octobercms.com/theme/jimmyhung-october-canvas-blog

Probably this way, haven't used blog for a while :)
```
<h3>{{ post.title }}</h3>
<p>{{ post.content_html | raw }}</p>
```

**Comment by balochlens** [comment]
@w20k Thanks for your quick reply, unfortunately, this has not resolved my issue.

**Comment by w20k** [comment]
@balochlens could you show your code then?

**Comment by balochlens** [comment]
Here it is.

```
<section class="uk-section uk-section-default">
    <div class="uk-container">    
        <header>
            <h1 class="uk-heading-primary">Courses</h1>
        </header>
        <div> 
      {% for post in blogPost%}
    <div class="uk-container">
    <ul uk-accordion="collapsible: false">
    <li>
        <a class="uk-accordion-title" href="#">{{ post.title }}<</a>
        <div class="uk-accordion-content">
            <p>{{ post.summary }}</p>
        </div>
    </li>
 
</ul>  
    </div>
    {% endfor %}

 
         </div>
    </div>
</section>
```

**Comment by rubenvanerk** [comment]
@balochlens I think you should use the variable name `posts` instead of `blogPost`

**Comment by balochlens** [comment]
@rubenvanerk  Thanks It has bee solved accordingly.
