### ISSUE TITLE
Categories page shows Exception

### ISSUE THREAD

**Issue by mosid** [rainlab/blog-plugin#46]
when navigating to blog/categories i got the following:
![screenshot from 2015-01-11 18 22 06](https://cloud.githubusercontent.com/assets/5040354/5695658/ea17dfbc-99be-11e4-9ea0-4bc5eed1b28c.png)

october build 174 on postgresql9.3 php5 apache

**Comment by mosid** [comment]
upgrading to build 177 solved the issue

**Comment by mosid** [comment]
@daftspunk  The method `RainLab\Blog\Models\Category::getPostCountAttribute()` in line 39 looks like this
` public function getPostCountAttribute()
    {
        return $this->posts()->count();
    }`

it should be like this `  public function getPostCountAttribute()
    {
        return $this->posts->count();
    }`

**Comment by mosid** [comment]
Sorry closed the issue by accident

**Comment by daftspunk** [comment]
Could this be a bug in Laravel? I think the ORDER component of this query is redundant when counting records.

**Comment by mosid** [comment]
How about adding a groupBy published_at in the original query?
