### ISSUE TITLE
[Question] Is there a simple way to add a class to an individual post on the post listing (almost like a post-type)?

### ISSUE THREAD

**Issue by willstocks** [rainlab/blog-plugin#460]
So to explain my question a bit better:

In a post-list, I get my standard list of posts:
```html
<div class="individual-post post-1">...</div>
<div class="individual-post post-2">...</div>
<div class="individual-post post-3">...</div>
```

But let's say one of those posts is a "sponsored post" and I wanted a clear way to style it, or do something else with it on that listing page, is there a simple way for me to add a class to that post for the post listing?

I thought about trying something along the lines of:

```twig
{% if "sponsored" in post.categories %}
<div class="individual-post post-{{post.id}} sponsored" >
{% else %}
<div class="individual-post post-{{post.id}}" >
{% endif %}
```

But it didn't feel quite right (and my October skills are still super limited at the moment... I'm still on a learning curve). Is there a clean/right way for me to do something like this?

**Comment by bennothommo** [comment]
@willstocks That's pretty much the only way to do it that does not involve using a third-party plugin or writing your own plugin to extend the Blog form to add a sponsored field in. There are plugins available that add features like tags that you could leverage for this as well. (eg: https://octobercms.com/plugin/rahman-blogtags)

I hope that helps! :)

**Comment by LukeTowers** [comment]
@willstocks that looks fine. I would probably do it like
```twig
<div class="individual-post post-{{post.id}} {% if "sponsored" in post.categories %}sponsored{% endif %}">
```
or if it got super complicated with lots of conditions use twig macros to generate the classes but overall that's fine.

**Comment by willstocks** [comment]
I quite like that approach - fewer lines and still as readable imo! Thanks!

> use twig macros

Ooh, I’ll have a look into that as had never heard of it! Any good
links/resources I could look at?

**Comment by LukeTowers** [comment]
https://twig.symfony.com/doc/2.x/tags/macro.html and https://github.com/luketowers/oc-blank-theme/blob/master/partials/tmpl/featured-image.htm as an example
