### ISSUE TITLE
how to custom category list and show featured image category

### ISSUE THREAD

**Issue by Alpa86** [rainlab/blog-plugin#461]
<div class="row">
      {% if blogCategories.categories|length > 0 %}
      <div class="col col-lg-6 col-12 mb-3 mb-lg-5">
        <div class="wrapper-feature-card">
          <a href="#" class="img-hover img-hover-primary">
            {% for category in post.categories %}
            {% if category.featured_images.count %}
            {% for image in category.featured_images %}
            <img src="{{ image.path }}" alt="{{ image.file_name }}"/>
            {% endfor %}
            {% endif %}
            {% endfor %}
          </a>
          <div class="feature-content">
            <h4>
              {% partial blogCategories ~ "::items"
              categories = blogCategories.categories
              currentCategorySlug = blogCategories.currentCategorySlug
              %}
            </h4>
            <p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown <br>
              printer took a galley of type.</p><a href="#">selengkapnya&nbsp;&nbsp;<i
            class="fa fa-long-arrow-alt-right"></i></a></div>
        </div>
      </div>
      {% else %}
      <p>No categories were found.</p>
      {% endif %}
    </div>

**Comment by LukeTowers** [comment]
I'm assuming this was solved?
