### ISSUE TITLE
Exception in blog post

### ISSUE THREAD

**Issue by alancunnane** [rainlab/blog-plugin#468]
We have just begun to have issues with our blog; when clicking on the link from the main blog page, it returns the message

Type error: Argument 2 passed to RainLab\Blog\Classes\ComponentAbstract::getComponent() must be of the type string, null given, called in /var/www/html/plugins/rainlab/blog/components/Post.php on line 108
/var/www/html/plugins/rainlab/blog/classes/ComponentAbstract.php line 28

This has only happened in the past day or so; I updated October and plugins using the dashboard settings panel last week, but it seems to have happened a few days after that, in any case.

Apparently the categoryPage value being passed through is null, although I can't see how that can be the case. Changing category hasn't helped.

Any assistance will be greatly appreciated - thanks!

Alan Cunnane

**Comment by bennothommo** [comment]
@alancunnane Would you mind providing us with a full backtrace if possible, as well as the code of the page for your main blog page and the page that displays the blog post itself?

**Comment by alancunnane** [comment]
[stacktrace.txt](https://github.com/rainlab/blog-plugin/files/3656307/stacktrace.txt)

[synthetixDOTcom.zip](https://github.com/rainlab/blog-plugin/files/3656425/synthetixDOTcom.zip)

I think these files cover it - let me know if you need more.  Been a while since we put this in place!

**Comment by alancunnane** [comment]
I've remedied this for the time being, by uploading an older version of the plugin (1.2.19) to the server.  Obviously only a temporary solution, as it means I can't install any updates.

Thanks,
Alan

**Comment by w20k** [comment]
@alancunnane have you used the latest version or which one was it, that triggered exception?

**Comment by alancunnane** [comment]
I'm not entirely sure of the version number; I carried out the update around mid-September, if that helps.

**Comment by bennothommo** [comment]
@alancunnane This should be fixed by https://github.com/rainlab/blog-plugin/pull/487.
