### ISSUE TITLE
Verify category slug in URL, else redirect to 'canonical'

### ISSUE THREAD

**Issue by pavsid** [rainlab/blog-plugin#472]
I noticed recently that if the blog post page url is of the format `/blog/:category/:slug` then the post is retrieved and displayed regardless of whether the correct category slug has been entered in the URL.

In my case, this has led to a load of duplicate content being crawled by search engines, and so I believe, if supplied, the category slug in the URL should be verified, and if not valid, a redirect to the correct URL sent.

Quite a simple fix, and works with translations too...

```
if($post->categories->count() && $this->param('category')) {

    if(false === $post->categories->pluck('slug')->search($this->param('category'))) {
        $canonicalUrl = $this->controller->pageUrl($this->page->baseFilename, [
            'category' => $post->categories[0]->slug,
            'slug' => $post->slug
        ]);
        return response()->redirectTo($canonicalUrl)->send();
    }
}
```

Note that this relies on the category param in the page URL definition being `:category`.

Can do PR if you want?

**Comment by bennothommo** [comment]
@pavsid I'll be happy to take a look at a PR. :)

**Comment by w20k** [comment]
@pavsid the same here! Would be awesome to peer review your PR 😄

**Comment by pavsid** [comment]
Here you go, hope it helps - https://github.com/rainlab/blog-plugin/pull/475

**Comment by daftspunk** [comment]
The Post component doesn't support the route `/blog/:category/:slug` natively. However, you could implement something similar in your PHP code to prevent the duplicated content. I've made a note to look at introducing this functionality in the next iteration of the blog featureset

Add to blog post page

```
function onStart()
{
    if($this->post->categories->count() && $this->param('category')) {

        if(false === $this->post->categories->pluck('slug')->search($this->param('category'))) {
            $canonicalUrl = $this->pageUrl($this->page->baseFilename, [
                'category' => $this->post->categories[0]->slug,
                'slug' => $post->slug
            ]);
            return response()->redirectTo($canonicalUrl)->send();
        }
    }
}
```

Thanks!
