### ISSUE TITLE
Posts bulk import from external source. Suggestion and improvement

### ISSUE THREAD

**Issue by queengab** [rainlab/blog-plugin#474]
Hi,

I'm Gabriele. We taled sometime no slack. Today i write an issue directly here about a problem that occurs today after a bulk import on rainlab.blog.

I describe all my steps:
1) My buddy created a python script scrape articles and import them to a csv for rainlab.blog import.
2) I imported all posts with the csv file. And match the content column with html content
3) We noticed after import that no posts on the blog backend was pubblished
4) Following @LukeTowers suggestion on slack, we launched a simple query to update the colum pubblished 
5) Then we noticed that not saved posts don't show all the post text, cause, during the import procedure, we have filled only html content column and not content column so html content on db have all "mark upped" text correctly and content have onlt the first text paragraph for the imported post.  During the import phase we matched content column with html content column 

![immagine](https://user-images.githubusercontent.com/9084695/66388427-6479a180-e9c6-11e9-9570-78b5e3ae9762.png)

We know that this import and export feature were designed from rainlab.blog to rainlab blog but it could be useful if:
1) We add a "pubblish all" button to select and pubblish all posts from rainlab blog backend interface.
2) We create a button to automically fill content and html content fileds
3) We have the opportunity to extend the right window database fields, during the import process, and add custom fileds that matched with file columns of csv. Example. We have extended rainlab blog with a featured image filed, but we can't match a featured image fileld with nothing.

Don't konw if someone felt the need for these functionalities but will be good.

Bye!

**Comment by daftspunk** [comment]
It looks like this would be best handled with some custom PHP code, or a custom importer plugin. We hope to have features like this introduced in a later release. If you need help writing an importer plugin, feel free to reach out. Thanks for your feedback
