### ISSUE TITLE
Allow Wordpress-style blog post URLs

### ISSUE THREAD

**Issue by queengab** [rainlab/blog-plugin#479]
Hi,

trying to find a definitive solution to improve SEO for my blog pages i've encoured several problems.

My temporary solution to improve my seo is:

Create a single page

 `/notizie`

With standard `blogPostList`
```
title = "Notizie"
url = "/notizie"
layout = "internalBlog"
is_hidden = 0
robot_index = "index"
robot_follow = "follow"

[blogPosts blogPosts_grid]
pageNumber = "{{ :page }}"
categoryFilter = "notizie"
postsPerPage = 10
noPostsMessage = "No posts found"
sortOrder = "published_at desc"
categoryPage = "categorienotizie"
postPage = "notizia"
```

Then 
a category page
`/categoria` 

```
Title = "categorieNotizie"
url = "/notizie/:category/:page?"
layout = "internalBlog"
is_hidden = 0
robot_index = "index"
robot_follow = "follow"

[blogCategories]
slug = "{{ :category }}"
displayEmpty = 0
categoryPage = "categorienotizie"

[blogPosts blogPosts_grid]
pageNumber = "{{ :page }}"
categoryFilter = "{{ :category }}"
postsPerPage = 9
noPostsMessage = "No posts found"
sortOrder = "published_at desc"
categoryPage = "categorienotizie"
postPage = "notizia"
```
A single post page:

```
title = "notizia"
url = "/notizie/:category/notizia/:slug"
layout = "internalBlog"
is_hidden = 0
robot_index = "index"
robot_follow = "follow"

[blogCategories]
slug = "{{ :category }}"
displayEmpty = 0
categoryPage = "categorienotizie"

```

With this configuration i have correct pagination on category pages:
example: `/notizie/2019/2`

and a post page `/notizie/2019/notizia/comunicato-del-tavolo-asilo-nazionale-su-mare-jonio`

When i use railab.sitemap perhaps the plugin print on xml file this url for a single post:
`/notizie/default/notizia/accesso-agli-atti-e-ricorso-contro-ufficio-immigrazione-questura-di-roma-per-mancato-rinnovo-dei-permessi-di-soggiorno-il-commento-di-francesco-portoghese-di-a-buon-diritto`

1) i'd like to have on my sitemap the correct url i've generated
2) i'd like finally to find a standard and defnitive solution to create sort of wordpress permalink 
for my blog posts.
I know we are working with rest API and we need a page and parameter to print post but i think is essential to find a collaborative solution.

**For example**
A category page with url `news/2019/page1.... `
And a single post url with url `/notizie/2019/postslug `or `notizie/2019-10-25/postslug`

_For this case TimFoster on slack channel suggest me to use:_
`/bla/:slug` `/bla/:category/:page`
but 'd like to reach my goal.

After seeing this: https://www.youtube.com/watch?v=sZXdruO2ac8
I tried to arrive it via twig:

When i cycle my post i inserte it
```
<h3>
       <a href="{{ 'notizia'|page({ post: post.slug[0].slug, slug: post.slug }) }}">
            {{ post.title }}
       </a>
</h3>
```

But how to cycles categories and add pagination?

```
{% for categories in post.categories %}
 <a href="/notizie/{{ categories: childcategories.slug, pagination }}">{{ genre.genre_title }}</a><br />
{% endfor %}
```

Don't know the best way is to go by create a `routes.php`  file but i don't know how to manage it. Anyway maybe if we find 3-4 cases of good url we can make a plugin that extend blog.

I think is a very important SEO feature if we want to spread October CMS and give a signal to many wordpresser frustrate users :)

Thanks anyway!
Bye
Gabriele

**Comment by bennothommo** [comment]
@queengab The issue where the URL used "default" for the category in the Sitemap is a known issue, see here: https://github.com/rainlab/blog-plugin/issues/458.

With regards to your query about setting up URLs like Wordpress, you will need to include the category parameter in the URL somehow if you would like the current category to be selected in your blog page, but you can make the URL for the page that will display your blog post like the following:

`/blog/:date/:category/:slug`

And populate the `date` parameter with the post date when you create the links to the blog posts. Even though the `date` parameter is populated, you do not have to use when loading the post as the Post component only uses the `slug` parameter to determine the correct blog post.

**Comment by queengab** [comment]
Hi @bennothommo ,

thanks i will try. But i have to wait first to forward my sitemap.xml to google until the sitemap url problem is resolved. I'd never want a urls duplication for oogle, one with default and one with the year.

Thanks for support and your response. I will post my solution!
