### ISSUE TITLE
Problem with "published date" selector

### ISSUE THREAD

**Issue by WebShapedBiz** [rainlab/blog-plugin#481]
Hi.
I've created an admin user for my client, to create blog posts, with "Publisher" role and only these permissions allowed:
![Slika zaslona s 2019-10-21 18-16-10](https://user-images.githubusercontent.com/6765137/67223451-8f84dc00-f42f-11e9-9064-7e895455b066.png)

Now my client has an issue with the "Published date" selector - it doesn't work. It seems that that new user doesn't have permission to load `storm-min.js`:
![Slika zaslona s 2019-10-21 18-18-18](https://user-images.githubusercontent.com/6765137/67223624-e2f72a00-f42f-11e9-920b-cefe2c331fa2.png)

When I log in, as a super admin, everything works and there is no error message in the console. OK, `navigator.serviceWorker error` is there and I don't know what it is, but it's not in the way and it does not affect date selector.

Thank you for your time and effort.

Cheers.

**Comment by WebShapedBiz** [comment]
UPDATE:
Even adding the superuser rights to my Publisher administrator I cannot get a "published date" selector to work, and this is making my client angry as hell since I'm doing all the publishing at the moment.
What is interesting that when I'm impersonating this Publisher administrator, everything works fine.

Could somebody please at least share some ideas about this issue?

**Comment by bennothommo** [comment]
@WebShapedBiz can you try run `php artisan october:util compile assets` in your command line where the site is hosted, and see if that makes a difference?

**Comment by WebShapedBiz** [comment]
Thank you so much @bennothommo for your reply. Unfortunately, nothing has changed. It seems that Pikaday has an issue with i18n (see my screenshot with an error). I can create a more elaborate screencast with this issue. I also observed that there are some issues reported on GitHub regarding 
Pikaday and i18n on some other projects.

To recapitulate:
1. The latest version of OctoberCMS and all plugins, on 30th October 2019.
2. Primary language EN and another HR (Croatian) which is **not added as a backend language** in CMS nor any plugin, only as a **second site language via Translate plugin**.
3. Rainlab Blog plugin and Sensit BlogDisplayDate plugin as an extension of Rainlab Blog, adding another date field that I use for event announcements.
4. **Only me** as an installation creator and first admin/superuser **can see both dates selectors** (date published and another date from BlogDisplayDate plugin) when creating or editing blog posts.
5. **I cannot create any type of user with any permissions/groups setup that could see the date selectors in a blog post.**
6. I and all other users **can see** the time selector in Date Published, which again points to Pikaday and i18n issue since time selector doesn't use i18n, as I can understand.
7. **If I impersonate any other user I can see the date selector, no issues whatsoever**.

Please help me out here with this puzzling issue.

**Comment by LukeTowers** [comment]
@bennothommo @WebShapedBiz is this because the Translate plugin is setting the locale to HR (Croatian), which might not exist as a backend locale? @WebShapedBiz if you use the account of the client and set their backend preference to use the english locale does that resolve the issue?

**Comment by WebShapedBiz** [comment]
Thank you @LukeTowers for joining in.
The backend preference was never changed from the English locale, but I was thinking that this may be the reason behind the issue, so I've copied `lang.php` file from `en` folder to `hr` folder in both CMS and Blog plugin to try to "fool" the system to think there is a Croatian locale, while leaving the backend locale to English.
It didn't work. It's so frustrating because I cannot see the logic behind it. It works for impersonated users but not for actual logged-in user :-(

**Comment by LukeTowers** [comment]
@WebShapedBiz check the value of app.locale, users should be defaulting to that: https://github.com/octobercms/october/blob/master/config/app.php#L78. The backend locale shouldn't have to be set on a user unless it's going to be different from the main one.

**Comment by WebShapedBiz** [comment]
This was my app.locale:
```/*
    |--------------------------------------------------------------------------
    | Application Locale Configuration
    |--------------------------------------------------------------------------
    |
    | The application locale determines the default locale that will be used
    | by the translation service provider. You are free to set this value
    | to any of the locales which will be supported by the application.
    |
    */

    'locale' => 'hr',

    /*
    |--------------------------------------------------------------------------
    | Application Fallback Locale
    |--------------------------------------------------------------------------
    |
    | The fallback locale determines the locale to use when the current one
    | is not available. You may change the value to correspond to any of
    | the language folders that are provided through your application.
    |
    */

    'fallback_locale' => 'en',
```

Was that where I've scr***d up?

**Comment by LukeTowers** [comment]
@WebShapedBiz yup. If hr doesn't exist as a locale in October then you shouldn't be setting it there. Set it to en instead, the translation plugin will still work.
