### ISSUE TITLE
Is there a way to customize the backend forms and lists?

### ISSUE THREAD

**Issue by RomainMazB** [rainlab/blog-plugin#485]
Hi,

I love this plugin, but I want to change some stuff to make it more user-friendly. Such as the checkbox "Published" which I want to be checked as default and with the "Publish on" field I want to fill with now(). And so on with some other modifications (list posts with a kind of tiles instead of a table for example).

So I need to customize the backend lists and forms of the blog plugin.

I looked in the docs of both OctoberCMS Rainlab.Blog but I didn't find any way to do it without modifying the plugin's source code.

For example, I tried to listen to the core backend.list.extendColumns event, with a filter to target Blog/Posts lists:
```PHP
<?php namespace RomainMazB\BlogExtend;

use System\Classes\PluginBase;
use Event;

class Plugin extends PluginBase
{
    public function boot()
    {
        Event::listen('backend.list.extendColumns', function($list) {
            if (!$list->getController() instanceof \RainLab\Blog\Controllers\Posts) {
                return;
            }
            $list->customViewPath = plugins_path().'/romainmazb/blogextend/views/posts/index.htm';
        });
    }
}
```
But the list is still rendered with the default partials.

Is there a proper way to accomplish what I want? Does the plugin fire some event before render lists and forms in the backend? (I searched that way too but didn't find anything)

**Comment by bennothommo** [comment]
@RomainMazB What sort of modifications are you looking to achieve? The main two events you want to listen to are `backend.list.extendColumns` and `backend.form.extendFields` - however, I don't believe you can change the view path from these events.

**Comment by LukeTowers** [comment]
@RomainMazB @bennothommo the System\Traits\ViewMaker trait that is used by all widgets actually provides a way for you to accomplish this.

```php
<?php namespace RomainMazB\BlogExtend;

use System\Classes\PluginBase;
use Event;

class Plugin extends PluginBase
{
    public function boot()
    {
        Event::listen('backend.list.extendColumns', function($list) {
            if (!$list->getController() instanceof \RainLab\Blog\Controllers\Posts) {
                return;
            }
            $list->addViewPath('$/romainmazb/blogextend/views/posts');
        });
    }
}
```

Now all you have to do is copy over the partials you want to modify from /backend/widgets/lists/partials into /plugins/romainmazb/blogextend/views/posts/ and modify them as desired (keeping the same filename) and the Lists widget will use those partials instead. Same goes for the Form widget as well.
