### ISSUE TITLE
Validation errors not showing

### ISSUE THREAD

**Issue by mplodowski** [rainlab/blog-plugin#486]
1. Create new Post.
2. Enter post title.
3. Try to leave page and you will receive confirmation message about leaving page. Click "Cancel".
4. Click "Save" button.
5. Nothing happens, no validation error is showing up.

You should receive validation error: "The content field is required.".

Blog version: 1.3.5
October: 459

**Comment by daftspunk** [comment]
I could replicate this but couldn't trace it. Mystery 🤷 

Seems to happen in the framework.js or flash message JS, added a note to revisit it when we look at these tools

Thanks
