### ISSUE TITLE
Support Shortcode?

### ISSUE THREAD

**Issue by nycparking** [rainlab/blog-plugin#488]
Hello,

I am working on a project which requires me to use the blog plugin, but I noticed there isn't a way for me to add a shortcode (change the editor to add codes) in the blog content area.

Is there a way I could work around this?

i am also using the custom fields plugin to insert the shortcode.
https://octobercms.com/plugin/pkurg-customfields

**Comment by LukeTowers** [comment]
@nycparking October doesn't have "shortcodes", so I have no idea what you're talking about.

**Comment by drmzio** [comment]
I'm actually working on a shortcode plugin right now. I'll ping this issue when it's available 👍 

Blog Shortcodes demo |
--- |
![](https://cl.ly/c8fa8f1bb24d/Image%2525202019-11-21%252520at%25252010.57.50%252520PM.jpg) |

**Comment by LukeTowers** [comment]
@drmzio is that going to be matching shortcodes to components?

**Comment by drmzio** [comment]
@LukeTowers Not sure I quite understand, but it pull from your theme's partials

**Comment by LukeTowers** [comment]
@drmzio I mean will it allow you to pull in a component? Say you have a `forms` component, would you be able to do `[forms form=contact]`?

**Comment by drmzio** [comment]
@LukeTowers Haven't really thought about using components yet. All it does is pull a custom partial from your theme and renders it on the blog post, then saves the rendered partial into the blog `content_html` column.

It's still a very early work in progress, but here are the steps:

1. Register shortcode name (e.g. `[youtube-embed]`)
2. Create the partial under the `partials/shortcodes` theme directory (e.g. `partials/shortcodes/youtube-embed.htm`)
3. Add your custom HTML data to the partial (e.g. The youtube embed code would go here)
4. Call the shortcode in the blog post editor (e.g. `[youtube-embed]` would render the youtube embed code from the partial)
5. On save, only the rendered partial code gets stored in the DB Blog plugin column `content_html`

You can pass arguments like `video="xxx"` or `name="John"` to reuse a shortcode in many ways. See https://github.com/thunderer/Shortcode for more on what can be done with shortcodes.

**Comment by nycparking** [comment]
@drmzio This is great, this is what I actually needed a few days ago, but I went ahead and found a developer to get it done for me.

But I think a lot of people would find this useful.
