### ISSUE TITLE
Category name in the url causing problem

### ISSUE THREAD

**Issue by farhanianz** [rainlab/blog-plugin#490]
### Goals
1. all posts list + category list (sidebar) on /blog
2. all posts list of specific category on /blog/category-name
3. read the post on /blog/category-name/post-title

### Steps to reproduce:
1. edit the blog posts list page url to: /blog/:page?
2. edit the blog posts list in a specific category page url to: /blog/:category/:page?
3. edit the blog post view (viewing single post) page url to: /blog/:category/:slug

**Adapt the components accordingly, you can use rainlab-vanilla theme.**

### Problems:
1. none
2. issues: 
    posts list of specific category is not showing
    instead, posts list of all category is showing
    _workaround:_ adding :page param. works properly: /blog/category-name/1
   so this is messing up with other pages, I guess, it is not able to isolate the pages.
3. issues:
    It still shows the all posts list of all category
    Not able to fix with this url structure.
    I've tried this one:

        {% if this.param.category and not this.param.slug %}
            {# configured to show category specific posts: not works. shows all posts of all categories #}
        {% else %}
            {# configured to show the post, nothing happened. shows all posts of all categories  #}

### Urgently need a fix with this kind of url structure, kindly response soon.

Regards.

**Comment by LukeTowers** [comment]
@farhanianz if you need support urgently, consider signing up for our Premium Support program: https://octobercms.com/premium-support

**Comment by farhanianz** [comment]
Since then, any fix? Does anyone have a solution? I'm quite new in oc.

**Comment by LukeTowers** [comment]
Try asking the community on the forums, otherwise if you need urgent support consider signing up for our Premium Support program: https://octobercms.com/premium-support. Non priority support program issues are dealt with as we have the time to get around to doing so as that is offered for free.

**Comment by bennothommo** [comment]
@farhanianz Which component are you using for the specific category pages?

**Comment by cjkpl** [comment]
The solution which worked for me had been posted several years ago here: [https://octobercms.com/forum/post/blog-categories-dont-work](https://octobercms.com/forum/post/blog-categories-dont-work).

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
