### ISSUE TITLE
Cannot show category name as title of the page

### ISSUE THREAD

**Issue by enricoeur** [rainlab/blog-plugin#491]
Simply this code on your guide doesn't work:

       $this->page->title = $this->category->name;

I get error of null object.

**Comment by LukeTowers** [comment]
@enricoeur what was the solution?

**Comment by bennothommo** [comment]
@LukeTowers might've been changing it to the following:
```php
$this->page['title'] = $this->category->name;
```

**Comment by LukeTowers** [comment]
hmm, weird.
