### ISSUE TITLE
Category Filter returns all post when no match

### ISSUE THREAD

**Issue by setianke** [rainlab/blog-plugin#496]
The category filter works correctly when accessing an existing/correct slug but when accessing a not existing slug the "blogPosts" Component returns all posts of the database instead of none. All posts have correctly tagged categories and published dates. 

My Category page setup:

```
title = "Blog Category"
url = "/category/:slug/:page?"
layout = "default"
is_hidden = 0
robot_index = "index"
robot_follow = "follow"

[blogCategories]
slug = "{{ :slug }}"
displayEmpty = 0
categoryPage = "blog/blog-category"

[blogPosts]
pageNumber = "{{ :page }}"
categoryFilter = "{{ :slug }}"
postsPerPage = 10
noPostsMessage = "No posts found"
sortOrder = "published_at asc"
categoryPage = "blog/blog-category"
postPage = "blog/blog-single"
```

**Comment by daftspunk** [comment]
Yes, when the `:slug` is empty is assumes "no category filter". Try using a default on the parameter

```
url = "/category/:slug?none/:page?"
```

Hope this helps. Ping me if you still need help with this. Thanks
