### ISSUE TITLE
Filtering the Categories List

### ISSUE THREAD

**Issue by marcoinward** [rainlab/blog-plugin#497]
Hi there, I know this is probably so basic, but I cannot find any resource on how to make it work. Literally, all I'd like is to be able to filter the categories that display on the category list. 
So like I am able to filter post list by category, I'd like to filter Category List by category. (I'd like the category list to exclude one of the categories I have created.)

Pleeeease help!

**Comment by bennothommo** [comment]
@marcoinward As an option, you could overwrite the [component markup](https://github.com/rainlab/blog-plugin/blob/master/components/categories/items.htm) in your template and just add an `{% if category.name != 'Category' %}` check around the list item code.
