### ISSUE TITLE
Blog post content images are not rendered.

### ISSUE THREAD

**Issue by MariusGi** [rainlab/blog-plugin#499]
Hello,

I tried to add images in blog post both as "image" and as "media image".

I am using the recomended syntax to uploading images. Which is generated by pressing image or media image button and then selecting image.

Images are showing in backend on the right side of Blog module. Where it shows how the content looks.
However in my website I just get the same code as it is written in code editor window(left side of Blog module). ![]img with parentheses on img, where img is my working link to img.

I am calling blog post content in a .htm file as {{ post.content|raw }}
I am getting the content, just images are not rendered.

Could you let me know what could be wrong here?

**Comment by bennothommo** [comment]
@MariusGi You need to use `{{ post.content_html|raw }}` to get the proper HTML.
