### ISSUE TITLE
dynamic category url depending on the news

### ISSUE THREAD

**Issue by dynamiccontent** [rainlab/blog-plugin#501]
I have 3 categories. Example category1, category2, category3.
I display every category on different page with filter that works fine but what I want to achieve is
When I click on on the news article on category1 I get url https://example.com/category1/newstitle
for category2 https://example.com/category2/newstitle
for category3 https://example.com/category3/newstitle
How can I do this? Any examples... The problem I have is that on the front page I want to display all the news (from all categories) and when I click on the news that was posted in different category the url should reflect the category it was posted in.
Anyone?

**Comment by chrisvidal** [comment]
this should work fine in your page 

```yaml
url = "category/:categorySlug/:pageTitle?"
```

or if pageTitle is mandatory:

```yaml
url = "category/:categorySlug/:pageTitle"
```

**Comment by get-web** [comment]
> ```yaml
> :categorySlug/:pageTitle?
> ```
It doesn't work

**Comment by daftspunk** [comment]
When you link to a page, you have the opportunity to supply route params, for example:

```
{{ 'postpage'|page({categorySlug: post.category.slug }) }}
```
