### ISSUE TITLE
Minimize ajax requests on markdown preview with debounce

### ISSUE THREAD

**Issue by drmzio** [rainlab/blog-plugin#502]
One thing I've noticed with the markdown editor is that every keystroke initiates an ajax request to the server. Now imagine typing 200 characters per minute, that's equivalent 200 ajax requests per minute. One way to minimize the unnecessary amount of requests is to debounce the markdown preview. I wrote a small plugin that adds a 250 millisecond cool-down before showing an updated preview and I'm using it on https://october-news.com. 

Without debounce | 
--- | 
![](https://cl.ly/02ee65e6292e/Screen%252520Recording%2525202020-05-18%252520at%25252003.05%252520PM.gif)

With debounce | 
--- | 
![](https://cl.ly/1c0864b1f34c/Screen%252520Recording%2525202020-05-18%252520at%25252003.02%252520PM.gif)

Debounce fix: https://github.com/ompmega/blog-preview-debounce-plugin

Discussion: Should this be a core feature in the blog plugin?

**Comment by bennothommo** [comment]
@drmzio I'd be happy to make it slightly debounced as a core feature (although it needs to still feel responsive when typing). I know that mass-spamming AJAX calls could be interpreted as a DDoS by some systems too, so someone typing up a big blog post could inadvertently fall afoul of their mitigation systems.

**Comment by LukeTowers** [comment]
@bennothommo I don't suppose there's a client side implementation of the markdown renderer that we could use instead of having to make a AJAX request to re-render the preview continually?

**Comment by drmzio** [comment]
@bennothommo For sure! I was thinking about having a setting that lets users change the debounce delay if needed. I'll see what I can come up with.

@LukeTowers So far I haven't found a client-side markdown renderer in the October codebase, only in the backend https://octobercms.com/docs/services/parser#markdown-parser but I'm curious how the client-side renderer would turn out. Might test something like this too :P

**Comment by bennothommo** [comment]
@LukeTowers There's a few out there (eg. https://github.com/markedjs/marked), but I'd be concerned that there might be small subtle differences between them and Parsedown. At least with the way the widget works currently, it's "what you see is what you get".

@drmzio 
> @bennothommo For sure! I was thinking about having a setting that lets users change the debounce delay if needed. I'll see what I can come up with.

I'd probably just set a sensible middle-ground between responsiveness and spamming the crap out of a server. I doubt there'd be many people who would change it TBH.

**Comment by LukeTowers** [comment]
@drmzio note that this should probably be done to the core markdowneditor widget. @bennothommo what's the difference between the widget provided by this plugin and the core one?

**Comment by bennothommo** [comment]
@LukeTowers there's very little difference I believe - it just has some slight customisations to the preview and file upload aspects, and there's tweaks to the styling of it. Otherwise, functionally, they're identical.

**Comment by drmzio** [comment]
I've decided that this isn't much of a big issue for most people. A debounce feature would be better at the October core level, rather than specifically for this plugin.

For anyone that needs this functionality, you can clone my plugin here https://github.com/ompmega/blog-preview-debounce-plugin

However, I will be testing out a client-side markdown editor and see how it turns out. Might start with the UIkit editor https://getuikit.com/v2/docs/htmleditor.html#markdown

**Comment by bennothommo** [comment]
@drmzio It appears UIKit uses the same library I posted above for Markdown parsing on the client side. I'd probably say if you wanted to use it, it would still need to be a plugin.
