### ISSUE TITLE
Blog Plugin installation is giving error.. and no blog has been installed or activated before

### ISSUE THREAD

**Issue by PKKumar1** [rainlab/blog-plugin#505]
Hello,

I am trying to install blog but it is giving below error. Can you please help.

Update failed
{"#layout-flash-messages":" <p data-control=\"flash-message\" class=\"flash-message fade error\" data-interval=\"5\">The slug has already been taken.<\/p>\n","X_OCTOBER_ERROR_FIELDS":{"slug":["The slug has already been taken."]}}

**Comment by bennothommo** [comment]
@PKKumar1 can you please provide the steps that you took in order to encounter this error, so that we can try and replicate?

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
