### ISSUE TITLE
Easy way to quick link to other blog posts and pages?

### ISSUE THREAD

**Issue by sburkett** [rainlab/blog-plugin#507]
More of a question than an issue, but ...

When creating or editing a blog post, is there some easy way to link to the URL of another blog post or page? The only way that I can see to do it is to constantly open a new tab and go search for it and copy/paste the link.

Thanks!

**Comment by bennothommo** [comment]
@sburkett Unfortunately, there's no shortcut through the Markdown editor.

However, you can use plugins to replace the Markdown editor with a Rich WYSIWYG editor, which does have a link facility that allows you to pick single blog posts. You can try this plugin (https://octobercms.com/plugin/anandpatel-wysiwygeditors) or write your own plugin that runs this event (https://octobertricks.com/tricks/force-richeditor-in-rainlabblog-plugin-post-editor).

Note that the Markdown editor and Rich editors are not compatible with one another - you cannot use Markdown in the Rich editor, and vice versa.

**Comment by sburkett** [comment]
Yeah, I tried the WYSIWYG approach, but not ideal. Thanks for the response! Maybe I'll mess with putting together a plugin that will extend the Markdown editor, assuming that is a possibility.

**Comment by bennothommo** [comment]
That would be great if you can pull it off! :)
