### ISSUE TITLE
SEO default value issue

### ISSUE THREAD

**Issue by Artful-dodger** [rainlab/blog-plugin#508]
I am trying to figure out how to resolve an issue where by I have links to none existing pages like for example "http://example.com/blog/category/default/page"  and I am am not sure where the default part of this link is coming from and how to resolve it. It appears that any category created gets this default value it is also assigned to the blog page but not to any of the blog/post pages is there a way to remove this action from the link

**Comment by LukeTowers** [comment]
@Artful-dodger what's the URL of the page you have set as the page to generate URLs to

**Comment by Artful-dodger** [comment]
blog/category/:page/:slug? is for the category page and blog/:page? is for the blog page and blog/post/:slug is for the pos page. The post page doesn't have any SEO issues but the blog page has 2 page with the same tilte that is /blog and /blog/default have the same title of blog-page and because the /blog/category page is inserting the default  value the titles for /blog/category/news and 
/blog/category/article have no title becouse the url reads as /blog/category/default/news instead

**Comment by LukeTowers** [comment]
@Artful-dodger why do you have `:page` in the category page and blog page? What value is supposed to go in there?

**Comment by Artful-dodger** [comment]
I believe that was the way suggest to be setup is the that the setup for pages in the plugin is incorrect if what which way is correct

**Comment by Artful-dodger** [comment]
I have altered the pluging to reflect they the pluging suggests the URL's to be setup but I am still getting the news category with the the default URL /blog/category/default/news page but it has gone from the /blog/category/article any idea why this might be or should I reinstall the pluging and start again with the new parameters

**Comment by LukeTowers** [comment]
@Artful-dodger you shouldn't need to reinstall the plugin, just fix the URLs to be what they're supposed to be on the pages you have setup for linking to

**Comment by Artful-dodger** [comment]
sorry for taking so long to reply it took a while to figure out but as a test I had hard wired a link which was causing the final error but thank you @LukeTowers for your help with this problem
