### ISSUE TITLE
Carousel Using Featured Images

### ISSUE THREAD

**Issue by mattpollard0** [rainlab/blog-plugin#509]
I'm typing to insert a carousel into a blog post that uses the Featured Images as the images for each slide.

I know I can link to the first and last images using .first and .last, is there a way I can link to the ones in between as well, and only display the slide if an image exists?

**Comment by bennothommo** [comment]
@mattpollard0 You just need to use a Twig `for` loop to get all the images - you can see how the default partial for the post component does it:
https://github.com/rainlab/blog-plugin/blob/master/components/post/default.htm#L5-L17

**Comment by mattpollard0** [comment]
Brilliant, thank you so much!
