### ISSUE TITLE
Alias already exists

### ISSUE THREAD

**Issue by mkinternet** [rainlab/blog-plugin#511]
When i create new post with alias that already exists i recieve message "Alias already exists". Plugin should have create new alias automaticly instead of throwing an error. For example by adding dash and number on the end.

new-post-title
new-post-title-1
new-post-title-2
and so on.

**Comment by bennothommo** [comment]
@mkinternet I have to say I disagree - I'd rather the system tell me the post slug is in use and give me the option to suffix it or change it to something else, than to have it suffix it without any warning.

**Comment by LukeTowers** [comment]
The sluggable trait already does this in PHP if a slug isn't provided. I agree with @bennothommo though, it's better UX for the user to be notified they have a conflicting slug, usually that means they should probably name one of the two posts something different.

**Comment by mkinternet** [comment]
It is good solutions when you have few posts with the same title. When posts are more you have to always think how to name slug.
Typical user does''t want to have this problem. Typycial user event doesn't know what the slug is for.
Wordpress increments same slug and it is hidden form the user.

**Comment by bennothommo** [comment]
@mkinternet Just because Wordpress does it, doesn't make it a good idea, unfortunately. While some people may not realise what slugs are for, I feel they will most certainly appreciate being warned if it's a duplicate, as opposed to wondering why their URLs end with a "-2" or a "-3".
