### ISSUE TITLE
Pagination hidden in Safari

### ISSUE THREAD

**Issue by Klaswh** [rainlab/blog-plugin#515]
Pagination is hidden in Safari, no html code out at al.  This at least on local host.
Function in other web browsers, like Opera and Chrome.

**Comment by LukeTowers** [comment]
That makes absolutely zero sense whatsoever. The server should not be deciding to just not send part of the response to a specific browser. This sounds like an issue with your debugging process. 

Please post the view-source results of the page in question from safari & chrome, as well as the code you're using to generate the page.

**Comment by Klaswh** [comment]
Actually the pagination do not show up when your not loged in, in October CMS.

Sorry for my bad check, before post.

**Comment by LukeTowers** [comment]
@Klaswh it sounds like you don't have enough public published posts for the pagination to show up when not logged in. Is that the case?

**Comment by daftspunk** [comment]
When you are signed in as admin, unpublished posts will appear on the front-end. This is probably why. If it is still an issue, ping me and we can revisit. Thanks
