### ISSUE TITLE
Update Page theme not working 

### ISSUE THREAD

**Issue by awaidqureshi** [rainlab/blog-plugin#517]
Update page broken how to solve this issue
![image](https://user-images.githubusercontent.com/46388507/89890012-091ece00-dbec-11ea-872f-44f0971d201f.png)

**Comment by bennothommo** [comment]
@awaidqureshi You are missing the PHP `gd` extension which is required for October CMS. Please install that and try it again.

**Comment by awaidqureshi** [comment]
Thanks, its resolved
