### ISSUE TITLE
define a user who can only contribute to a specific category of posts

### ISSUE THREAD

**Issue by Thominho** [rainlab/blog-plugin#518]
Hi, is it possible to define a user who can only contribute to the category of posts A, and then a user who can contribute to the category of posts A, B?

Thank you

**Comment by bennothommo** [comment]
@Thominho unfortunately there's no functionality within the Blog plugin for this type of control over categories. I'm not aware of any plugins that provide that functionality, but I can imagine it would be very doable as a plugin.
