### ISSUE TITLE
Page contents doesn't appear in the backend for administration tabs

### ISSUE THREAD

**Issue by Calinou** [rainlab/blog-plugin#524]
**PHP version:** 7.4.11
**October version:** 1.1.0
**Rainlab blog plugin version:** 1.4.3

*Note:* unlike #523, this also occurs before upgrading the plugin.

When I browse to the list of blog posts or create a new post in the backend, I get an empty page even though submenus are displayed:

![image](https://user-images.githubusercontent.com/180032/95619695-4c23e300-0a6f-11eb-9d78-5ad2e4ef74b5.png)

![image](https://user-images.githubusercontent.com/180032/95619714-534af100-0a6f-11eb-93f3-7a03d33882a7.png)

I don't get any errors in the browser's console. I also tried disabling uBlock Origin to no avail.
The Dashboard and CMS tabs display fine. The Patreon tab doesn't either (it's https://github.com/pcvonz/oc-patreongoalstatus-plugin), but I'm also trying to fix that plugin :slightly_smiling_face: 

I can reproduce this with both Firefox 81 and Chromium 85.

**Comment by LukeTowers** [comment]
@Calinou are you using symlinks locally? If so you need to make sure you disable `cms.restrictBaseDir` (only do so locally, never do so in production): https://github.com/octobercms/october/blob/develop/config/cms.php#L446

**Comment by Calinou** [comment]
@LukeTowers Enabling symlinks resolved the issue, thanks a lot!

Is there a way this could be detected while in development to print an error message somewhere?

**Comment by bennothommo** [comment]
@Calinou I have previously thought about having a warning for this come up in the status box on the Dashboard, but I felt that a) some people may be using symlinks within the app which don't go outside the bounds of the app (therefore `cms.restrictBaseDir` is not required) and b) the performance decrease in checking if any symlinks are being used anywhere within the app made it not worth it.

If it comes up, we can certainly point people in the correct direction if they don't see this issue first. It could also be added to the docs somewhere.

**Comment by LukeTowers** [comment]
@bennothommo I think the way to handle it would be to display a better warning message if the view file that's supposed to be rendered isn't able to, and that message could simply include a "Are you using symlinks to manage code outside of your project root? Try disabling cms.restrictBaseDir (NEVER DO IN PRODUCTION)"
