### ISSUE TITLE
MS SQL Server 2019 / the ORDER BY clause is  invalid

### ISSUE THREAD

**Issue by chrisvidal** [rainlab/blog-plugin#525]
@bennothommo 

On Microsoft Azure 2019 / MS SQL Server 2019 / PHP 7.4 / Laravel version from last October CMS installed with Wizard.

using the `Posts` component from the Blog plugin, `scopeListFrontend`

Few test cases:

## case 1

`select  * from [rainlab_blog_posts] order by [published_at] desc` and `select top 100 * from [rainlab_blog_posts] order by [published_at] desc`

is working fine

## case 2
`select * from [rainlab_blog_posts] where exists (select * from [rainlab_blog_categories] inner join [rainlab_blog_posts_categories] on [rainlab_blog_categories].[id] = [rainlab_blog_posts_categories].[category_id] where [rainlab_blog_posts].[id] = [rainlab_blog_posts_categories].[post_id] and [id] in (?) order by [nest_left] asc) order by [published_at] desc`

```php
PDOException: SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified. in D:\STTC\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:105
#0
D:\STTC\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php(105):
PDOStatement->execute()
#1
D:\STTC\vendor\laravel\framework\src\Illuminate\Database\Connection.php(330):
Doctrine\DBAL\Driver\PDOStatement->execute()
#2
D:\STTC\vendor\laravel\framework\src\Illuminate\Database\Connection.php(657):
Illuminate\Database\Connection->Illuminate\Database\{closure}()
#3
D:\STTC\vendor\laravel\framework\src\Illuminate\Database\Connection.php(624):
Illuminate\Database\Connection->runQueryCallback()
#4
D:\STTC\vendor\laravel\framework\src\Illuminate\Database\Connection.php(333):
Illuminate\Database\Connection->run()
#5
D:\STTC\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1719):
Illuminate\Database\Connection->select()
#6
D:\STTC\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1704):
Illuminate\Database\Query\Builder->runSelect()
#7
D:\STTC\vendor\october\rain\src\Database\QueryBuilder.php(122):
Illuminate\Database\Query\Builder->get()
#8
D:\STTC\vendor\october\rain\src\Database\QueryBuilder.php(92):
October\Rain\Database\QueryBuilder->getDuplicateCached()
#9
D:\STTC\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1804):
October\Rain\Database\QueryBuilder->get()
#10
D:\STTC\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1777):
Illuminate\Database\Query\Builder->runPaginationCountQuery()
#11
D:\STTC\vendor\october\rain\src\Database\Builder.php(138):
Illuminate\Database\Query\Builder->getCountForPagination()
```

## case 3

trying to implement MS recommendation to use TOP, but does not work either.

`select top 100 * from [rainlab_blog_posts] where exists (select * from [rainlab_blog_categories] inner join [rainlab_blog_posts_categories] on [rainlab_blog_categories].[id] = [rainlab_blog_posts_categories].[category_id] where [rainlab_blog_posts].[id] = [rainlab_blog_posts_categories].[post_id] and [id] in (?) order by [nest_left] asc) order by [published_at] desc`

```php
PDOException: SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified. in D:\STTC\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:105
#0
D:\STTC\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php(105):
PDOStatement->execute()
#1
D:\STTC\vendor\laravel\framework\src\Illuminate\Database\Connection.php(330):
Doctrine\DBAL\Driver\PDOStatement->execute()
#2
D:\STTC\vendor\laravel\framework\src\Illuminate\Database\Connection.php(657):
Illuminate\Database\Connection->Illuminate\Database\{closure}()
#3
D:\STTC\vendor\laravel\framework\src\Illuminate\Database\Connection.php(624):
Illuminate\Database\Connection->runQueryCallback()
#4
D:\STTC\vendor\laravel\framework\src\Illuminate\Database\Connection.php(333):
Illuminate\Database\Connection->run()
#5
D:\STTC\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1719):
Illuminate\Database\Connection->select()
#6
D:\STTC\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1704):
Illuminate\Database\Query\Builder->runSelect()
#7
D:\STTC\vendor\october\rain\src\Database\QueryBuilder.php(122):
Illuminate\Database\Query\Builder->get()
#8
D:\STTC\vendor\october\rain\src\Database\QueryBuilder.php(92):
October\Rain\Database\QueryBuilder->getDuplicateCached()
#9
D:\STTC\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1804):
October\Rain\Database\QueryBuilder->get()
#10
D:\STTC\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1777):
Illuminate\Database\Query\Builder->runPaginationCountQuery()
#11
D:\STTC\vendor\october\rain\src\Database\Builder.php(138):
Illuminate\Database\Query\Builder->getCountForPagination()
```

**Comment by chrisvidal** [comment]
after test in pure SQL on SQL Server, this is correct

`select * from [rainlab_blog_posts] where exists (select top 100 * from [rainlab_blog_categories] inner join [rainlab_blog_posts_categories] on [rainlab_blog_categories].[id] = [rainlab_blog_posts_categories].[category_id] where [rainlab_blog_posts].[id] = [rainlab_blog_posts_categories].[post_id] and [id] in (1) order by [nest_left] asc) order by [published_at] desc;`

notice the shift of location for `select top 100`, it needs to be in the subqueries for SQL server in that case.

Am trying to translate this into Eloquent query now

**Comment by chrisvidal** [comment]
what works is to modify the `scopeListFrontend` method with this:

```php
        /*
         * Category, including children
         */
        if ($category !== null) {
            $category = Category::find($category);

            $categories = $category->getAllChildrenAndSelf()->lists('id');
            $query->whereHas('categories', function ($q) use ($categories) {
                $q->whereIn('id', $categories)->limit(100);
            });
        }
```

**Comment by bennothommo** [comment]
@chrisvidal What happens if you remove the ordering in the inner query? It might be better to remove the ordering, as the inner query doesn't need to be ordered when it's only being used as a filter (ie. the post must belong to one of the categories returned by the inner query).

**Comment by bennothommo** [comment]
I think the real cause of the issue is that the `NestedTree` trait in the `Blog` model injects an order clause in every query via [a global scope](https://github.com/octobercms/library/blob/develop/src/Database/NestedTreeScope.php). What would resolve this would be to disable this global scope in the inner query:

```php
$query->whereHas('categories', function ($q) use ($categories) {
    $q->withoutGlobalScope(NestedTreeScope::class)->whereIn('id', $categories)->limit(100);
});

**Comment by chrisvidal** [comment]
> What happens if you remove the ordering in the inner query?

I am not sure where this orderBy is done in the subquery.

**Comment by chrisvidal** [comment]
> I think the real cause of the issue is that the `NestedTree` trait in the `Blog` model injects an order clause in every query via [a global scope](https://github.com/octobercms/library/blob/develop/src/Database/NestedTreeScope.php). What would resolve this would be to disable this global scope in the inner query:
> 
> ```
> $query->whereHas('categories', function ($q) use ($categories) {
>     $q->withoutGlobalScope(NestedTreeScope::class)->whereIn('id', $categories);
> });
> ```

Oo, never heard of this indeed. Let me try this tomorrow when I can connect remotely to my client server.

thanks

**Comment by chrisvidal** [comment]
Alright, just tested on the client SQL Server and you are right @bennothommo your snippet fixes the particular SQL Server issue. Would be good to implement it in the `post.php` model for future SQL server users I guess.
thanks so much

**Comment by chrisvidal** [comment]
the issue exists as well on the backend side in the plugin, especially when one performs a filter by category.

**Comment by bennothommo** [comment]
@chrisvidal Would you mind testing the changes in #526 and letting me know if that resolves all issues for you?
