### ISSUE TITLE
How can I make CSV exports accessible to public users without requiring a login?

### ISSUE THREAD

**Issue by RobertMatkulcik** [rainlab/blog-plugin#527]
Hello, I'm trying to make a CSV export of all blog posts. Without any permissions required - visible for any visitor. 
So, I edited the config_import_export.yaml to offer file download. Unfortunately this works only for admins, cause non-registered users are redirected to Sign In page. Is this a plugin restriction or October CMS?
THX for any help :)

**Comment by LukeTowers** [comment]
What does your config_import_export.yaml look like?

**Comment by RobertMatkulcik** [comment]
Hi, Luke. My config looks like this:
```
export:
    useList: true
```

**Comment by LukeTowers** [comment]
> I edited the config_import_export.yaml to offer file download

I don't see anything in your config that would say that a generated export file can be downloaded

**Comment by RobertMatkulcik** [comment]
So, what I'm missing? Permissions options?

**Comment by LukeTowers** [comment]
Please provide a gif of how the process currently works and how you expect the process to work for users that aren't logged in.

**Comment by RobertMatkulcik** [comment]
A GIF? OK, there is a working example as a logged-in user.
![Working](https://user-images.githubusercontent.com/13135956/97631684-9f1b0580-1a31-11eb-928d-d5caad842892.gif)
And non-working example as a non-logged-in user :) 
![not-Working](https://user-images.githubusercontent.com/13135956/97631800-ceca0d80-1a31-11eb-923a-b4bea426a4f8.gif)

Just want to make file downloadable for all.

**Comment by LukeTowers** [comment]
Backend controllers inherently block non-logged users from accessing them by default, that's the point of the backend. If you want to make the file available for people to download then you can just download it yourself and then upload it to the Media Manager and provide a URL to that uploaded file. If you'd like to have a URL that will automatically export and download the latest posts whenever you hit it then that will require custom development on your part as that's effectively creating an API (albeit a CSV file download is a pretty crappy API).

What are you trying to achieve by allowing non-logged in users to download an export of all posts? (Note that this export includes posts that are private / not published yet.
