### ISSUE TITLE
How to edit the sidebar latest posts

### ISSUE THREAD

**Issue by g3rox** [rainlab/blog-plugin#531]
Hi, I downloaded this theme: [https://octobercms.com/theme/mehedi-megakit](https://octobercms.com/theme/mehedi-megakit) and installed the Blog plugin. But after I followed the instructions, I do not get what was shown in the demo here: [https://octobercms.com/theme/mehedi-megakit](http://demo.themefisher.com/megakit/blog-single.html) I would like to have the photos of the blogs next to the titles as shown and no excerpt, just the date. How can I achieve this?

**Comment by mjauvin** [comment]
Please, open a support issue here:

https://octobercms.com/theme/support/mehedi-megakit

**Comment by g3rox** [comment]
I did but no one answered.

**Comment by mjauvin** [comment]
Then I suggest using a different theme...

**Comment by g3rox** [comment]
I don't understand. That part of the theme is using the blog plugin. So wouldn't that fall under the plugin support? Is what they did possible to do with the plugin or ?

**Comment by mjauvin** [comment]
There is nothing wrong with the blog plugin. If the theme uses the plugin the wrong way or if you expect a different layout/rendering, it's up to you or the theme to customize this.

**Comment by LukeTowers** [comment]
See https://octobercms.com/docs/cms/components#customizing-default-markup for information on how to customize the default partials provided by plugins.
