### ISSUE TITLE
Global Title Tag

### ISSUE THREAD

**Issue by orzech76** [rainlab/blog-plugin#533]
Hello, How can I change the global title tag that displays in google for each blog article to a unique title tag for each category? Now, Google displays the same title in every category in search results. I will be grateful for your help

**Comment by mjauvin** [comment]
which "global title tag" are you refering to? You mean like below?
```html
<head><title> My Title </title></head>
```

**Comment by daftspunk** [comment]
Add this PHP code to your page

```
function onStart()
{
    $this->meta_title = $this->post->title;
}
```

**Comment by chocolata** [comment]
Hi Samuel, is it possible that this doesn't work anymore?
Inside my blogpost detail page I've got in the header:

	title = "Article"
	url = "/news/article/:slug"
	layout = "blog/post"
	is_hidden = 0

	[viewBag]
	[blogPost]
	[blogCategories]
	slug = "{{ :slug }}"
	displayEmpty = 0
	categoryPage = "blog/category"

	==
	<?php
	function onStart(){
		$this->meta_title = "My custom meta title"; // doesn't work
		$this->page->meta_title = "My custom meta title"; // doesn't work
		$this->page->title = "My custom meta title"; // doesn't work
	}
	function onEnd() {
		$this->meta_title = "My custom meta title"; // doesn't work
		$this->page->meta_title = "My custom meta title"; // doesn't work
		$this->page->title = "My custom meta title"; // doesn't work
		
		// Strangely, below does work perfectly!
		$this->page->meta_description = 'My custom meta description'; 
	}
	?>
	==

My header partial is then mentioned in the `blog/post` layout. My header contains the following code regarding the page title:

    <title>{% if this.page.meta_title | length %}{{ this.page.meta_title }}{% else %}{{ this.page.title }} - {{ this.theme.site_title }}{% endif %}</title>

The documentation states the following, but this doesn't seem to work. The post title is always used, even if we use something else like `$this->page->title = "Get to de choppaaaah";`

    title = "Blog Post"
    url = "/blog/post/:slug"

    [blogPost]
    ==
    <?php
    function onEnd()
    {
        // Optional - set the page title to the post title
        if ($this->post)
            $this->page->title = $this->post->title;
    }
    ?>
    ==

Interestingly the meta title does seem to be correctly set when no layout is defined in the blog detail page. 
Also, strangely, this issue does not seem to appear on the category pages. There, the above code works as it should.

What could be the issue? I could supply a test-environment if that would be helpful.
Thanks in advance for your time.

**Comment by daftspunk** [comment]
Hi @chocolatam

This appears to be working normally. Tested with v2.2 and and v3.0

```
title = "Blog Post"
url = "/blog/post/:slug"
layout = "default"
description = "Viewing a single blog post"
hidden = "0"

[blogPost]
slug = "{{ :slug }}"
categoryPage = "blog/category"
==
<?php
function onEnd()
{
    $this->page->title = $this->post->title;
}
?>
==
{% component 'blogPost' %}

```

In the layout 

```
<title>October CMS - {{ placeholder('pageTitle') ?: (this.page.meta_title ?: this.page.title) }}</title>
```

Tested with your code as well

```
<title>{% if this.page.meta_title | length %}{{ this.page.meta_title }}{% else %}{{ this.page.title }} - {{ this.theme.site_title }}{% endif %}</title>
```

Check that you don't have any plugins installed that might be interfering.
