### ISSUE TITLE
How to prevent wrapping of images in markdown within <p> tags?

### ISSUE THREAD

**Issue by TuringJest** [rainlab/blog-plugin#534]
Currently all images added in markdown are wrapped within a p tag. How can we prevent that? 

It makes it impossible to style paragraphs and images separately in certain situations (e.g. width).

**Comment by bennothommo** [comment]
@TuringJest the [Markdown standard](https://www.markdownguide.org/basic-syntax/#paragraphs-1) stipulates that any content separated by a blank line should be made into paragraphs and surrounded by `<p>` tags. If you remove the blank line, the image will fall inline with the content surrounding it.
