### ISSUE TITLE
Composer PHP Dependency is wrong

### ISSUE THREAD

**Issue by nokios** [rainlab/blog-plugin#537]
Since version 1.4.1 you have introduced arrow function syntax.

(Example, see here: https://github.com/rainlab/blog-plugin/blob/9853f3a4db8329fd429158ec4c48f699fafb195d/components/posts/default.htm#L10)

Your composer php version, however, for version 1.4.1, is php >=7.0.

This is not advisable, as arrow functions were introduced in php 7.4.  You should indicate 7.4 as a minimum at this point.

Not sure what you can do about this except maybe fix and re-tag your versions or mark as broken?

**Comment by LukeTowers** [comment]
@nokios would you be willing to submit a PR to remove the arrow function? Not sure how I let that slip through, I don't like using them period.  Also, I have no idea how Twig even permits that as valid syntax. @bennothommo any thoughts?

**Comment by nokios** [comment]
I will see if I have time at some point to submit a PR.

**Comment by daftspunk** [comment]
Rolled it back. Thanks
