### ISSUE TITLE
Backend button notify all registered users from user plugin

### ISSUE THREAD

**Issue by Hessel91** [rainlab/blog-plugin#541]
Hi, for a client I would like the blog plugin to send a notification e-mail to all registered "User" plugin users. 
I know there is a front-end plugin for this however all other plugins are managed in the backend, I can not tell them to switch to backend and front-end to manage their website. Is this a modification request that would benefit other blog plugin users  as well or do I need to post this as a job request?

**Comment by bennothommo** [comment]
@Hessel91 this is functionality that would best suited for another plugin that extends the Blog plugin. I don't think there's a real use case for having the function in the Blog plugin by default - it's not really a "natural" place to look for a "notify all users" action.
