### ISSUE TITLE
Error displaying translated post

### ISSUE THREAD

**Issue by kolacekp** [rainlab/blog-plugin#544]
Hi, 

I have problem with displaying multilingual blog post.

When I have configured multiple languages on the site and create a blog post in backend with some translated contents. But those translated contents don't show on frontend (displaying via blogPost component, via `content_html`) property - there is fallback to the default language. Post title shows correctly, post url show correctly, but content (content_html) not.

I've just been doing some digging and found that if you paste some translations in backend, they're not saved properly to the database table `rainlab_translate_attributes` - in the field `attribute_data` there is just translated `content` property in json object, but not the `content_html` property. 

Though, on the fronted it works when I display the post content with `{{post->content|raw}}` markup but I'm not sure if it will always work with formatting.

Can you please look at this? 

Thanks,
best regards,
Petr Kolacek

**Comment by LukeTowers** [comment]
@mjauvin

**Comment by mjauvin** [comment]
This is personally how I display the post content, and it does get translated:
```
{{ html_clean(post.content)|md }}
```

**Comment by daftspunk** [comment]
The |raw filter is needed for now
