### ISSUE TITLE
1054 Unknown column...'post_id` is not null limit 1... (error when trying to extend Post model)

### ISSUE THREAD

**Issue by Dione-stack** [rainlab/blog-plugin#545]
Hi there
I'm trying to extend Post model and add new fields, and i'm getting a database related error
when i go to an existing blog post i get this error:

`"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'testplugins_myplugin_videos.post_id' in 'where clause' (SQL: select * from `testplugins_myplugin_videos` where `testplugins_myplugin_videos`.`post_id` = 2 and `testplugins_myplugin_videos`.`post_id` is not null limit 1)" on line 664 of D:\Work\Projects\Experiments Lab\vendor\laravel\framework\src\Illuminate\Database\Connection.php`

and when i try to save a new post i get this error:

`"Call to a member function hasRelation() on null" on line 70 of D:\Work\Projects\Experiments Lab\modules\backend\traits\FormModelSaver.php`

Migration file:

```
<?php namespace Testplugins\Myplugin\Updates;

use Schema;
use October\Rain\Database\Schema\Blueprint;
use October\Rain\Database\Updates\Migration;

class CreateFieldsTable extends Migration
{
    public function up()
    {
        Schema::create('testplugins_myplugin_videos', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->integer('video_length')->nullable();
            $table->timestamps();
        });
    }

    public function down()
    {
        Schema::dropIfExists('testplugins_myplugin_videos');
    }
}
```

Plugin.php file:

```
use RainLab\Blog\Models\Post as PostModel;
use RainLab\Blog\Controllers\Posts as PostsController;

public function boot()
{
  PostModel::extend(function($model){
    $model->hasOne['video'] = ['Testplugins\Myplugin\Models\Video'];
  });

  PostsController::extendFormFields(function($form, $model, $context){
    $form->addTabFields([
      'video[video_length]' => [
        'label' => 'Video Length',
        'tab' => 'video'
      ],
    ]);
  });
}
```

**Comment by bennothommo** [comment]
@Dione-stack for a `hasOne` relation, the target database - in the case `testplugins_myplugin_videos` - should have a related ID column that matches the model name in underscore-case. So, in this instance, you should have a `post_id` column in that table.

**Comment by Dione-stack** [comment]
> @Dione-stack for a `hasOne` relation, the target database - in the case `testplugins_myplugin_videos` - should have a related ID column that matches the model name in underscore-case. So, in this instance, you should have a `post_id` column in that table.

Thank you for your response, i added the post_id column to my table just like you said and it worked, and the second error turns out to be unrelated to the issue and i dealt with it as well, that leaves nothing, thank you very much!
