### ISSUE TITLE
Add missed Spanish tranlations

### ISSUE THREAD

**Issue by Chocofede** [rainlab/blog-plugin#547]
Hi, 

I've seen that the new blog update is missing some Spanish translations, so, I've added them and homogenized the translation strings, to make it sound Spanish (From Spain).

I will do a Pull Request from my repo to master. Please, let me know if that's Ok or if I have to do it in a different way.

**Comment by Chocofede** [comment]
I created the #548 pull request for this.

**Comment by daftspunk** [comment]
Merged. Thanks!
