### ISSUE TITLE
Can't update from 1.4.3 to 1.4.4

### ISSUE THREAD

**Issue by climao** [rainlab/blog-plugin#549]
At the end of the update I receive the "Update process complete" flash message but no update is done. No files are changed.
If I hit the "Check for updates" button again I still receive the "Found new updates! Click Update software to begin the update process. "

Anybody knows what is going on?

**Comment by tfprado** [comment]
Having the exact same issue. Running PHP version 7.2 and latest October build (471)

**Comment by lco0Vpjd** [comment]
Not even on a fresh install...nothing on the server log or in cms event log....can't update or install.

**Comment by daftspunk** [comment]
Should be fixed now. Please try the update again and you should get 1.4.4. If it still isn't working, ping me in a comment and we can check again

**Comment by lco0Vpjd** [comment]
Thanks !
