### ISSUE TITLE
Non super admin can't put in embedded media.

### ISSUE THREAD

**Issue by SalocinDotTEN** [rainlab/blog-plugin#550]
Hi,

I have a setup where there are blog writers without administrator privileges and they have come back to me saying while they are able to insert embedded media, they aren't able to save it into the blog article.
Text edits are visible but the embedded media just does not show up.
Only after I log in and resave the blog article does the embedded media show.

Is there a specific setting in October CMS's administrator manager to enable this feature?

Thank you

**Comment by daftspunk** [comment]
This could be related to the permission called `backend.allow_unsafe_markdown` which is designed to stop XSS attacks. It would be worthwhile to check what happens if you give them this permission, of course, it would be wise to only give this permission to roles that you trust and potentially have some legal recourse over

Otherwise, can you provide details on the embedded media that you're using? This will allow us to test with the same data.

**Comment by SalocinDotTEN** [comment]
Thanks @daftspunk :)

I suppose that is the issue.

For information, it is an iFrame based embed. You can go to [this site](https://www.bfm.my/podcast) and look for a random podcast to copy its embed code.

**Comment by daftspunk** [comment]
Thanks, we will conduct some testing against this embed code

```
<script src="https://www.bfm.my/player-embed?embedUrl=https://omny.fm/shows/enterprise-biz-bytes/how-much-are-online-fitness-classes-worth/embed"></script>
```

Is that embed the correct one @SalocinDotTEN ? If so, it would certainly be caused by that permission. Try allowing it for your users and let me know

**Comment by SalocinDotTEN** [comment]
Most welcome, @daftspunk .

The actual embed code is not a script tag but an iframe like as follows..
`<iframe src="https://omny.fm/shows/popcorn-culture/popcorn-culture-throwback-tuesday-kill-bill-vol-1/embed" width="100%" height="180px" frameborder="0"></iframe>`

However yes, it is really caused by that permission setting. I have tested it through user impersonation and it works. So hopefully it will work when the writer uses it again.

Thanks!

**Comment by daftspunk** [comment]
Great, thanks for reporting back
