### ISSUE TITLE
New post save does not show success message

### ISSUE THREAD

**Issue by camohub** [rainlab/blog-plugin#551]
I have a pure new installation of October cms + Blog plugin. 
I tried to make a new post and save it. Page shows me the loading circle but no success message. If I click on other page link this redirect shows me the message related to new post. New post is saved successfully but ajax does not work as expected. 

Here is the link to avi video file https://drive.google.com/file/d/1ixXg-m1rx_IUc1SZ8-N_LOeRfJ_Js7xM/view?usp=sharing

**Comment by daftspunk** [comment]
Fixed in bde3340d4b47119280f093072ef30483c7db76d8 (v1.5.0)

Thanks!
