### ISSUE TITLE
No categories were found.

### ISSUE THREAD

**Issue by camohub** [rainlab/blog-plugin#552]
I have a newest installation of October cms and latest rainlab blog plugin. I can create a categories and posts. But as I try to include the categories list component to the site like
```
        <div class="row">
            <div class="col-md-4 col-md-offset-1">
                <h2>Blog categories</h1>
                {% component 'blogCategories' %}
            </div>

            <div class="col-md-6">
                <h2>Blog posts</h2>
                {% component 'blogPosts' %}
            </div>
        </div>
```
it shows me a message: no categories found.

![Screenshot (389)](https://user-images.githubusercontent.com/8393426/115260712-49e3c500-a133-11eb-8492-edf1631f6d4a.png)

Also there as some checkboxes in the categories administration which make a request to the server but they are still not checked. I dont see any field in database like "active" or "visible" so I dont understand why it plugin does not see any category.

Here are the screenshots of the blog admin pages.

![Screenshot (384)](https://user-images.githubusercontent.com/8393426/115261388-dee6be00-a133-11eb-8da1-86fdc0922824.png)
![Screenshot (383)](https://user-images.githubusercontent.com/8393426/115261398-e017eb00-a133-11eb-844e-63f81f978ff5.png)

**Comment by daftspunk** [comment]
Hi @camohub ! Thank you for this

I note that every category in your screenshot has no posts. The `blogCategories` component does not show empty categories by default. There is a checkbox in the component inspector that lets you modify this behavior

- [ ] Display empty cateogeories

I hope this helps. If it doesn't, ping me here and we can revisit

**Comment by camohub** [comment]
The problem was in published property. But I don't understand if the posts were not published how is it possible I can see them on the page? You can see that on the first screenshot. Non of that posts were published but I can see them.

**Comment by camohub** [comment]
Ok I have it. There is something like "Show all posts to backend users" in blog plugin settings. (in my opinion all this stuff should be on one place)
