### ISSUE TITLE
"Content Field Is Required"

### ISSUE THREAD

**Issue by AbdulsatarAboud** [rainlab/blog-plugin#553]
Hello,

I've installed the current blog plugin(v 1.5.0) on my October project(v 2.0.14). Whenever I make a new blog post I get a flash message "Content Field is required" while I have already filled the text area.

**Comment by daftspunk** [comment]
Hey @AbdulsatarAboud 

Sorry to hear you are having issues. I have tested this and confirmed it is an issue when interacting with the RainLab.Translate plugin. We have pushed a fix and it is available by updating to v1.5.1 of the blog plugin

Thanks!

**Comment by AbdulsatarAboud** [comment]
It works now.

Thank you.
