### ISSUE TITLE
Can't align text or image

### ISSUE THREAD

**Issue by wardaari** [rainlab/blog-plugin#555]
![image](https://user-images.githubusercontent.com/12183372/121887723-62c5bc80-cd17-11eb-80ee-be9591e045ff.png)

I don't see option to align text or to centralize an image

**Comment by daftspunk** [comment]
Hi @wardaari 

When you click on the image, you should see the image-specific options. See below:

![image](https://user-images.githubusercontent.com/1392869/122186699-a2d09f00-ced1-11eb-80f1-07c10888e171.png)

**Comment by wardaari** [comment]
What about text, though?

**Comment by daftspunk** [comment]
The blog plugin uses [Markdown format](https://www.markdownguide.org/basic-syntax/) so the text alignment is not supported natively. You can use HTML to do it instead, for example, to center text:

```
<center>
    My centered text
</center>
```
