### ISSUE TITLE
"Trying to get property 'contentable_id' of non-object"...

### ISSUE THREAD

**Issue by exaline-ru** [rainlab/blog-plugin#556]
(LATEST BUILD 2.0.21 - Blog 1.5.1)

When editing content, this error comes out:

"Trying to get property 'contentable_id' of non-object" on line 96 of /home/admin/web/domain.com/public_html/vendor/october/rain/src/Database/Relations/MorphOne.php

* When creating new content - everything works as it should

**Comment by daftspunk** [comment]
Hi @exaline-ru.

This looks like it may be caused by a plugin that is introducing a relation called `contentable`. Do you have any plugins installed that are extending RainLab.Blog?

**Comment by exaline-ru** [comment]
Yes. The problem is caused by an extraneous editor. After disconnecting - everything works as it should. Thank you for your time.
