### ISSUE TITLE
error for Release post :"A four digit year could not be found Data missing"

### ISSUE THREAD

**Issue by aaradho** [rainlab/blog-plugin#559]
hello,
I have problem. when I want to Release my post in blog , show this error " A four digit year could not be found Data missing....in carbon.php".
because my back-end language is persian.then I change it to English it is correct.
please help me to solve it for persian language.
thanks.

**Comment by daftspunk** [comment]
This appears to be related to a plugin that you have installed. We have followed up via email. Please check your inbox for a reply

**Comment by aaradho** [comment]
hello,I install only this plugin:october demo version 1.0.1blog version 1.5.1builder version 1.0.30Can you explain more please?

    On Monday, July 12, 2021, 06:29:56 AM GMT+4:30, Sam Geo ***@***.***> wrote:  
 
 


This appears to be related to a plugin that you have installed. We have followed up via email. Please check your inbox for a reply

**Comment by daftspunk** [comment]
We can't replicate this, but we saw your email sent to us and have replied with further instructions.
