### ISSUE TITLE
Wrong cursor location in text input area

### ISSUE THREAD

**Issue by NChechulin** [rainlab/blog-plugin#561]
!!! I am not sure that the problem is in the plugin, so feel free to close the issue if it is irrelevant.

Some offset occurs and as a result, the cursor can be right inside the character:
![image](https://user-images.githubusercontent.com/38015818/128758228-f694defe-7068-4ca2-8945-a25f1fd5ed72.png)

The longer the text is, the bigger the difference. At some point, if a user presses Backspace it deletes a "random" character.
I guess the problem is the difference between a visual representation and an actual cursor position, but still, it is very annoying.

Would be happy to try any ways to fix it.

**Comment by daftspunk** [comment]
Hi @NChechulin 

I could not replicate this, using Chrome Version 92.0.4515.107 and Windows 10.

![image](https://user-images.githubusercontent.com/1392869/128960870-519d6b80-1134-43fd-b93f-bd92908864a6.png)

What browser are you using for this to occur?

**Comment by NChechulin** [comment]
Hi @daftspunk!
I use:
- Chrome 92.0.4515.131 (Official Build) (64-bit) (cohort: Stable)
- Windows 10 OS Version 2009 (Build 19043.928)

**Comment by daftspunk** [comment]
It looks like we use the same browser and OS. Unfortunately, I was not able to replicate this. If you can provide more detail, such as replication instructions we can look at finding the cause and a solution.
