### ISSUE TITLE
Unable to type in richeditor field

### ISSUE THREAD

**Issue by maartenmachiels** [rainlab/blog-plugin#562]
Hi,

I'm not sure this issue is elegable for support, but here goes:

My clients is on October 473, using the Blog plugin with the slight modification that the content field is changed to a richeditor field via a custom plugin with the following snippet in the boot method:

        \Event::listen('backend.form.extendFields', function($widget) {

            // Extend only the Blog\Posts controller
            if (!$widget->getController() instanceof \RainLab\Blog\Controllers\Posts)
                return;

            // Extend only Blog\Post model
            if (!$widget->model instanceof \RainLab\Blog\Models\Post)
                return;

            // Update content field
            $widget->addSecondaryTabFields([
                'content' => [
                    'tab' => 'rainlab.blog::lang.post.tab_edit',
                    'type' => 'richeditor',
                    'size' => 'giant',
                    'stretch' => 'true'
                ]
            ]);
        });

Now for some strange reason, in Google Chrome on Mac, it seems to be impossible to access the content field. You cannot click in it... If you enlarge the richeditor field to fullscreen, you can type into it, but when making it smaller, the content is gone again.

The strange thing is that this issue only appears in Google Chrome on Mac. The issue doesn't appear in Google Chrome on Windows or Safari on Mac.

My client mentioned the following versions: macOS Mojave version 10.14.6, Chrome version 93.0.4577.82 (and up-to-date as of today).

In the Console there does seem to be some errors, but they also appear on Google Chrome on Windows, so they might be unrelated:

```
jquery-migrate.min.js?v=473:33 JQMIGRATE: Migrate is installed, version 3.0.1
jquery.min.js?v=473:2 jQuery.Deferred exception: this.$markdownEditor.markdownEditor is not a function TypeError: this.$markdownEditor.markdownEditor is not a function
    at VideoTagProcessor.addToolbarButton (https://essma.eu/plugins/rainlab/blogvideo/assets/js/blog-video.js:14:44)
    at new VideoTagProcessor (https://essma.eu/plugins/rainlab/blogvideo/assets/js/blog-video.js:6:14)
    at HTMLDocument.<anonymous> (https://essma.eu/plugins/rainlab/blogvideo/assets/js/blog-video.js:124:9)
    at e (https://essma.eu/modules/backend/assets/js/vendor/jquery.min.js?v=473:2:29453)
    at t (https://essma.eu/modules/backend/assets/js/vendor/jquery.min.js?v=473:2:29755) undefined
k.Deferred.exceptionHook @ jquery.min.js?v=473:2
t @ jquery.min.js?v=473:2
setTimeout (async)
(anonymous) @ jquery.min.js?v=473:2
c @ jquery.min.js?v=473:2
fireWith @ jquery.min.js?v=473:2
fire @ jquery.min.js?v=473:2
c @ jquery.min.js?v=473:2
fireWith @ jquery.min.js?v=473:2
ready @ jquery.min.js?v=473:2
B @ jquery.min.js?v=473:2
jquery.min.js?v=473:2 Uncaught TypeError: this.$markdownEditor.markdownEditor is not a function
    at VideoTagProcessor.addToolbarButton (blog-video.js:14)
    at new VideoTagProcessor (blog-video.js:6)
    at HTMLDocument.<anonymous> (blog-video.js:124)
    at e (jquery.min.js?v=473:2)
    at t (jquery.min.js?v=473:2)
VideoTagProcessor.addToolbarButton @ blog-video.js:14
VideoTagProcessor @ blog-video.js:6
(anonymous) @ blog-video.js:124
e @ jquery.min.js?v=473:2
t @ jquery.min.js?v=473:2
setTimeout (async)
k.readyException @ jquery.min.js?v=473:2
(anonymous) @ jquery.min.js?v=473:2
e @ jquery.min.js?v=473:2
t @ jquery.min.js?v=473:2
setTimeout (async)
(anonymous) @ jquery.min.js?v=473:2
c @ jquery.min.js?v=473:2
fireWith @ jquery.min.js?v=473:2
fire @ jquery.min.js?v=473:2
c @ jquery.min.js?v=473:2
fireWith @ jquery.min.js?v=473:2
t @ jquery.min.js?v=473:2
setTimeout (async)
(anonymous) @ jquery.min.js?v=473:2
c @ jquery.min.js?v=473:2
fireWith @ jquery.min.js?v=473:2
fire @ jquery.min.js?v=473:2
c @ jquery.min.js?v=473:2
fireWith @ jquery.min.js?v=473:2
ready @ jquery.min.js?v=473:2
B @ jquery.min.js?v=473:2
```

Does someone else also experience this issue? Thanks in advance.

P.S.: Please note that my client is able to type into all other richeditor fields.

**Comment by daftspunk** [comment]
Hi @maartenmachiels 

Try uninstalling the `rainlab/blogvideo` plugin because it specifically looks for a markdown editor, which you are not using anymore.

I hope this helps!

**Comment by maartenmachiels** [comment]
Hi @daftspunk , just to let you know that that solves the issue! Thanks a bunch.
