### ISSUE TITLE
Change data range to blog  V1.2.2

### ISSUE THREAD

**Issue by IonelRO** [rainlab/blog-plugin#569]
Hi,
I have a site made with October CMS and blog V 1.2.2.

Data range is until 31 dec 2020 ... how I can extened this range ?

**Comment by daftspunk** [comment]
Hi @IonelRO, 

This should not happen normally. Could you show a screenshot?

**Comment by IonelRO** [comment]
Attached.

| 
Ionel Dobre
Președinte
 | 
ASOCIAȚIA PSIHOLOGILOR GORJENI
Tel: +40253213041

Mobil: +40764473012
***@***.*** / www.apsg.ro |


  

    On Wednesday, March 2, 2022, 12:04:20 AM GMT+2, Samuel Georges ***@***.***> wrote:  
 
 


Hi @IonelRO,

This should not happen normally. Could you show a screenshot?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by daftspunk** [comment]
Please email this using the contact details here: https://octobercms.com/contact

Thanks
