### ISSUE TITLE
Text cannot contain '&'

### ISSUE THREAD

**Issue by Bauboo** [rainlab/blog-plugin#570]
### Description

When I make a blog post with an '&' in the text, the text gets truncated right before the '&'. There is no obvious error message.

### Versions

Rainlab/Blog: 1.5.6
OctoberCMS: 3.0.51

### Other

It did work in the past with an older version of the plugin and OctoberCMS 2, although I don't remember the exact versions.

**Comment by daftspunk** [comment]
Hi @Bauboo 

Please try updating to OCMS v3.0.52 for the fix.

Thanks!
