### ISSUE TITLE
Categories translated slug issue

### ISSUE THREAD

**Issue by az-vm** [rainlab/blog-plugin#571]
Hello!

First thank you for this amazing plugin.

I´m facing the problem only in categories, not in posts, with the translated slug on front end side.

When we change locale it don´t change the url to the translated slug defined on the categories.

For example: 
www.domain.com/en/categorie/en_slug
www.domain.com/es/categorie/es_slug

When we are on:
-> www.domain.com/en/categorie/en_slug 
-> and change the locale to (ES)
it shows: www.domain.com/es/categorie/en_slug

and trowns a categorie not found on page.

What could it be ?

Kind Regard´s

**Comment by az-vm** [comment]
Hello @daftspunk 

Any update on this bug ?

Kind Regard's

**Comment by daftspunk** [comment]
This is a known issue with the translate plugin, and we are working on a solution.

**Comment by az-vm** [comment]
Thank you @daftspunk

**Comment by zakir1929** [comment]
Hello @daftspunk 
I am having the same issue in ocms v3

is there any solution for that?

**Comment by zakir1929** [comment]
Dont worry I have found the solution. this Event listener did the trick

```
Event::listen('cms.sitePicker.overrideParams', function($page, $params, $currentSite, $proposedSite) {
     if ($page->baseFileName == 'your-page-filename') {
          return YourModel::overrideParams($params, $currentSite, $proposedSite);
      }
});
```

**Comment by daftspunk** [comment]
Thanks @zakir1929 

This should solve it for everyone: https://github.com/rainlab/blog-plugin/commit/9c23336e549f1f7e510f714fdc788832e36b8f09
