### ISSUE TITLE
Endless saving

### ISSUE THREAD

**Issue by LZaplata** [rainlab/blog-plugin#572]
Hi,

I found weird behavior in the plugin after upgrading to version 1.5.6, OctoberCMS is is version 3.0.53. When I want to save a post, it looks like saving but never stops and doesn't show flash message. After browser refresh, post changes are in fact saved. What's wrong? Can you help me please? Thanks.

**Comment by daftspunk** [comment]
Hi @LZaplata 

Thank you for reporting this bug. It will be fixed in the next patch release (v3.0.54). Keep an eye on the changelog to see when it becomes available:

https://octobercms.com/changelog

Best regards
