### ISSUE TITLE
Update hint for documentation

### ISSUE THREAD

**Issue by renickbuettner** [rainlab/blog-plugin#573]
By using blog combined with translate - (and the richtext editor) - I used the content_html field several times. But actually this field does not getting translated automatically. The attribute summary and content_html do not translate (if no summary provided). The content attribute is the field to go with.

May we can adjust the documentation/examples of the plugin, to make this more clearly :-) Will reduce time needed for debugging.

**Comment by daftspunk** [comment]
Yes sure, feel free to adjust the documentation of this repo using a pull request.
