### ISSUE TITLE
"Uncaught TypeError: a.indexOf is not a function" error occurs while trying to upload image

### ISSUE THREAD

**Issue by VadimIzmalkov** [rainlab/blog-plugin#576]
I got this error when tried to upload an image in the post editor.

Event-aliase ``.load()`` here https://github.com/rainlab/blog-plugin/blob/master/assets/js/post-form.js#L84 should be replaced by following:

```PHP
$(window).on('load', function(){ ...});
```

**Comment by samgeorges** [comment]
Fixed in v1.6.1

Thanks!
