### ISSUE TITLE
Markdown editor translation issue

### ISSUE THREAD

**Issue by mplodowski** [rainlab/blog-plugin#578]
Blog Plugin version: 1.6.1
Translate Plugin version: 2.0.6
OctoberCMS version: 3.1.12

When you have multisite and 2 languages setup and create new post with primary language, then translate this post with secondary language the "content_html" field is not saved into database table  "rainlab_translate_attributes". Only "content" field is saved. I assume this is an issue with markdown editor. I also tried to change in Blog Settings to use older markdown editor, but it is the same result.

**Comment by samgeorges** [comment]
Hey @mplodowski 

Thanks for this. I'm not sure it ever worked properly. Should be fixed in v1.6.2
