### ISSUE TITLE
No localization for buttons in Editor for Blog pages

### ISSUE THREAD

**Issue by yellotra** [rainlab/blog-plugin#579]
Hey! There are no localization for buttons and tooltips in toolbar of Editor for Blog pages

For example, such buttoms, like Bold, Big Hedaing, Medium Hedaing, Small Hedaing, Code - all buttons in toolbar are not localized. How to fix it manually?

**Comment by daftspunk** [comment]
Hi @yellotra 

The translations for this come from here: https://github.com/octobercms/october/blob/3.x/modules/system/lang/en/client.php

Check to see that your locale has the necessary translations. You are welcome to submit a PR to this repo with new or updated translations.

Best regards

**Comment by yellotra** [comment]
Thank you, colleague. It works!

**Comment by yellotra** [comment]
It does not work. Found the solution: /var/www/october/modules/backend/vuecomponents/documentmarkdowneditor/assets/vendor/easymde@2.12.0/easymde.min.js

**Comment by daftspunk** [comment]
Thanks, this is fixed in the next patch release (v3.2.13)

There are some new language keys added as a result: https://github.com/octobercms/october/commit/4cca5c673df7a5f6d7ef849ff09b3e0761263bce

These should be translated for maximum effect.

Best regards
