### ISSUE TITLE
posts by author

### ISSUE THREAD

**Issue by hmsuchier** [rainlab/blog-plugin#582]
Hi,
 On Octobercms forum, I asked if it could be possible to display all posts by a given author (on a page with author slug): https://talk.octobercms.com/t/rainlab-blog-blog-posts-by-user/1439
Do you think such a feature could be implemented within this plugin?
Thanks!

**Comment by daftspunk** [comment]
Hey @hmsuchier 

Thanks for your question. I have included a detailed answer in your original post:

https://talk.octobercms.com/t/rainlab-blog-blog-posts-by-user/1439

Best regards
