### ISSUE TITLE
Category not found

### ISSUE THREAD

**Issue by gvanto** [rainlab/blog-plugin#586]
I have under my theme pages/blog/category.htm the following (as per docs):
(blog list + post pages are working fine)

```
title = "Category"
url = "/blog/category/:slug/:page?"
layout = "default"

[blogPosts]
categoryFilter = ":slug"
==
function onEnd()
{
    // Optional - set the page title to the category name
    if ($this->category) {
        $this->page->title = $this->category->name;
    }
}
==
{% if not category %}
    <h2>Category not found</h2>
{% else %}
    <h2>{{ category.name }}</h2>

    {% component 'blogPosts' %}
{% endif %}
```

I have two published posts, each with a category assigned.

But on the blog/category/{category} page, I am getting 'No category' found.

Any help much appreciated,
G

On latest ocms 2 version and blog (1.7.0):
![image](https://github.com/rainlab/blog-plugin/assets/8372918/a479f80a-0cd5-4196-851c-5079c18693e5)

**Comment by daftspunk** [comment]
Here is the code that loads the category:
https://github.com/rainlab/blog-plugin/blob/b8afc17c7a525a4646d15dd3f29481cf49382ed4/components/Posts.php#L234-L249

In this case, you need to tweak the page settings to use an external parameter. It looks like this:

```
[blogPosts]
categoryFilter = "{{ :slug }}"
```

I hope this helps!

**Comment by gvanto** [comment]
Works now, thanks! (I think the docs need updating though: https://octobercms.com/plugin/rainlab-blog > Documentation)

**Comment by daftspunk** [comment]
Thanks! Updated the docs too
