### ISSUE TITLE
Class 'October\Rain\Support\Markdown' not found

### ISSUE THREAD

**Issue by stu177** [rainlab/blog-plugin#59]
When creating a new post, it throws a class not found error:

    Class 'October\Rain\Support\Markdown' not found

 Line 7 in models/Post.php has:

    use October\Rain\Support\Markdown;

Has something changed with October causing this path to be wrong as changing line 7 to:

    use Markdown;

Fixes the issue.

**Comment by daftspunk** [comment]
[This is fixed](https://github.com/rainlab/blog-plugin/blob/master/models/Post.php#L7) already, make sure you have `edgeUpdates` enabled as you are on the RC build.
