### ISSUE TITLE
Class 'October\Rain\Support\Markdown' not found

### ISSUE THREAD

**Issue by MFazzolari** [rainlab/blog-plugin#60]
Trying to reproduce the steps on https://vimeo.com/97088926  when I try to create a new blog post I have the following error:

Class 'October\Rain\Support\Markdown' not found
in /home/matias/Projects/Personal/october/plugins/rainlab/blog/models/Post.php line 149

There is an October\Rain\Support\Facades\Markdown class and it has an annotation mentioning that it resolves to October\Rain\Parse\Markdown

![mardownnotfound](https://cloud.githubusercontent.com/assets/2354174/6220823/d382169c-b619-11e4-8c3e-c4aa4c8ee098.jpg)

**Comment by daftspunk** [comment]
Please ensure you are [using `edgeUpdates`](https://octobercms.com/docs/help/troubleshoot#edge-updates), it would appear that you are running a beta version of the blog plugin on the [RC version of October](https://octobercms.com/blog/post/hello-release-candidate).
