### ISSUE TITLE
Duplicating Plugin

### ISSUE THREAD

**Issue by yusufff** [rainlab/blog-plugin#62]
( https://github.com/octobercms/october/issues/956 )
Hi

I want to duplicate a plugin for use another purpose. I am using Blog plugin from Rainlab for listing Stores and I'll use same plugin for listing campaigns and listing movies. Searched for some other blog plugin but there isn't i guess. How can I do that?

Thank you

**Comment by vojtasvoboda** [comment]
You can use Blog categories (Stores, Campaigns, Movies).

**Comment by LukeTowers** [comment]
@vojtasvoboda is correct, either use blog categories, or utilize the [Builder plugin](https://github.com/rainlab/builder-plugin) to build a custom plugin for yourself.
