### ISSUE TITLE
"Error in exception handler." on new post.

### ISSUE THREAD

**Issue by stuarteske** [rainlab/blog-plugin#65]
Route: /backend/rainlab/blog/posts/create  
Rendered: "Error in exception handler."

**Comment by daftspunk** [comment]
Can you show a screenshot or the stack trace?

**Comment by stuarteske** [comment]
Would there be any issues regarding October CMS Beta and RC versions?

![screen shot 2015-03-01 at 20 44 34](https://cloud.githubusercontent.com/assets/488377/6432727/e01da850-c053-11e4-8847-582c48743478.png)
![screen shot 2015-03-01 at 20 44 28](https://cloud.githubusercontent.com/assets/488377/6432728/e01ff4ac-c053-11e4-8ac6-6a6fa2719d18.png)

**Comment by stuarteske** [comment]
![screen shot 2015-03-01 at 20 51 06](https://cloud.githubusercontent.com/assets/488377/6432764/d44a859c-c054-11e4-807e-0cf6858ae5ea.png)

**Comment by daftspunk** [comment]
Yes this is an error caused by using the Beta version of October which is no longer supported.
