### ISSUE TITLE
rain.blog - category and pagination not workiing as expected

### ISSUE THREAD

**Issue by daveharrisonnet** [rainlab/blog-plugin#68]
Can you check there isn't an issue with RC breaking the blog plugin. I have tried dozens of times to set this up as per instruction video on vimeo but although there are no errors clicking on the category from the list does not filter the results it just shows all results again. Also pagination does not seem to work, clicking on  'next' takes me to the 'blog post' page rather than page 2 of 'blog posts' 

I have no error messages or screen shots but I hope my explanation is clear enough ;)

I realise I may have implemented the plugin wrong but I'm pretty sure all is at it should be, based on your video. If you can confirm everything is working as it should I can carry on my end

Is it correct that blog slug and category slug would both be ":slug"
Is it OK that the urls for my 3 pages are as follows

posts page = /articles/:page? - articles.htm
categories page = /articles/category/:slug/:page? - categories.htm
single post page =  /articles/:slug - article-single.htm

FYI, I tried this without the :page slug (not bothered with pagination at the time) and still categories did not work , all posts were shown they were not filtered by category

Also is any of this stored in database? Is it possible if I misconfigured the plugin set-up and then amended it that the amendments didn't get written to database so that no matter how often I tweak the plugin settings it keeps using an incorrect one??

Thanks
D

**Comment by sarahetter** [comment]
I am having the exact same problem. Category pages are not filtering the results, but rather, showing all posts. Otherwise the post list, and the post display pages are working.

I followed along with the video as well.

**Comment by daftspunk** [comment]
There is a minor difference in the screencast and the current implementation, make sure you have the external parameter mode selected when entering the :slug value.

![External param](http://s9.postimg.org/8zs9iyklr/inspector_animation.gif)

**Comment by daveharrisonnet** [comment]
Yeah that works ;) thanks, you fixed in a few seconds what took me hours of troubleshooting and still not fix , lol
Now how do you implement the pagination correctly? When i click on 'next' or a page number it redirects to single post page, although the url says. /articles/3 which looks correct

below are the urls i am using
posts page = /articles/:page? - articles.htm
categories page = /articles/category/:slug/:page? - categories.htm
single post page = /articles/:slug - article-single.htm

Also I have added the page slug :page using external parameter mode

**Comment by daveharrisonnet** [comment]
OK I figured it out. There was a conflict because of how I wanted to refer to my pages. I have changed the posts page to the following URL /articles/all/:page, now all working well, Thanks for your help ;)

**Comment by seanthepottingshed** [comment]
Thanks for the above this sorted out my own issue with the category selection. It would be a good idea
