### ISSUE TITLE
Persistence Route

### ISSUE THREAD

**Issue by ghost** [rainlab/blog-plugin#69]
When accessing https://octobercms.com/blog/category/announcements/2 page, category links on the sidebar also will have page=2

Solution is simple, just disable $routePersistence;
Also we can add 3th parameter to
`setUrl($pageName, $controller, $routePersistence = true)`
function on the Models

```
RainLab\Blog\Models\Category
RainLab\Blog\Models\Post
```

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
