### ISSUE TITLE
post.url not getting populated

### ISSUE THREAD

**Issue by karnold** [rainlab/blog-plugin#72]
On a clean install with the latest git version of this plugin and build 225 of OctoberCMS the $post->url variable is returning null, thus linking post titles to the home page instead of the blog post.

**Comment by karnold** [comment]
sorry, user error. i did not create the appropriate pages.

**Comment by goedda** [comment]
I face the same problem. Would you mind sharing your solution in more detail, please. I have a page for /blog/post/:slug and if I enter the URL(s) manually, I get there, but on the /blogs page, the $post->url variable is still null for all posts...
Rather new to Laravel, OctoberCMS and the blog plugin, thus, bear with me.

**Comment by karnold** [comment]
for the "posts" page I added the "Post List" component and made the url /:page? and for individual blog posts there is a separate page that contains the "Post" component and the url /blog/post/:slug

**Comment by goedda** [comment]
Thanks for the reply. I add the "blogPosts" component for the blog list page and the "blogPost" (singular) for the respective blog post(s) as described in the docs.
Everything but the URLs is working, so I will have to have a night session and hope that I find the problem.

**Comment by goedda** [comment]
Ok, I think I got it. For all that follow:
The "blogPosts" has the property "postPage". This property has the default value "blog/post", which means that the details pages must be - as described in the docs - /pages/blog/post.htm
As my detail page was /pages/blog.htm, I changed the property in my blog list to

[blogPosts]
postPage = "blog"
