### ISSUE TITLE
Backup and Restore

### ISSUE THREAD

**Issue by MikeOracle** [rainlab/blog-plugin#75]
Hey,

Does anyone know if there's support for backup/restore? Where are the blog posts stored by default? Are they in the database? 

My whole goddamned install got nuked when upgrading to RC, and while I managed to recover all of my static content after a reinstall, my blog posts are kaput. 

Any idea on how to get those back?

Thanks,

Mike

**Comment by felixinx** [comment]
The blog post and categories are stock in the `rainlab_blog_posts` table. If you have access to your database, you should be able to get your content back. If not, try to get a backup from the computer or hosting provider.

Good luck! :smile:

**Comment by vojtasvoboda** [comment]
You can use import/export feature.

**Comment by LukeTowers** [comment]
@vojtasvoboda is correct, this plugin now supports importing/exporting your data.
