### ISSUE TITLE
Rain blog posts page pagination not working

### ISSUE THREAD

**Issue by alvi1987** [rainlab/blog-plugin#77]
I have not changed anything. The config is just like following
![blog](https://cloud.githubusercontent.com/assets/2070352/7179546/ef997b58-e45a-11e4-9cfb-0a621e16fd80.png)
but pagination is not working. when clicking in links its always in the first page instead of clicked page.

**Comment by ribsousa** [comment]
I have the same Problem...

**Comment by zile-lhs** [comment]
Try adding /:page parameter to your page URL (top right), so it looks something like /blog/:page. Component is expecting to get page number from the url, but you are not providing it...

**Comment by ribsousa** [comment]
I added the parameter blog/**:page** on the **blog** page but returns 404 error page was not found.

**Comment by ribsousa** [comment]
Solved added blog/**:page?** as docs [plungin] (https://octobercms.com/plugin/rainlab-blog)

**Comment by zile-lhs** [comment]
I'm glad you figured it out! Though in my case I think it worked without question mark...
Anyway, thanks for posting solution, it might help someone else in future.

**Comment by LukeTowers** [comment]
See http://octobercms.com/docs/cms/pages#url-syntax for more information on how to properly form routing parameters
