### ISSUE TITLE
Uploading feature images broken

### ISSUE THREAD

**Issue by RaihaX** [rainlab/blog-plugin#79]
With the new Media Manager update (awesome feature) it appears to have broken the feature image upload. 

When uploading an image it now shows up blank, and you cannot access the image properties modal window.

![image](https://cloud.githubusercontent.com/assets/7531705/7313815/47b9020a-ea90-11e4-9354-49135a1401ac.png)

![image](https://cloud.githubusercontent.com/assets/7531705/7313826/5aa934de-ea90-11e4-903c-80e04a993a2d.png)
(it gets stuck loading the properties box)

I checked the \storage\app\media and the image did upload successfully.

Many Thanks

**Comment by daftspunk** [comment]
Thanks for reporting this - it has been fixed in Build 249

**Comment by RaihaX** [comment]
Awesome, thank you :)
