### ISSUE TITLE
Migrating from WP

### ISSUE THREAD

**Issue by guiligan** [rainlab/blog-plugin#85]
Hey, I was wondering if there is an easy way to migrate from Wordpress to Blog! I'm planning on moving it, but I don't have much free time for it, if there is a way, please enlighten me! Thanks

**Comment by felixinx** [comment]
The blog plugin dosen't have any migration support. October dosen't have too. +1 for migration support.

You can do it manually, but note that the WP syntax and Markdown syntax aren't the same. May be you can find a tool to export the Markdown from post?

**Comment by daftspunk** [comment]
HTML should work in Markdown editor just fine. There is recently an import feature added that you could use.

Ideally it would be cool if someone made a Wordpress -> October plugin.

**Comment by felixinx** [comment]
@daftspunk Someone already made it! [https://github.com/tiipiik/Import](https://github.com/tiipiik/Import). It's old, but it should be functional.

**Comment by daftspunk** [comment]
Cool, it should be on the marketplace so we can promote it.
