### ISSUE TITLE
can i use rainlab.translate plugin with this ?

### ISSUE THREAD

**Issue by alioygur** [rainlab/blog-plugin#87]
can i use rainlab.translate plugin with this ?

**Comment by felixinx** [comment]
No, same problem with the pages-plugin. I am working on it.

**Comment by AramLoosman** [comment]
Soo, how's the work coming along? ;)
I'd be interested to use it on a multilang blog...

**Comment by FelixINX** [comment]
Hi @AramLoosman !

I have stopped my work on the pages plugins but I can work on the blog plugin. Please except some time. I don't think it should be too dificult as it is on models.

**Comment by rsobon** [comment]
Hello. 
I made pull request with translatable markdown editor and blog markdown editor into translate-plugin repo
https://github.com/rainlab/translate-plugin/pull/122

**Comment by daftspunk** [comment]
Plugin supports native translations as of v1.2.5
Refs 1af7be59b4cc28f984cba8c07e3b1f6ce96c6d10
