### ISSUE TITLE
og:image

### ISSUE THREAD

**Issue by serge15** [rainlab/blog-plugin#89]
Hello,

I am trying to setup the featured image as the og:image. How can this be done?
In the facebook debugger I can see the featured image in the post but once I share it, the shared image changes to the blog logo.

Thanks

**Comment by LukeTowers** [comment]
This would need to be setup within your theme as the og:image tags need to be present within the `<head>` element of your site's markup.

**Comment by stephenkeable-allies** [comment]
@serge15 this might be late but I had the same issue and used this code to pass the image to the template:-

```php
function onEnd() {
    $_post = $this->components['blogPost'];
    if ($_post->featured_images->first()) {
        $this->page->og_image = $_post->featured_images->first()->path;
    }
}
```
Which will allow you to use this markup in your template:-

```
{% if this.page.og_image %}
     <meta property="og:image" content="{{ this.page.og_image }}" />
{% else %}
```

**Comment by LukeTowers** [comment]
Got an explanation of how it ain't working anymore @Hessel91?

**Comment by Hessel91** [comment]
Well I get [https://ibb.co/q0kNNqt](this) error when I add the code to the blog post page.
I used `{% if this.page.og_image %}
     <meta property="og:image" content="{{ this.page.og_image }}" />
{% else %}` inside the head of my theme.

**Comment by Hessel91** [comment]
Thank you Luke for notice. It works perfectly now!
