### ISSUE TITLE
Pagination does not work while using postsList on layout as well as page.

### ISSUE THREAD

**Issue by dannydinges** [rainlab/blog-plugin#92]
I've got a layout which includes a postList as a 10 recent posts list on a sidebar. Then I have a page that uses that layout and inside it it has the paginated list of posts. Seems they are colliding and making it so pagination will not work. I tried to alias one of them but it doesn't seem to help. Anyone deal with this problem before and have a solution?

**Comment by petsto** [comment]
Probably really late to answer but if someone else have the same wondering...
You should add ` :page? ` to the end of the page URL.

**Comment by LukeTowers** [comment]
You may also need to set the `pageNumber` property of your paginated list of posts component instance to `1` so that it doesn't try to pull that value from the URL.
