### ISSUE TITLE
how to make search bar?

### ISSUE THREAD

**Issue by keithshih** [rainlab/blog-plugin#96]
I want to create search bar in homepage, search for post's title, content  
How can i do?

**Comment by PascalKleindienst** [comment]
Hi, I needed also a search bar for the posts, so I created a simple Plugin which adds a a simple search form and displays search results. The Code can be found here: https://github.com/PascalKleindienst/october-blogsearch-extension

I have also submitted the plugin to the october marketplace, but it's pendig at the moment. But I hope that helps you :smiley:

**Comment by LukeTowers** [comment]
For anyone else that's curious, there are several [plugins available on the marketplace](http://octobercms.com/plugins/search?search=search) that do this.
