### ISSUE TITLE
How to get author name?

### ISSUE THREAD

**Issue by mateoprifti** [rainlab/blog-plugin#98]
Hello, great plugin. Only issue i have is, how can i get the name of the user which wrote the blog post?

**Comment by nsrosenqvist** [comment]
+1

**Comment by rendler-denis** [comment]
Hello, @mateoprifti! 

I am using the following code to get the user name:
{% set authorName = post.user.getFullNameAttribute() %}

Hope it helps,
Denis

**Comment by LukeTowers** [comment]
@rendler-denis is correct, you can access the user object of the author that created the post through `post.user` in Twig.
