### ISSUE TITLE
Как вывести картинку вместе с постом? {{'How to display a picture with thepost?'|_}}

### ISSUE THREAD

**Issue by TheGreatMax** [rainlab/blog-plugin#99]
Как вывести картинку вместе с постом? {{'How to display a picture with the post?'|_}}
И у меня в задании стоит полный перевод сайта, как можно перевести новости? {{'And how i can translate a blog-content?'|_}}

**Comment by keiosweb** [comment]
^ if you have code editor (default), you can use markdown: 

http://daringfireball.net/projects/markdown/syntax#img

there are plugins on the market that allow to replace code editor with graphical one.

aand you cannot translate content right now, check #87

**Comment by LukeTowers** [comment]
As of https://github.com/rainlab/blog-plugin/commit/1af7be59b4cc28f984cba8c07e3b1f6ce96c6d10 we support translatable blog content.
